### ISSUE TITLE
[Question] "Font is bold" is not checked in Bold weight?

### ISSUE THREAD

**Issue by ShikiSuen** [adobe-fonts/source-han-sans#101]
![image](https://cloud.githubusercontent.com/assets/3164826/7310004/9f864af0-e9e2-11e4-8b4c-871ca2161c37.png)

Firefox would always treat SHS Heavy as "bold" unless "Font is bold" is checked in Bold weight.

I am going to close this issue at first, and the repo administrator could reopen it if he thinks that it is an issue.

**Comment by kenlunde** [comment]
The "bold" bits are set only if the family is style-linked, which we don't do for our CJK fonts.

**Comment by ShikiSuen** [comment]
Then it looks like FireFox might need to do something regarding this.
Thanks for your explanation, I will refer this thread to themex.net since lots of people there have such question.
