### ISSUE TITLE
[Doubts] Compatibility between SHS (Language Specific Release) and Twitter Mac Client App.

### ISSUE THREAD

**Issue by ShikiSuen** [adobe-fonts/source-han-sans#102]
Someone sent me a complaint, he claims that SourceHanSansUI installation package could let Twitter's Mac Client App unable to display some of usernames. After serious investigation, **I have found that it's not my fault, but I couldn't figure out whether it's SHS itself's bug or Twitter app's bug.**

The results of my investigation are the following, based on a fact that SourceHanSans official Language Specific Release set is defined as OS X Yosemite's default GUI font:

1. Source Han Sans 1.002 official SuperOTF, while being used as CJK GUI fallback font in OS X, could display **nothing** in bold weight in Twitter's mac app (only Helvetica Neue effects):
![image](https://cloud.githubusercontent.com/assets/3164826/7311869/854d4856-e9ff-11e4-9565-a48cfdc86269.png)

2. While complete set of Source Han Sans 1.002 official Language-Specific Release (LSR) separate OTF is installed and used as CJK GUI fallback font in OS X, **only Japanese version of Source Han Sans LSR could display some glyphs in bold weight**  in Twitter's mac app (i.e. For Bold fonts in Twitter's mac app, in this case, only Helvetica Neue and 「源ノ角ゴシック Bold」 effects for some users' username):
![image](https://cloud.githubusercontent.com/assets/3164826/7311924/48e253ec-ea00-11e4-8a95-df1f1831fc39.png)

Further tests will be performed if necessary, I am going to left this thread here as reference and invite some volunteers to come here to join this thread for discussion regarding this problem.
---------------------------------------------
I am going to close this issue at first, and the repo administrator could reopen it if he thinks that it is an issue.

**Comment by ShikiSuen** [comment]
// Just a notification towards email-subscription-only watchers that my previous post has been edited. This reply will be removed as soon as it's pushed to your mailbox.

**Comment by ShikiSuen** [comment]
# Update:
Further tests proved that same thing happens if using SHS regional specific release instead.

**Comment by ShikiSuen** [comment]
**Update:**
I have changed all cidfontinfo file to make IsFontBold true (as someone suggested), but it doesn't work in this case.

**Comment by kenlunde** [comment]
s/IsFontBold/IsBoldStyle/ ;-)

**Comment by ShikiSuen** [comment]
^ 了解。次のテストが続きます。

**Comment by ShikiSuen** [comment]
Confirmed, Tried, not work.

**Comment by ShikiSuen** [comment]
@kenlunde This issue has been solved in Source Han Sans 1.003!

**Comment by ShikiSuen** [comment]
Please label this issue as solved.

**Comment by kenlunde** [comment]
Fixed in Version 1.003. Thank you, @ShikiSuen, for confirming!

**Comment by ShikiSuen** [comment]
Your welcome.

**Comment by ShikiSuen** [comment]
Further investigation indicates that the [Asc = 1000, Desc = -234] in hhea table could also trigger this issue.

Since Apple intended to let one family of GUI fonts separated into the following two versions in different cases, I will recommend all people, who wants to use SHS as GUI fonts, to do the following:

- use official SHS in the `monospace` and `sans-serif` section of `DefaultFontFallbacks.plist`... or, at least, keep the official Asc & Desc hhea metrics as-is. (Twitter mac app read the `sans-serif` section of this plist file as its GUI fallback font)

- use modified SHS with [Asc = 1000, Desc = -234] in hhea table in `CTPresetFallbacks.plist` and the `default` section of DefaultFontFallbacks.plist

This suggestion applies onto all OS X releases since Yosemite.

**Comment by ShikiSuen** [comment]
Update:

In order to keep this problem not happen, in case of HHEA LineGap = 0, the HHEA Ascender & Descender should be **not less than** a certain value set and they should keep a certain proportion.

What I recently tested proved that [1010, -241] is a safe metric set for SHS / OHS-UI's HHEA Ascender & Descender for OS X / iOS GUI font purposes. (may work with GNOME; does not work with KDE)

**Comment by ShikiSuen** [comment]
(I updated my last reply regarding the font metrics, please discard the mail notification of my last reply if it has been sent to your mailbox.)

**Comment by ShikiSuen** [comment]
Update: There is absolutely no resolution in such issue unless the font that Twitter4Mac official client uses CJK Fallback UI font with its <hhea> LineGap non-zero.

Meanwhile, Source Han Sans has no duty on this, even though I issued this: https://github.com/adobe-fonts/source-han-sans/issues/129 .

I will try my way to contact Twitter to let them aware of their mistake on this:
> For the sake of your customers, please refer <default> in lieu of <sans-serif> section from DefaultFontFallbacks.plist for UI font purposes.
(Such fault let their mac client app reads `PingFang` but not `.PingFang`, and the problem comes.)

**Comment by ShikiSuen** [comment]
@kenlunde Could you please throw a tag of "not-this-product" on this thread? Thanks.

**Comment by ShikiSuen** [comment]
I edited my previous post to make sure it displays `hhea` correctly.
