### ISSUE TITLE
Style links

### ISSUE THREAD

**Issue by RyanChng** [adobe-fonts/source-han-sans#103]
Just wondering, why are the regular and bold fonts not style-linked? It would be useful to style-link those 2 so that we can install those two and use it as a font with regular and bold, so the end-user experience would feel something like Source Sans Pro. Currently, installing the Regular and Bold weights gives me 2 fonts in the font menu (Windows).

for example, when I have a document in Microsoft Yahei, it has bold headings, but when I change the font to SHS, I have to unbold the headings and change their font to SHS Bold... I can't just change the font for all.

**Comment by kenlunde** [comment]
We have traditionally and intentionally not style-linked our CJK fonts for a variety of reasons, whose practice obviously carried forward with Source Han Sans (and Noto Sans CJK). For those existing CJK fonts that are style-linked, they have been designed to be used in relatively contained environments (aka bundled with an OS) and available only in the two weights that are to be style-linked.

In any case, I will close this issue for now, but I set a note for myself to explore the possibility of style-linking for the next version of Source Han Sans.

Thank you for posting this issue.

**Comment by rschiang** [comment]
@kenlunde Since font support is limited on some devices (e.g. e-book reader), which require style linking for SHS to work properly; is there any possibility we could build a style-linked version of SHS out of source? Maybe some manipulation on `FontMenuNameDB`?

**Comment by kenlunde** [comment]
Thank you for raising this issue again, because it is something I would like to address in the Version 2.000 update that should happen sometime this year. For this reason, I am reopening it.

If you can wait a few days, I can try to assemble a set of style-linked fonts (let me know which specific Regular and Bold OTFs you'd like me to use for this purpose) for you to test.

In terms of what files need to be adjusted, that would be the _FontMenuNameDB_ (I would create a separate one with a unique filename) and the _cidfontinfo_ files for only the Bold weight.

**Comment by rschiang** [comment]
Thanks @kenlunde for such positive feedback. I was trying to bring SHS TW variant to work on embedded devices, so Regular and Bold weight should be sufficient. :) 

(Due to the fact that FontForge cannot handle SHS correctly, thus difficult for individuals to tamper with font metadata [style linking for example], it would be nice if we shed some lights on customizing the build using AFDKO.)

**Comment by kenlunde** [comment]
@rschiang: Please try [these fonts](http://blogs.adobe.com/CCJKType/files/2016/03/SHSTW-StyleLinked.zip). If I built them correctly, they should be properly style-linked.

**Comment by kenlunde** [comment]
@rschiang: If the test fonts that I built for you work as expected, in terms of style-linking Regular to Bold, this was done by doing only two minor things:

- I changed the *IsBoldStyle* keyword in the Bold weight's *cidfontinfo* file from false to true, which sets the OS/2.selection value to 0x0020 (Bold).

- I created an alternate *FontMenuNameDB.SL* file that simply removes the "l=" lines from both the Regular and Bold weights.

Below are the style-linked FontMenuNameDB records:

```
[SourceHanSansTW-Regular]
        f=3,1,0x404,\601D\6E90\9ED1\9AD4 TW
        s=3,1,0x404,Regular
        f=Source Han Sans TW
        s=Regular

[SourceHanSansTW-Bold]
        f=3,1,0x404,\601D\6E90\9ED1\9AD4 TW
        s=3,1,0x404,Bold
        f=Source Han Sans TW
        s=Bold
```

**Comment by rschiang** [comment]
@kenlunde: I've tested the font files on a Kobo eReader (without TTC support, treat subset OTF weights as individual families.) 
![Working example](https://cloud.githubusercontent.com/assets/1512231/13468903/f7df57ec-e0df-11e5-9d7f-c1e14c155683.JPG)

They are handled correctly, so style-linking must have worked! Thanks again for providing the builds and hacking instructions. :beer:

**Comment by kenlunde** [comment]
@rschiang: Excellent. Many thanks for confirming that the style-linking works as expected. I may add the necessary files and instructions to the project in the next few days, and will consider making this standard behavior (for Regular and Bold) for the Version 2.000 update.

**Comment by kenlunde** [comment]
@rschiang: I just added to the repository the files (three new FontMenuNameDB files plus 12 new cidfontinfo files) and commands (in the COMMANDS.txt file) necessary to building style-linked Regular and Bold fonts.

**Comment by rschiang** [comment]
@kenlunde++ Glad to know that!

**Comment by kenlunde** [comment]
As I have added the necessary files to the master branch to enable this, and because I have a plan to style-link the Regular and Bold weights in the next version, in terms of the release branch, I will now close this issue.

**Comment by kenlunde** [comment]
Consolidated with Issue #181.
