### ISSUE TITLE
Usage for Corporate marketing assets

### ISSUE THREAD

**Issue by t-yashima** [adobe-fonts/source-han-sans#104]
Dear, 
My client  is a Jpanaese subsidiary company of a global company. They are planning to use Japanese versions of source-han-sans fonts for their marketing creative assets (brochure, catalog, video, and etc,). We have read Readme and FAQ, but the client would like get more explicit confirmation about they are allowed to do so. Could you please help me on this issue?
Best Regards,

**Comment by kenlunde** [comment]
The terms of the (open source) license permits such uses. The details are in the LICENSE.txt file.

Enjoy!

**Comment by t-yashima** [comment]
Dear,
 
Thank you very much, for a quick reply!!
 
Best Regards,
