### ISSUE TITLE
TW subset renders as unrecognized characters with “Mac” smoothing in Photoshop CC

### ISSUE THREAD

**Issue by zhusee2** [adobe-fonts/source-han-sans#105]
I just found that the Source Han Sans TW subset fonts can be faulty rendered in Photoshop CC 2014, if chose the “Mac” or “Mac LCD” smoothing option. But it looks as designed under other smoothing options.

The screenshot below shows that the TW subset font being correctly rendered under “Smooth” smoothing in Photoshop:
![Correct font render](https://cloud.githubusercontent.com/assets/365035/7509442/2a74d952-f4c3-11e4-8b1b-803eb2c86204.png)

while this one shows the TW subset font is rendered as random characters under “Mac” smoothing:
![Incorrect font render](https://cloud.githubusercontent.com/assets/365035/7509443/2b888e9c-f4c3-11e4-8d08-5556bdadc692.png)

**Comment by ShikiSuen** [comment]
Please use language-specific release, not the subset release, to avoid this issue.

**Comment by kenlunde** [comment]
This was already posted as Issue #67. It is an issue with Photoshop in that its "Mac LCD" mode assumes that GIDs equal CIDs for Adobe-Identity-0 ROS OpenType/CFF fonts. The good news is that Photoshop CC 2015, which will be released soon, fixes this.

And, as @ShikiSuen kindly pointed out, the workaround is to use the language-specific OTFs for which GIDs equal CIDs.

**Comment by zhusee2** [comment]
Thank you for pointing this out!



—

**Comment by kenlunde** [comment]
This should now be fixed in Photoshop CC 2015.
