### ISSUE TITLE
A bug probably concerning the recently added feature 'hist'

### ISSUE THREAD

**Issue by jimmymasaru** [adobe-fonts/source-han-sans#107]
When I used TTX to dump SHS, I got the following content in the xml.
      &lt;Lookup index="31">
        &lt;LookupType value="1"/>
        &lt;LookupFlag value="0"/>
        &lt;!-- SubTableCount=1 -->
        &lt;SingleSubst index="0" Format="1">
          &lt;Substitution in="cid65353" out="glyph67212"/>
        &lt;/SingleSubst>
      &lt;/Lookup>
The value of @out is glyph67212.
I checked the features file and it's correct:
feature hist {
  substitute \65353 by \1676;
} hist;
I don't know if it's a bug/issue of cidfont.ps.otc.* or of AFDKO or of TTX.
And I understand it doesn't impact anything practically, but i think it might be an internal mistake during the updating of SHS.

Thanks.

**Comment by kenlunde** [comment]
This is definitely a TTX problem. This isn't the first time that these fonts have exposed issues in tools, including our own, due to the number of glyphs being at the architectural limit.

**Comment by kenlunde** [comment]
BTW, are you using the TTX that is bundled with AFDKO? If so, you might try to get the latest version of TTX to see if it exhibits this behavior. If so, please report it to @behdad.

**Comment by kenlunde** [comment]
@jimmymasaru: See [nototools Issue 25](https://github.com/googlei18n/nototools/issues/25).

**Comment by behdad** [comment]
Fixed in fonttools now.

**Comment by jimmymasaru** [comment]
Thank you both so much.
