### ISSUE TITLE
Strokes in 等(U+7B49) for TW & HK

### ISSUE THREAD

**Issue by itsnotvalid** [adobe-fonts/source-han-sans#108]
As noticed in other system fonts (e.g. Mac's and Windows) the stroke form have the 土 part of the character, while in this font, it becomes 士. Would it be better to change it to be consistent with them?

Thanks.

**Comment by kenlunde** [comment]
The conventions set forth by Taiwan MOE specify that the top component of 寺 is 士, not 土. For all other regions, including Hong Kong (also Traditional Chinese), the convention is to use 土 as the top component. When we add Hong Kong support (see Issue #48), the top component of 寺 and other Big Five or Hong Kong SCS characters that use 寺 as a component, will reflect 土.
