### ISSUE TITLE
[Investigating] SHS head-cut problem while being used as fallback font in Youtube.

### ISSUE THREAD

**Issue by ShikiSuen** [adobe-fonts/source-han-sans#109]
I tested both official releases of SHS 1.003 and my finished SHS-UI 1.003 (they have only ascender & descender differences among their hhea tables), both have such phenomenon.

The following examples are made under such circumstances:

Browser: Chrome 43.0.2357.124 (64-bit) and Safari 8.1 (11601.1.32.10)
System: Both OS X Yosemite 10.10.4 Beta seed 14E33b and  OS X El Capitan Developer Beta 1.
Tested webpage: https://www.youtube.com/user/love610free
Default system CJK fallback font: SHS official super-OTC release 1.003

The phenomenon are presented as following:
![image](https://cloud.githubusercontent.com/assets/3164826/8129181/b5dbc76e-10c3-11e5-9618-31b3d19edb5e.png)

More screenshot attachments will be posted in further reply.

(I will close this first since it is now "phenomenon", let Adobe judge whether it is a bug or not.)

**Comment by ShikiSuen** [comment]
This screenshot is made under OS X El Capitan, while the previous one is made under OS X Yosemite.
![image](https://cloud.githubusercontent.com/assets/3164826/8129227/3780d07a-10c4-11e5-96db-a2774c1367ee.png)

**Comment by ShikiSuen** [comment]
I guess that this might not be SHS's issue since I tested PingFang and get the same result.

I don't know how to let Youtube Team take a glance at this issue, but they have to do something regarding this.

**Comment by kenlunde** [comment]
Just out of curiosity, is this issue specific to this particular website?

**Comment by ShikiSuen** [comment]
@kenlunde For website, I could only remember that Youtube has such problem among random webpage elements in random dates and occasions before... but now it definitely happens.

For Adobe flash player content in some video websites (e.g. Youku, acfun, etc.), this problem happens.

**Comment by ShikiSuen** [comment]
* supplemental intel regarding my last reply:

The similar issue, which happens among some Adobe Flash contents in those websites I mentioned above, are issues happened with previous releases... and I haven't done sufficient test regarding SHS 1.003 official release.
