### ISSUE TITLE
Font metrics in Pleco

### ISSUE THREAD

**Issue by RyanChng** [adobe-fonts/source-han-sans#110]
Hi,

I use Pleco, a Chinese dictionary app, to learn Chinese on my Android. The app gives us the opportunity to use a custom .ttf or .otf font for the interface and definitions. I have tried using SHS, but for some reason the metrics are off rendering it unusable. I thought 1.003 would have fixed the problem (I'm not very sure about the technical details, but seeing that the vertical metrics were adjusted, it gave me hope). However, when I tested the new fonts, they still presented the same issue. Anyone has an idea what is the problem? (No other font has given me this issue on Pleco so far). If anyone can help please reply, or if this issue needs to be merged then please do so. Thanks!
![screenshot_2015-06-12-19-51-31](https://cloud.githubusercontent.com/assets/11143315/8129609/77e96284-113d-11e5-8838-552c7aba2d28.png)
![screenshot_2015-06-12-19-51-40](https://cloud.githubusercontent.com/assets/11143315/8129610/77ef197c-113d-11e5-9cdf-94c55c96dd64.png)

**Comment by RyanChng** [comment]
Here are some screenshots taken using another font that does not exhibit this problem (Hiragino Sans GB W3)
![screenshot_2015-06-12-20-08-26 1](https://cloud.githubusercontent.com/assets/11143315/8129776/13a0f614-113f-11e5-88cb-caf82d97c139.png)
![screenshot_2015-06-12-20-08-33 1](https://cloud.githubusercontent.com/assets/11143315/8129778/19aaf5be-113f-11e5-8886-ae0bcf102200.png)

**Comment by ShikiSuen** [comment]
Probably because Android reads incorrect metrics from SHS...

**Comment by kenlunde** [comment]
It looks like Pleco is reading the vertical metrics from a completely different location, and judging from the glyph placement, my bet is on _head.yMin_ and _head.yMax_. There is no way to override these values, as they represent the FontBBox.

The FontBBox of SHS is unusually tall due to the inclusion of glyphs for U+3031 and U+3032, along with vertical versions of U+2E3A and U+2E3B.

Have you contacted the developer of Pleco?

**Comment by RyanChng** [comment]
I see. So, as I partially suspected, the issue isn’t with SHS. It seems the Pleco developers had considered this issue (SHS is available as a font on the iOS version), and simply decided not to use it in Android. For a bit of context, Android Pleco defaults to a non-fallback font (XinGothic). They were considering SHS at some point but seems they found the metrics unusable and decided not to use it. Never mind, in the meantime I’ll look for another solution. Thanks for clarifying!

**Comment by kenlunde** [comment]
@RyanChng: Pleco is not the first app to incorrectly use FontBBox values for line layout. For some fonts, it doesn't matter, but fonts such as SHS that include these excessively tall (vertical-only) glyphs for particular characters, such app shortcomings are more easily exposed.
