### ISSUE TITLE
Suggestion: Split the release zipball/tarball into four individual zipballs/tarballs.

### ISSUE THREAD

**Issue by jakwings** [adobe-fonts/source-han-sans#111]
It is a little pain in a slow network. ;-)

**Comment by jakwings** [comment]
:ok_hand: I see the zip files in the subdirectories on the release branch. Maybe you'd like to give a notice for this.

**Comment by kenlunde** [comment]
I'll add a note to the README.md file of the release branch. Thank you for the suggestion.

While the additional ZIP files make downloading all weights for specific languages and formats easier, it made the release branch larger. The entire ZIP file is over 1.5GB!

**Comment by jakwings** [comment]
Good. Also better to leave some links to the zip files in the release notes.

I've collect the links for you:

```
OTC - ExtraLight/Light/Normal/Regular:
https://github.com/adobe-fonts/source-han-sans/blob/1.003R/OTC/SourceHanSansOTC_EL-R.zip?raw=true
OTC - Medium/Bold/Heavy:
https://github.com/adobe-fonts/source-han-sans/blob/1.003R/OTC/SourceHanSansOTC_M-H.zip?raw=true

OTF - Japanese:
https://github.com/adobe-fonts/source-han-sans/blob/1.003R/OTF/SourceHanSansJ.zip?raw=true
OTF - Korean:
https://github.com/adobe-fonts/source-han-sans/blob/1.003R/OTF/SourceHanSansK.zip?raw=true
OTF - Simplified Chinese:
https://github.com/adobe-fonts/source-han-sans/blob/1.003R/OTF/SourceHanSansSC.zip?raw=true
OTF - Traditional Chinese:
https://github.com/adobe-fonts/source-han-sans/blob/1.003R/OTF/SourceHanSansTC.zip?raw=true

OTF - Japan - HW:
https://github.com/adobe-fonts/source-han-sans/blob/1.003R/OTF/SourceHanSansHWJ.zip?raw=true
OTF - Korean - HW:
https://github.com/adobe-fonts/source-han-sans/blob/1.003R/OTF/SourceHanSansHWK.zip?raw=true
OTF - Simplified Chinese - HW:
https://github.com/adobe-fonts/source-han-sans/blob/1.003R/OTF/SourceHanSansHWSC.zip?raw=true
OTF - Traditional Chinese - HW:
https://github.com/adobe-fonts/source-han-sans/blob/1.003R/OTF/SourceHanSansHWTC.zip?raw=true

SubsetOTF - CN:
https://github.com/adobe-fonts/source-han-sans/blob/1.003R/SubsetOTF/SourceHanSansCN.zip?raw=true
SubsetOTF - JP:
https://github.com/adobe-fonts/source-han-sans/blob/1.003R/SubsetOTF/SourceHanSansJP.zip?raw=true
SubsetOTF - KR:
https://github.com/adobe-fonts/source-han-sans/blob/1.003R/SubsetOTF/SourceHanSansKR.zip?raw=true
SubsetOTF - TW:
https://github.com/adobe-fonts/source-han-sans/blob/1.003R/SubsetOTF/SourceHanSansTW.zip?raw=true

SuperOTC:
https://github.com/adobe-fonts/source-han-sans/blob/1.003R/SuperOTC/SourceHanSans.ttc.zip?raw=true
```

Same goes for 1.002R and 1.001R.

But [1.001R](https://github.com/adobe-fonts/source-han-sans/tree/1.001R/) does not provide zip files other than SourceHanSans.ttc.zip (SuperOTC).

**Comment by kenlunde** [comment]
Thank you. I will try to get the updated README.md done in the next day or two.

**Comment by kenlunde** [comment]
I will probably use URLs that replace "blob/1.003R" with "raw/release" and remove the trailing "?raw=true" so that the user simply gets the latest version, and I won't need to muck with URLs for each release.

**Comment by jakwings** [comment]
That's fine. You can also replace `blob/1.003R` with `raw/1.003R` and remove the trailing `?raw=true` (Just tried).

**Comment by CNMan** [comment]
Google has a nice download page for Noto Fonts, You can easily download the full fonts package or a separate fonts package.
https://www.google.com/get/noto/

**Comment by kenlunde** [comment]
Given that the Noto Sans CJK fonts are 100% identical to the equivalent Source Han Sans fonts other than name, using the former fonts is certainly an option. What I plan to do this weekend is to update the README.md file, which represents the landing page of the release branch, to provide convenient download links for the assorted ZIP file.

Note that Google is moving the Noto Sans CJK fonts to the [noto-cjk](https://github.com/googlei18n/noto-cjk) project on GitHub, though they still plan to maintain their separate landing page.

**Comment by kenlunde** [comment]
Fixed.
