### ISSUE TITLE
JP hiragana/katakana vertical glyphs are old (same as 1.000) since 1.002

### ISSUE THREAD

**Issue by mm-jikasei** [adobe-fonts/source-han-sans#112]
Hiragana/Katakana glyphs has been updated in the SHS 1.001.
but, the vertical Hiragana/Katakana glyphs were rollback to 1.000 from 1.002.
![shs 1.003 Hiragana/Katakana](https://cloud.githubusercontent.com/assets/12693275/8142998/c9656458-11d0-11e5-8a2d-266154125b1b.png)

**Comment by kenlunde** [comment]
Thank you for catching this! I am now trying to figure out how this could have happened.

**Comment by kenlunde** [comment]
While I am not completely sure how these glyphs were reverted to their pre-1.001 forms, I now have the correct glyphs staged in my backend sources.

**Comment by kenlunde** [comment]
Fixed in Version 1.004.
