### ISSUE TITLE
FreeType rasterizer does not work well when generating bitmap for too many glyphs

### ISSUE THREAD

**Issue by medicalwei** [adobe-fonts/source-han-sans#117]
Steps to reproduce:
1. Generate all bitmaps for a Chinese font at once
2. Some bitmap glyphs are ugly, and if we regenerate once for the selected glyph of small volume it will be redrawn well.

**Comment by kenlunde** [comment]
Based on the description of this issue, it is clearly an issue for FreeType, not for the Source Han Sans fonts.

**Comment by medicalwei** [comment]
Sorry I posted on the wrong issue tracker
