### ISSUE TITLE
Please add U+2C386 (𬎆, ⿰王莹)

### ISSUE THREAD

**Issue by MingFan617** [adobe-fonts/source-han-sans#118]
Ken,
This ideograph,𬎆,is from XinHua dictionary,a famous dictionary in China.Almost every family have this dictionary.Most family like to give their children's name using ideographs in this dictionary.The ideograph 𬎆,both its glyph and meaning are really good,so many people in China use this ideograph in their names.But this character was encoded just about one month ago,so there are many support problems of this character.
Android 5.0 use the font SHS,so the characters in SHS can be identified by most new mobile phones,that create a good chance to popularize new CJK character.So included this character in SHS can solve many support problems for this character, and also SHS can be popularized further in China.
Thank you very much :)

**Comment by mrhso** [comment]
For example:
![vlcsnap-2015-05-01-08h26m31s720](https://cloud.githubusercontent.com/assets/13294467/8635903/60037734-2873-11e5-8637-79ac73feb6d1.png)
Hmm…

**Comment by kenlunde** [comment]
Given that the glyph set is effectively and literally full (at the architectural limit)—but with a very small number of *reserved* glyphs at the end for break-the-glass-for-emergency purposes, 21 of which were consumed during the Version 1.002 update—support for any new character beyond the original scope of the project must be carefully weighed and considered.

To put this into better perspective, Unicode Version 8.0 includes 80,388 CJK Unified Ideographs, but the Source Han Sans glyph set supports only 29,777 (37%) of those code points.

**Comment by mrhso** [comment]
Hai Liang:
到项目后期已经在精打细算每一个字形了（比如早期版本中受国标误导有一个简中的单横「¥」变体，后来我们反馈说没有必要，于是小林剑很高兴我们又释放了一个字形的空间……）。
It may be placed in the released glyph.

**Comment by kenlunde** [comment]
Consolidated with Issue #115.

**Comment by kenlunde** [comment]
Consolidated with Issue #180.
