### ISSUE TITLE
Raw glyphs before merging contours

### ISSUE THREAD

**Issue by jimmymasaru** [adobe-fonts/source-han-sans#119]
Is it possible to offer the glyphs of the two extreme weights in the form **before merging contours (overlaps)**?

**Comment by kenlunde** [comment]
We can certainly consider this request, which would amount to adding two unhinted 65,535-glyph CIDFont resources to the master branch of the project, but the soonest that this could potentially happen would be for Version 2.000.

Keep in mind that the outlines are scaled, on a per-weight and per-script basis, as one of the processing steps. The glyphs for ideographs and bopomofo are scaled to 98% for ExtraLight through Medium, 99% for Bold, and left as-is (100%) for Heavy. The glyphs for hangul are scaled in the same way, but are additionally scaled 98% across all weights (meaning 96.04% for ExtraLight through Medium, 97.02% for Bold, and 98% for Heavy), and are also shifted down 10 units after scaling is applied.

**Comment by davelab6** [comment]
> We can certainly consider this request, which would amount to adding two unhinted 65,535-glyph CIDFont resources to the master branch of the project, but the soonest that this could potentially happen would be for Version 2.000.

Perhaps they could be added to a "pre-processing" branch?

**Comment by kenlunde** [comment]
@davelab6: While we are taking this request seriously, I am still pondering how to best deploy the compatible masters. Your suggestion of the pre-processing branch, or possibly folder with a comparable name, are definitely candidates.

**Comment by be5invis** [comment]
@davelab6 @kenlunde 
A build script using FDK or otfcc?

**Comment by kenlunde** [comment]
A plan is in place, so I will close this issue.

**Comment by NightFurySL2001** [comment]
Quick question: will the overlap versions still be released as planned? It is mentioned in https://github.com/adobe-fonts/source-han-sans/issues/149 that the two extreme masters are now incompatible to be interpolated. How will the project proceed on this regard?

**Comment by punchcutter** [comment]
@NightFurySL2001 Do you mean the non-overlap versions before overlap removal is done? In that case, yes, the plan is to continue as mentioned above and provide those sources.

**Comment by NightFurySL2001** [comment]
@punchcutter Yes, thank you. Any expected time that the plan will be on-going?

**Comment by punchcutter** [comment]
We are currently working on it in addition to other updates and fixes, but there is no specific timeframe at the moment. Hopefully this will be part of the next release, but I don't know when that will be yet.

**Comment by lapomme** [comment]
Is this planned for Source Han Serif as well?

**Comment by punchcutter** [comment]
@lapomme Yes, Serif production will follow Sans for the most part.

**Comment by weiweihuanghuang** [comment]
Any updates here?
