### ISSUE TITLE
Radical ⻐⻠in some characters have bugs

### ISSUE THREAD

**Issue by jimmymasaru** [adobe-fonts/source-han-sans#120]
The last stroke of component ⻐ in some characters like 钮 钵 钯 ⋯⋯ need fixing.
And also ⻠ in 饪, etc.

<img width="493" alt="screen shot 2015-07-26 at 14 08 48" src="https://cloud.githubusercontent.com/assets/12769660/8892235/bc0926ca-33a2-11e5-86e8-b8e0e0f4d54c.png">

**Comment by jimmymasaru** [comment]
Please also check 诫 议, etc...
译 苌 are also weird but I don't know if they can be counted as a bug.
Thanks.

**Comment by kenlunde** [comment]
This should be consolidated with Issue #99.

**Comment by kenlunde** [comment]
Thank you. I determined that the Heavy masters exhibit this issue, which means that most of the five intermediate weights will exhibit it as well. Anyway, I am closing this issue, to be consolidated with Issue #99.

**Comment by kenlunde** [comment]
Consolidated with Issue #178.
