### ISSUE TITLE
Will there be monospace font?

### ISSUE THREAD

**Issue by laichiaheng** [adobe-fonts/source-han-sans#123]
As title, will there be monospace font?

**Comment by kenlunde** [comment]
The HW (Source Han Sans) and Mono (Noto Sans CJK) is the closest thing to a monospaced version, which uses half-width glyphs for the ASCII range. Although it is Japanese-only right now, you can also explore [Source Han Code JP](https://github.com/adobe-fonts/source-han-code-jp).

**Comment by laichiaheng** [comment]
Oh! Thanks! I found TraditionalChineseHW in the OTF folder.
