### ISSUE TITLE
How do I enter https://github.com/adobe-fonts/source-han-sans/tree/release?

### ISSUE THREAD

**Issue by laichiaheng** [adobe-fonts/source-han-sans#124]
I can't fine tree folder in https://github.com/adobe-fonts/source-han-sans/

**Comment by laichiaheng** [comment]
Sorry, I found the way to get in.

**Comment by kenlunde** [comment]
For the installable font resources, you want to access the [release](https://github.com/adobe-fonts/source-han-sans/tree/release) branch.
