### ISSUE TITLE
Improving compatibility with Windows 10 by adding a specific <gasp> table.

### ISSUE THREAD

**Issue by ShikiSuen** [adobe-fonts/source-han-sans#128]
This suggestion is recommended to be addressed onto Source Han Sans 2.00 and later versions.

Windows 10 now reads the following <gasp> table. If such table with such content exists, Windows 10 won't read hinting data while rendering texts with DirectWrite.

    <?xml version="1.0" encoding="UTF-8"?>
    <ttFont sfntVersion="\x00\x01\x00\x00" ttLibVersion="2.5">

      <gasp>
        <gaspRange rangeMaxPPEM="65535" rangeGaspBehavior="10"/>
      </gasp>

    </ttFont>
In such case, the rendered CJK glyphs (without reading hinting data) will be looked similar as what they appear on Mac OS X. I suggest you to attach such table with further releases of Source Han Sans.

Sampled Screenshots (using Microsoft YaHei hacked with such <gasp> table):
![image](https://cloud.githubusercontent.com/assets/3164826/9597035/66870f0a-503a-11e5-9c8a-917b90129d7a.png)
![image](https://cloud.githubusercontent.com/assets/3164826/9597041/893de4d8-503a-11e5-8899-c03dd4c85522.png)

Under Retina Display (200% Hi-DPI):
![image](https://cloud.githubusercontent.com/assets/3164826/9597039/7ca2653c-503a-11e5-81e0-4dc8278fbf1d.png)

Reference:
http://bbs.themex.net/showthread.php?t=16903935

**Comment by ShikiSuen** [comment]
Looks like there's something wrong with the markdown editor here, I present that table again as screenshot:
![image](https://cloud.githubusercontent.com/assets/3164826/9597082/1637faea-503b-11e5-8741-c55c9a74fe9f.png)

**Comment by miguelsousa** [comment]
@ShikiSuen have you tried adding this table to any of the current Source Han Sans fonts?
**gasp** is a table specific to the TrueType font format. All Source Han Sans fonts are OpenType/CFF format, so my guess is that adding this **gasp** table to the fonts will not have any effect in the way the fonts are rendered on screen.

**Comment by ShikiSuen** [comment]
@miguelsousa I am going to try. But my experience told me that Source Han Sans (till current build) shown in Windows build of Google Chrome (using DirectWrite) still looks like it uses ClearType hinting.

DirectWrite is wonderful, but could be awful if used with ClearType Hinting together. Esp. for CJK fonts.

**Comment by kenlunde** [comment]
@ShikiSuen I was going to post the same thing that @miguelsousa wrote. In any case, please keep us posted.

**Comment by ShikiSuen** [comment]
@kenlunde The most recent test on Windows 10 proved that adding such table onto SHS makes no difference. Topic closed.

**Comment by ShikiSuen** [comment]
P.S.: If under the same LowDPI mode, SHS looks worse on Windows 8 / 10 comparing to what it looks like under OS X while using the same 9px or 12px small size.

**Comment by kenlunde** [comment]
OS X uses a completely different rendering engine than Windows. In many ways, OpenType/CFF remains a second class citizen on Windows, perhaps because Microsoft deploys only TrueType fonts on Windows, but Apple deploys OpenType/CFF and TrueType fonts on OS X.
