### ISSUE TITLE
Source Han Sans HW can't be found in some IDEs' settings

### ISSUE THREAD

**Issue by showerying** [adobe-fonts/source-han-sans#130]
Hi,
I'd like to use Source Han Sans HW CN as my default editor font, but I can't find it in the font list of Android Studio (or Intellij Idea).

**Comment by tamcy** [comment]
Not sure what happened behind the hood (could it be Java's OTF support?), but you may try the [Kaigen Gothic](https://github.com/akiratw/kaigen-gothic/releases/tag/v1.004.20150912) fork, which is basically Source Han Sans converted to ttf format, as a workaround. I can successfully use it as my secondary editor font in Intellij based products (PHPStorm and Android Studio).

**Comment by cwchien** [comment]
I use IntelliJ IDEA 14, too. Source Han Sans is not supported.
As @tamcy said, Kaigen Gothic works very smoothly.
It also has HW version as well.
