### ISSUE TITLE
Please correct the top (middle) part of 釁 in Chinese (and maybe Japanese?)

### ISSUE THREAD

**Issue by orangeparanoid** [adobe-fonts/source-han-sans#131]
Please refer to the screenshots and decide if the character needs to be corrected:

![yan_means_challenge_compare](https://cloud.githubusercontent.com/assets/8391509/10558429/1041764e-7501-11e5-89d1-26fa1c369083.png)

![yan_means_challenge](https://cloud.githubusercontent.com/assets/8391509/10558430/1bb67754-7501-11e5-918f-1a2edb3922fc.png)

![yan_means_challenge_tw](https://cloud.githubusercontent.com/assets/8391509/10558431/238bed92-7501-11e5-8630-7edca5ee6958.png)

**Comment by kenlunde** [comment]
I am not sure how you are displaying the glyphs from the Traditional Chinese fonts, but U+91C1 definitely maps to a glyph of the correct shape (see the screenshot below), which is CID+41321.
<img width="602" alt="uni91c1-tw_cid41321" src="https://cloud.githubusercontent.com/assets/3988788/10558746/62022f8a-7490-11e5-8ea2-c9cf8a765d26.png">

**Comment by orangeparanoid** [comment]
It is a possible bug in LibreOffice, not in Source Han Sans.

https://bugs.documentfoundation.org/show_bug.cgi?id=94066

**Comment by orangeparanoid** [comment]
Closed.

**Comment by orangeparanoid** [comment]
I would like to reopen this issue. See the Microsoft Word screenshot:
![yan_challenge_in_ms_word](https://cloud.githubusercontent.com/assets/8391509/10562082/90085d82-757b-11e5-8570-2b5104c10c5c.JPG)
This is a screenshot on Windows. The Simplified Chinese character should be amended.

**Comment by jimmymasaru** [comment]
If you compare this character with SimSun or Microsoft YaHei, you would find it is correct according to China's standard.

**Comment by kenlunde** [comment]
+1

Welcome to the world of Pan-CJK fonts. &#x263A;

**Comment by kenlunde** [comment]
Here's an excerpt from the Unicode (ISO/IEC 10646) code charts.
<img width="978" alt="uni91c1" src="https://cloud.githubusercontent.com/assets/3988788/10562174/80441f04-7502-11e5-8ee0-4aa32bff9b03.png">

**Comment by orangeparanoid** [comment]
According to 通用规范汉字表 (in 2013) and 现代汉语词典2002年增补本, the character is correct. No change is necessary in the Simplified Chinese font.  

The screenshot is 通用规范汉字表 (in 2013) .

Closed.

![yan_challenge_in_ty_in_china](https://cloud.githubusercontent.com/assets/8391509/10562365/398f4e1a-758b-11e5-81ec-a1dc98db89ac.png)
