### ISSUE TITLE
HW fonts not listed as monospaced font in applications

### ISSUE THREAD

**Issue by Vdragon** [adobe-fonts/source-han-sans#132]
Some application only listed monospaced fonts in the font selection dialog(e.g. Konsole), but Source Han Sans HW fonts are not listed

As the following screenshot, it is still possible to use Source Han Sans HW fonts by hacking Konsole's config file, as a workaround.
![_002](https://cloud.githubusercontent.com/assets/1192163/10745511/5cfde4d0-7c7d-11e5-95f6-b3e09c647851.png)

**Comment by kenlunde** [comment]
My guess is that the monospaced flags in the font are triggering this, and those flags should be set _only_ if all of the glyphs in the font share the same width. In the case of Source Han Sans, this is not true. Whether one hacks a configuration file is at each user's discretion.
