### ISSUE TITLE
Add the character 𧒽(U+274BD)

### ISSUE THREAD

**Issue by fei0316** [adobe-fonts/source-han-sans#133]
The character, although not being in the any of the supported standards, should be added. This character is used as a station name of Guangzhou Metro (𧒽岗站), as a park name near that station (𧒽岗公园) and also as a name of a type seafood produced in that area. The character is supported by MingLiU_HKSCS-ExtB font, the character was also successfully shown properly on OS X 10.10 Yosemite by default. This character was proposed to be added, but later removed from 通用规范汉字表. Any documents, banners, and websites with that character would usually be written as 「虫雷」or「礌」people also claimed to have problems finding that station on the mobile phone app. Maps showing that station or the park have to use other words to replace the unsupported word. As the goal of this font is to maximize compatibility and minimize "tofu", adding this character can really benefit a lot of people, considering the fact that all Android devices running Android 5.0 or above are using this font. Thank you.

Reference:
https://zh.wikipedia.org/wiki/%F0%A7%92%BD%E5%B4%97%E7%AB%99
https://zh.wikipedia.org/wiki/%E9%BB%83%E6%B2%99%E8%9C%86
http://news.sina.com.cn/o/2014-07-24/142430572774.shtml
http://baike.baidu.com/view/4731307.htm
https://www.google.com/maps/place/%E7%A4%8C%E5%B2%97/@23.0442069,113.1465266,16z/data=!4m5!1m2!2m1!1z6Jmr6Zu35bKX5YWs5ZyS!3m1!1s0x0000000000000000:0x84aea54ce06ea2e9

**Comment by kenlunde** [comment]
Please add these details to Issue #115.

**Comment by fei0316** [comment]
I'm sorry but I'm new to GitHub, am I supposed to comment on Issue #115 the same thing that I've posted on this issue? Thank you very much.

**Comment by kenlunde** [comment]
Yes, please.

**Comment by kenlunde** [comment]
Consolidated with Issue #115.

**Comment by kenlunde** [comment]
Consolidated with Issue #180.

**Comment by ytx21cn** [comment]
Finally see that in Source Han Sans.
Hope to see it in Source Han Serif as well.

**Comment by kenlunde** [comment]
@ytx21cn I keep code point parity in each update, at least for major ones, such as Version 2.000, meaning that the _Source Han Serif_ Version 2.000 update will include a CN glyph for U+274BD 𧒽.
