### ISSUE TITLE
Question: Put font releases in GitHub Releases binary assets instead of in repository?

### ISSUE THREAD

**Issue by Vdragon** [adobe-fonts/source-han-sans#134]
Hi, although I'm not really bothered by this issue I'm still curious about it, so I post it here.

[GitHub support uploading binary assets lesser than 2GiB per file for each releases](https://help.github.com/articles/distributing-large-binaries/) under the [Releases page](https://github.com/adobe-fonts/source-han-sans/releases), I wonder why Source Han Sans not utilizing it instead of putting releases in a Git branch under version control?

**Comment by miguelsousa** [comment]
@Vdragon explain the benefit of doing the way you suggest as opposed to the way it's done now.

**Comment by Vdragon** [comment]
@miguelsousa Despite of "binary files is not Git-friendly", I'm not really know much benefit of that either

**Comment by miguelsousa** [comment]
Then we'll leave it the way it is. Thanks for asking.
