### ISSUE TITLE
Font Awesome icons displayed wrongly in Mozilla Firefox(but not in Google Chrome)

### ISSUE THREAD

**Issue by Vdragon** [adobe-fonts/source-han-sans#135]
I found that Font Awesome icons on <http://data.gov.tw> is wrongly rendered on Firefox but not in Chrome:
![_007](https://cloud.githubusercontent.com/assets/1192163/12112100/48c1814a-b3d5-11e5-99fb-a4299371298a.png)

According to the [Font Awesome's page of one of the icons](http://fortawesome.github.io/Font-Awesome/icon/file-text-o/) and [some Google research](http://www.unicodemap.org/details/0xF0F6/index.html) it seems that those characters are in 0xE000 - 0xF8FF : Private Use.

I'm not really sure this issue is Source Han Sans related but since I set Source Han Sans as fontconfig's 1st priority font(and `sans-serif` in Mozilla Firefox, `sans` in Google Chrome) I thought that Source Han Sans might be the cause.

Any ideas?

### Producing environment
* Ubuntu 14.04LTS
* Mozilla Firefox 43.0
* Google Chrome 47.0.2526.106
* Source Han Sans 1.004

**Comment by Vdragon** [comment]
Closing because it seems that Source Han Sans TW font isn't the source of the glyphs.

**Comment by Vdragon** [comment]
The font that produces this issue in my case is UnDotum and I figure it out by using [GNOME gucharmap](https://wiki.gnome.org/action/show/Apps/Gucharmap?action=show&redirect=Gucharmap).

Credits: [Find out fallback font used by fontconfig for a certain character | repolinux](https://repolinux.wordpress.com/2013/03/10/find-out-fallback-font-used-by-fontconfig-for-a-certain-character/)

**Comment by ShikiSuen** [comment]
The reason is that you use Firefox's built-in font settings to ignore website-customized fonts.
I recommend you to use Stylish instead and put the FontAwesome at the final place of your font fallback definition.

**Comment by Vdragon** [comment]
@ShikiSuen Hi I've already solve my problem alone, but thanks for your helping.
