### ISSUE TITLE
Require missing characters

### ISSUE THREAD

**Issue by KrasnayaPloshchad** [adobe-fonts/source-han-sans#136]
The Korean Wikisource has a page related to Hunmin Jeongeum (훈민정음, 訓民正音)
https://ko.wikisource.org/wiki/%ED%9B%88%EB%AF%BC%EC%A0%95%EC%9D%8C

In this page I found two characters 𪓟 and 𣖄 missing in Source Han Sans, these characters appearing in the section “Yongjarye”(用字例, 용자례), please giving support for them.

**Comment by kenlunde** [comment]
I am consolidating this with Issue #115.

Note that Hunmin Jeongeum is outside the scope of the glyph set, meaning that they are not considered to be required, but because this is only two characters, they will be considered for the Version 2.000 glyph set. Thank you for the suggestion.

**Comment by kenlunde** [comment]
Consolidated with Issue #180.

**Comment by acuteaccent** [comment]
I disagree with this suggestion.

Source Han Sans should prioritize the characters that are used today, not the ones that were used in archaic documents. In other words, characters need to be selected based on the contemporary/modern usage, not on the historical/archaic usage.

There are thousands of characters that appear in archaic documents but are never (or very rarely) used today. Adding glyphs for such archaic (or very rarely used) characters to Source Han Sans will not be that efficient. Keep in mind that the glyph set of Source Han Sans is almost full; unused glyphs need to be used wisely.

**Comment by acuteaccent** [comment]
And with regard to this particular issue, there is no guarantee that the Wikisource document has no typos or errors. There might be typos or errors.

Even books that are published today sometimes have typos or errors, even though they are carefully proofread and reviewed before they get published.

It is very unlikely that the Wikisource document was carefully proofread and reviewed.

**Comment by KrasnayaPloshchad** [comment]
OK, fixed in 2.000, thank you very much!
