### ISSUE TITLE
Add Chữ nôm characters

### ISSUE THREAD

**Issue by KrasnayaPloshchad** [adobe-fonts/source-han-sans#137]
Is it possible to adding more characters for [Chữ nôm](https://en.wikipedia.org/wiki/Ch%E1%BB%AF_n%C3%B4m)? Some of them are encoded in CJK Extended-B, -C, -D and -E blocks.

**Comment by kenlunde** [comment]
We have long-term plans to eventually support Extension B and beyond, and the thousands of VN (Chữ nôm) glyphs will come along for the ride. I am consolidating this with Issue #115.
