### ISSUE TITLE
Strange design of 奀

### ISSUE THREAD

**Issue by hfhchan** [adobe-fonts/source-han-sans#138]
![quickmemo _2016-01-13-21-27-44](https://cloud.githubusercontent.com/assets/8191296/12295558/c53f185a-ba3c-11e5-9975-58954eea1945.png)
This looks pretty strange to me. The third stroke of 不 could be shortened and the top of 大moved upwards.  This is a rather frequently seen informal tone character for "little"

**Comment by kenlunde** [comment]
Thank you. This belongs in Issue #99, so I am closing this and consolidating accordingly.

**Comment by kenlunde** [comment]
Consolidated with Issue #178.
