### ISSUE TITLE
Several comjoined Hangul Jamos breaking within vertical layout

### ISSUE THREAD

**Issue by KrasnayaPloshchad** [adobe-fonts/source-han-sans#140]
I found several comjoined Hangul Jamos breaking within vertical layout when using Source Han Sans.

First, I copied texts from [Hunminjeongeum Eonhae](https://ko.wikisource.org/wiki/%ED%9B%88%EB%AF%BC%EC%A0%95%EC%9D%8C%EC%96%B8%ED%95%B4) for test
![testcase 1](http://chuantu.biz/t2/24/1453474294x-1566679570.png)
Second, I copied texts again from [Hunminjeongeum](https://ko.wikisource.org/wiki/%ED%9B%88%EB%AF%BC%EC%A0%95%EC%9D%8C)
![testcase 2](http://chuantu.biz/t2/24/1453474314x-1566679570.png)

In these cases some of Hangul Jamos don’t comjoined as 1 syllable when put them in vertical texts

**Comment by kenlunde** [comment]
This issue is known, and already covered in Issue #34, which is being tracked.
