### ISSUE TITLE
indicate how big the releases are?

### ISSUE THREAD

**Issue by Pomax** [adobe-fonts/source-han-sans#142]
Right now github does not seem to indicate the size of the download, nor does it seem to send a content-length indicator so the browser is downloading "blind" - it has no idea whether the release is 10MB, 100MB, or even 1000MB, so it might be worth noting the (even rought) size of the releases in the README.md when a new release is tagged.

(The zipped 1.004 release is 1.6GB. It's nice to know that before hitting the download button, even with uncapped high speed internet =)

**Comment by kenlunde** [comment]
Yes, the download is huge, 1.6GB for the master branch, and about 1.2GB for the release branch. I think that it is less of an issue for the release branch, because very few people need to download the entire set of fonts. Thank you for this suggestion.

**Comment by kenlunde** [comment]
Please check the landing page of this project, specifically the newly added second paragraph.

**Comment by Pomax** [comment]
Nice, although I'd probably recommend moving it down so that it's in the "downlad the fonts" section. Also note that following the link in the README.md for "download latest release" takes you to https://github.com/adobe-fonts/source-han-sans/releases/tag/1.004R, and then downloading that zip file yields a 1.6GB file (1.666.256.727 bytes according to my file system) rather than 1.2GB.

**Comment by kenlunde** [comment]
I had the sizes of the branches transposed, but it should now be correct, along with the recommended placement of the note.

**Comment by Pomax** [comment]
super, thanks!

**Comment by miguelsousa** [comment]
I've added big :warning: **WARNING** comments to the release notes, near the download links.

**Comment by kenlunde** [comment]
👍
