### ISSUE TITLE
Need for a new CJK release branch with proportional kana as default

### ISSUE THREAD

**Issue by ShikiSuen** [adobe-fonts/source-han-sans#143]
Probably I shouldn't talk such technical issue on Twitter. It occurred to me that I contacted both Ken and Masataka for guides on self-compiling Source Han Sans with default proportional kana.

However, as I am still less-skilled on internal manipulation towards customized SHS compilation, I finally decided to ask for possibility on whether such a new release of SHS will be officially available when SHS 2.x comes out in this year.

P.S.: I personally figured out a thing: For horizontal reading, the Kana design of SHS looks better when proportional Kana is enabled. The reason why I claim it's "better" is that proportional kana could allow people keeps a comparatively even constant reading rhythm. However, I currently could only enable this feature through iWorks. (I hadn't tried Indesign yet, and I know it supports typography features better than iWorks.)

![image](https://cloud.githubusercontent.com/assets/3164826/13194034/7348ac56-d741-11e5-86ba-448a5b5ba0dc.png)
![image](https://cloud.githubusercontent.com/assets/3164826/13194202/b22b2d78-d745-11e5-9080-a9fc4953cb08.png)

**Comment by ShikiSuen** [comment]
(As a routine procedure, I close this thread at first unless Ken wants it opened.)

**Comment by kenlunde** [comment]
Proportional kana (and punctuation) is perhaps ideal for UI use. In order to implement this, there are effectively three steps or processes that must be executed: 1) proportional horizontal kana is effected by using the corresponding 'palt' GPOS feature records to change the LSB (left side bearing) and advance of the glyphs at the charstring level, and the AFDKO *rotateFont* tool is ideal for this purpose; 2) proportional vertical kana is effected by using the corresponding 'vpal' GPOS records to add 'vmtx' overrides to the "features" files; and 3) to remove said 'palt' and 'vpal' GPOS records from the "features" files.

Adding fonts that have proportional kana by default means doubling the number of OTFs, at least the Japanese ones, because the CFFs cannot be shared with the ones that have full-width kana by default.

I don't mind having this issue open, so I will reopen it.

**Comment by ShikiSuen** [comment]
One more idea:

Since Source Han Sans is used for UI fonts of Google Android, what about make a CJK-Common-Dingbat subset with only common parts among Language-Specific Releases? This means that such release doesn't have kanji glyphs but proportional Kana, Hangul, and other common dingbats. Such release could be placed as a fallback font prior to regional specific Kanji subsets.

**Comment by kenlunde** [comment]
The better—and longer term—solution is for OSes and applications to invoke the 'palt' or 'vpal' GPOS feature when proportional versions of otherwise full-width glyphs are needed, which mainly covers kana and punctuation.

Related to this, text layout engines should be invoking the 'halt' and 'vhal' GPOS features to get half-width versions of most East Asian punctuation (many text layout engines are mechanically transforming the full-width glyphs into half-width versions by trimming half of the glyph, but this fails miserably for some characters whose glyphs become centered for use in Taiwan and Hong Kong SAR, such as U+3001, U+3002, U+FF)C, and U+FF0E). Using the GPOS features gives the intended result.

**Comment by ShikiSuen** [comment]
For those symbols you concerned (e.g. U+3001, U+3002, U+FF)C, and U+FF0E), I prefer to leave them as half-width in TW and HK branches. Actually I hadn't thought anything about proportional dingbats.

**Comment by kenlunde** [comment]
If you check the palt/vpal metrics for the glyphs of those characters, they resolve to half-width, not proportional.

**Comment by ShikiSuen** [comment]
@kenlunde Yes and the circle period symbol will look weird if placed just after a kana from p family (ぱぴぷぺぽパピプペポ):

![image](https://cloud.githubusercontent.com/assets/3164826/13293160/c64f8814-dadb-11e5-9b78-5eda978c4d8b.png)

**Comment by ShikiSuen** [comment]
I am wondering those dingbats need to be tweaked a little to deal with the case when proportional kana is enabled.

**Comment by kenlunde** [comment]
Intelligent text layout starts out using half-width punctuation, and adds space when necessary. For the examples that you showed, the text layout engine is at fault. The font is supplying the appropriate glyphs and metrics.

**Comment by ShikiSuen** [comment]
@kenlunde Got it. Thanks for explanation regarding the real antecedent.

**Comment by ShikiSuen** [comment]
@kenlunde I am wondering why pkna is not introduced in Source Han Sans.

**Comment by kenlunde** [comment]
@ShikiSuen: There are two reasons why the '[pkna](https://www.microsoft.com/typography/otspec/features_pt.htm#pkna)' feature is not included in Source Han Sans: 1) although a registered feature, it is not supported, though the case is somewhat different in CSS whereby arbitrary features can be specified (but it is still up to each implementation as to whether a feature is supported); and 2) more importantly, it is a GSUB, not GPOS feature, and requires separate glyphs, with different CIDs, with default proportional metrics to be present in the font.

Supporting proportional kana via GPOS features does not consume additional CIDs, and as you are aware, [every CID is sacred](https://www.youtube.com/watch?v=fUspLVStPbk) in Source Han Sans.

**Comment by ShikiSuen** [comment]
@kenlunde Here comes another question:
Does PWID (i.e. font-variant-east-asian: proportional-width) need separate glyphs?

**Comment by kenlunde** [comment]
@ShikiSuen [Yes](https://www.microsoft.com/typography/otspec/features_pt.htm#pwid).

**Comment by ShikiSuen** [comment]
@kenlunde Then it looks like Safari still must solve this bug since 'palt' is the only way to enable SHS proportional kana on the web: https://bugs.webkit.org/show_bug.cgi?id=155299 .

P.S.: From Apple engineers' point of view, end users are supposed to use font-variant-east-asian instead of font-feature to enable east-asian font features. Looks like something needs to be done with the current HTML5 standard to allow people to enable 'palt' through font-variant or font-variant-east-asian settings.

**Comment by kenlunde** [comment]
@ShikiSuen Note that Safari still does not support the 'locl' GSUB feature (Chrome and Firefox do), which I consider to be far more critical than supporting the 'palt' GPOS feature, though that does not suggest that it is not important.

**Comment by frankrolf** [comment]
Safari supports `locl` – see here: https://charakterziffer.github.io/otfeat/index.html
(Tested with Safari Version 9.1 (11601.5.17.1))

**Comment by kenlunde** [comment]
@frankrolf: I am using the same version of Safari, but 'locl' is not working on [this page](https://blogs.adobe.com/CCJKType/2015/06/typekit-dynamic-kits.html). Any ideas? Perhaps it works in Safari for all languages except for CJK.

**Comment by kenlunde** [comment]
The boxed [paragraph](https://cloud.githubusercontent.com/assets/3988788/14090672/88005500-f4f0-11e5-944d-d923c865e9c0.jpg) suggests that Safari doesn't support 'locl', or at least not as well as Chrome or Firefox.

**Comment by frankrolf** [comment]
Sorry. I assumed the latest Safari update put it at par with other browsers in terms of OT feature support. I remembered that page/the `locl` feature from an exercise I ran with students last week. However, your observation is correct. Here is a 3rd test:
https://www.typotheque.com/articles/opentype_features_in_web_browsers_-_tests

**Comment by ShikiSuen** [comment]
@kenlunde The Safari and WebKit browser since OS X 10.11.4 supports 'palt' with bugs introduced.

**Comment by ShikiSuen** [comment]
@kenlunde I just checked Webkit r198471 (nightly build) and have found it supports font-variant-east-asian: proportional-width (i.e.: pwid) in this demonstration page: https://bug-155319-attachments.webkit.org/attachment.cgi?id=273625 (it shows three examples, the first two examples are using  font-variant-east-asian: proportional-width in different methods and the final example is using "palt".)

**Comment by ShikiSuen** [comment]
This is what we could see through Webkit Nightly Build r198471:
![textbackgroundlengthnotreflected](https://cloud.githubusercontent.com/assets/3164826/14094946/354d9732-f518-11e5-97af-63c39b14ae01.png)

**Comment by kenlunde** [comment]
@ShikiSuen: Nice!

**Comment by ShikiSuen** [comment]
@kenlunde It will be nicer if they solve current two bugs introduced (as what I addressed above).
