### ISSUE TITLE
[Question] Failed to find Source Han Sans Language-Specific Releases on CTAN and TeX Live Utility.

### ISSUE THREAD

**Issue by ShikiSuen** [adobe-fonts/source-han-sans#144]
This is not an issue with SHS, but just a request about official release for adobe fonts on CTAN network to let people download them through TeX Live Utility.

**Comment by kenlunde** [comment]
When you have a chance, please explain how this is a Source Han Sans issue?

**Comment by ShikiSuen** [comment]
@kenlunde Uh... I said in the 1st post that this is not an issue with SHS. I have just realized in recent days that SHS is not listed on CTAN network, and I am wondering why Adobe doesn't release SHS to CTAN.

I thought it's something that Adobe could do, but I don't think I have other official channels to let Adobe know. Please let me know if you think it's more appropriate to email you these matters instead of posting them on GitHub issue tracker here.

**Comment by kenlunde** [comment]
Adobe has no official channels with CTAN. If the folks who manage CTAN want to include Source Han Sans, they are free to do so.

**Comment by ShikiSuen** [comment]
@kenlunde Thanks. Then this issue shall be closed in such case.
