### ISSUE TITLE
some duplicate files in release file

### ISSUE THREAD

**Issue by fyears** [adobe-fonts/source-han-sans#145]
As of 20160227, I download the 1.004 release file https://github.com/adobe-fonts/source-han-sans/archive/1.004R.zip.

After decompressing the zip file, I found that in `OTF/` subfolder, there are some `*.zip` files, **as well as** their decompressed version:

```
OTF
│   SourceHanSansHWJ.zip
│   SourceHanSansHWK.zip
│   SourceHanSansHWSC.zip
│   SourceHanSansHWTC.zip
│   SourceHanSansJ.zip
│   SourceHanSansK.zip
│   SourceHanSansSC.zip
│   SourceHanSansTC.zip
│
├───Japanese
│       SourceHanSans-Bold.otf
│       SourceHanSans-ExtraLight.otf
│       SourceHanSans-Heavy.otf
│       SourceHanSans-Light.otf
│       SourceHanSans-Medium.otf
│       SourceHanSans-Normal.otf
│       SourceHanSans-Regular.otf
│
├───JapaneseHW
│       SourceHanSansHW-Bold.otf
│       SourceHanSansHW-Regular.otf
│
├───...
```

The same situation occurs in another subfolder `SubsetOTF/`.

I think it unnecessarily increases the downloaded file size.

**Comment by fyears** [comment]
OK. I think I know the reason.

Because GitHub creates the "release" by simply compressing the whole repo. And by the design of this repo, having duplicated files in the zip is unavoidable.

**Comment by kenlunde** [comment]
Your conclusion is correct.

**Comment by kenlunde** [comment]
See Issue #64.

**Comment by hfhchan** [comment]
I think the biggest confusion is the readme file on the master file links to github's entire repository zip.

Users might expect that those links would take them to the release branch's separate downloads.

**Comment by hfhchan** [comment]
* I think the biggest confusion is the readme file on the master repo links to github's entire repository zip.

**Comment by kenlunde** [comment]
@hfhchan: Please check the readme file in the master branch again.
