### ISSUE TITLE
Can I build region-specific half-width subset OTFs?

### ISSUE THREAD

**Issue by magiclen** [adobe-fonts/source-han-sans#147]
It seems there are only language-specific half-width OTFs, but no region-specific half-width subset OTFs.

I need half-width and smaller OTFs, how can I do?

**Comment by kenlunde** [comment]
Other than adding new entries to a FontMenuNameDB file and changing names in the appropriate cidfont.ps.* and cidfontinfo* files, you simply gather the sources for the region-specific subset OTFs for which you want half-width versions, then substitute the standard CMap resources with the half-width versions. The CMap resources map code points to CIDs, not to GIDs, which makes this possible.
