### ISSUE TITLE
Interpolating new weights?

### ISSUE THREAD

**Issue by davelab6** [adobe-fonts/source-han-sans#149]
Is it possible to interpolate a new/custom instance with the publicly available tools? 

I couldn't find the MM file...

**Comment by kenlunde** [comment]
This is a duplicate of #119. Too many processes have been applied to the master weights, ExtraLight and Heavy (equivalent to Thin and Black in Noto Sans CJK), making them no longer compatible in terms of interpolation.

**Comment by davelab6** [comment]
That makes sense :) Thanks!
