### ISSUE TITLE
Is there any chance to release TTF version ?

### ISSUE THREAD

**Issue by cwchien** [adobe-fonts/source-han-sans#15]
I know OTF has lot of advantages over TTF.

As a Java programmer, I have to admit that many Java Swing-based IDEs do not support OTF well, especially non-Latin characters.
Is there any chance to release TTF version like Source (Sans | Serif | Code) Pro  or we can compile them from source ?

Thanks.

**Comment by jameswilson** [comment]
Twitter user @akiratw has packaged Source Han Sans as TTF and made available for download (at your own risk) on mega.co.nz:  

http://akr.tw/2014/10/source-han-sans-ttf/

Quote from site (via google translate):

"Which contains Japanese, Korean, Simplified Chinese and Traditional Chinese in four languages ​​and seven kinds of word weight, a total of 28 TTF files"

It is a 257MB download.

https://mega.co.nz/#!nEZx0IRY!4DlWyiuadO9vreNu-uANg6tBxrl5jXuO40j9E83z3Oo

**Comment by be5invis** [comment]
simply:
```bash
otfccdump input.otf | otfcc-c2q | otfccbuild output.ttf # unhinted
```
You need a lot of memory, though

**Comment by cwchien** [comment]
@be5invis Thanks for the tips. I'd give it a try. :)

**Comment by be5invis** [comment]
@cwchien 
https://github.com/be5invis/source-han-sans-ttf/releases
(It is hinted either :smile:.)

**Comment by cwchien** [comment]
@be5invis
Thanks a lot for the hinted version.

otfcc really helps me a lot.
I have used it for compiling Source Han Sans / Serif TTF version and it works very well. :)
