### ISSUE TITLE
Offer separate downloads?

### ISSUE THREAD

**Issue by jjgod** [adobe-fonts/source-han-sans#151]
I wonder if the packaging process allows generating separate packages for each language or style, so that if I'm only interested in CN Regular for example I don't have to download the entire 1.5GB package.

It probably makes no difference for those of you on 50Gbps network, but I'm on a really slow network here downloading 10KB/s so every bit matters.

**Comment by jakwings** [comment]
You can try what I said in another issue:
https://github.com/adobe-fonts/source-han-sans/issues/64#issuecomment-60190541

**Comment by jjgod** [comment]
Thanks, that works. Closing.

**Comment by kenlunde** [comment]
👍 + 🍻
