### ISSUE TITLE
fwid substitution of ASCII tilde 

### ISSUE THREAD

**Issue by dohyunkim** [adobe-fonts/source-han-sans#153]
I have found this issue with Noto Sans CJK KR, but Source Han Sans K seems to have the same problem.

While testing vertical typesetting, I encountered an unexpected glyph substitution regarding ASCII tilde.  It turned out that the lookup table of OpenType feature `fwid` is the culprit. So I have tested `fwid` substitution of all ASCII characters ranging from U+0021 to U+007E and confirmed that only tilde character is affected:

![noto_fwid](https://cloud.githubusercontent.com/assets/4328134/15314535/74cc9686-1c4d-11e6-84a0-e3a6f83d9322.png)

I don't think this is an expected outcome of `fwid` feature.

**Comment by kenlunde** [comment]
Although this is a known issue and has been recorded, thank you for reporting it. We found the issue internally, and it will be fixed in the next update.

**Comment by ShikiSuen** [comment]
Wondering whether this issue had been addressed in Noto Sans CJK 1.005 (shipped with Android N).

**Comment by kenlunde** [comment]
At Google's request, I built Noto Sans CJK Version 1.005 in early March of this year, which was limited to only the Regular weight, and specifically addressed only [Noto CJK Issue 23](https://github.com/googlei18n/noto-cjk/issues/23), [Noto CJK Issue 24](https://github.com/googlei18n/noto-cjk/issues/24), [Noto CJK Issue 25](https://github.com/googlei18n/noto-cjk/issues/25), and [Noto CJK Issue 32](https://github.com/googlei18n/noto-cjk/issues/32). Source Han Sans was not updated. These and many other updates are targeted for Version 2.000, for both Noto Sans CJK and Source Han Sans.

**Comment by kenlunde** [comment]
This was fixed in [Source Han Serif](https://github.com/adobe-fonts/source-han-serif/) Version 1.000, and will be reflected in the Version 2.000 update.

**Comment by kenlunde** [comment]
Consolidated with Issue #181.
