### ISSUE TITLE
Unable to install Super OTC on Windows 10 anniversary update

### ISSUE THREAD

**Issue by Fanolian** [adobe-fonts/source-han-sans#156]
I cannot install SourceHanSans.ttc on Windows 10 anniversary update, but the 7 weight-based OTCs can be installed.

My system:
Windows 10 pro v1607 build 14393.10 64bit English edition
All existing Source Han Sans fonts are uninstalled and computer is restarted prior installing the .ttc.

Windows does not provide an informative error message:
![superotc](https://cloud.githubusercontent.com/assets/771216/17373405/9ebf4540-59da-11e6-8c6b-56270db5c33d.PNG)

I got the file from:
https://github.com/adobe-fonts/source-han-sans/tree/release and
https://github.com/adobe-fonts/source-han-sans/releases/latest

P.S. [Noto Sans CJK](https://www.google.com/get/noto/help/cjk/) has the same issue, as expected.

**Comment by Fanolian** [comment]
Just notice that the [blog post](https://blogs.adobe.com/CCJKType/2016/08/august-2-2016.html) had updated and acknowledged this issue already.

**Comment by kenlunde** [comment]
Right. I am working with Microsoft—at Microsoft's HQ—to determine what aspect of the Super OTC is triggering this. The first step was to manually install it, which also failed. I then provided a version that includes only 16 fonts (four weights and four languages), which also failed.

**Comment by dabeniao** [comment]
Just want to report that this issue is resolved in the Windows 10 Creators Update.
The Super OTC can now be installed on my Windows 10 pro v1703 build 15063.0 64bit Traditional Chinese edition.

**Comment by kenlunde** [comment]
@dabeniao: Yes, I am aware of this, and thank you for adding this note. My understanding is that Windows 10 Creators Update will be officially released sometime next month.

**Comment by Fanolian** [comment]
I can also verify that Super OTC for Source Hans San and Source Han Serif can be installed on Windows 10 Creators Update without any errors. (Given that official Windows 10 CU ISO has been released earlier today.)
