### ISSUE TITLE
SourceHanSansSC-Light can not be extrated 

### ISSUE THREAD

**Issue by metalmac** [adobe-fonts/source-han-sans#157]
Hello Guys,

When open the progit-zh.936.pdf file, it poped out the issue below,

The English translation for the Chinese is _Can not extract embeded font "DISOTQ+SourceHanSansSC-Light some of the characters might not be displayed normally or printed_

PS: I already downloaded the _SourceHanSansSC-Light_ font and installed sucessfully,do I need to install the DISOTQ font to resolve this issue?

![adobe_font_error 2016-08-18_105726](https://cloud.githubusercontent.com/assets/1448776/17760542/216515c0-6533-11e6-9b89-f13eda00b610.jpg)

**Comment by kenlunde** [comment]
If the PDF was created on Windows using the "Print as Adobe PDF," then this is a known issue, and is being tracked as [Noto CJK Issue 36](https://github.com/googlei18n/noto-cjk/issues/36). It may also be related to [Noto CJK Issue 38](https://github.com/googlei18n/noto-cjk/issues/38). I am guessing that it is related to the latter issue. The SourceHanSansSC-Light font has more than 32K glyphs.
