### ISSUE TITLE
Wrong char shape for “袱”

### ISSUE THREAD

**Issue by kangshiyin** [adobe-fonts/source-han-sans#158]
I just found the shape of the char `袱` is wrong in both TC and SC. The left part should be a `衤`, not a `礻`.
![baofu](https://cloud.githubusercontent.com/assets/3216836/18225600/c373a096-7228-11e6-91fd-cdb9cb2823e4.png)

**Comment by kenlunde** [comment]
This glyph error for U+88B1 (uni88B1-CN) was already reported by @tamcy on 2016-04-10 in Issue #99, where such issues should be reported.
