### ISSUE TITLE
Source Han Sans not available in Illustrator CC

### ISSUE THREAD

**Issue by JimmyLeonardson** [adobe-fonts/source-han-sans#159]
The font is not available when looking through my collection of fonts.
It comes up in the font list and works as expected in Photoshop, Sketch and Indesign.

Noto CJK JP which is the other version of this font works and is available in Illustrator but it should be the same font so what could be the issue? I have cleared font cache and installed on a fresh computer and got the same results. 

I'm using Illustrator CC (2015.2.1 - 19.2.1 release) and using the font Source Han Sans JP and Source Han Sans J on a Mac (OSX El Capitan).

**Comment by zerng07** [comment]
I believe it should be a bug of Illustrator CC though, not of Source Han Sans.

**Comment by JimmyLeonardson** [comment]
True but why do Noto Sans work but SHS not?

**Comment by kenlunde** [comment]
@JimmyLeonardson: This is definitely an Illustrator CC issue, and I will ask our QE to reproduce the issue. But, we need more information. In particular, please list the exact Source Han Sans fonts you have installed, by file name. I am asking this, because there is really no reason to install both the language-specific (Source Han Sans J) and region-specific subset (Source Han Sans JP) OTFs. I personally have a strong preference for the language-specific OTFS, because they are Pan-CJK fonts. The region-specific subset OTFs have reduced functionality in that they do not support the other languages.

**Comment by JimmyLeonardson** [comment]
I used Source Han Sans JP (Subset), uninstalled, then installed Source Han Sans J (Language specific). 
I did the same thing with Noto Sans but it works on both JP and CJK JP.

**Comment by kenlunde** [comment]
Have you tried to install the Super OTC?

**Comment by JimmyLeonardson** [comment]
Yes, and same results. 

The Noto Sans CJK JP and JP version works in Illustrator but we would like to keep using Source Han Sans if possible.

**Comment by kenlunde** [comment]
Thank you. I will ask our QE to investigate.

**Comment by kenlunde** [comment]
BTW, I am using Illustrator CC 2015.3.1 20.1.0 on macOS Version 10.12 (Sierra), and have the Super OTC installed. Source Han Sans J (源ノ角ゴシック) and all seven of its weights appear in the font menus. The two screenshots below show this in two areas of the UI:

![character-panel](https://cloud.githubusercontent.com/assets/3988788/19193645/14081d80-8c68-11e6-8c2c-14e99785766f.jpg)
![menu-bar](https://cloud.githubusercontent.com/assets/3988788/19193651/1a3ce884-8c68-11e6-8e04-38b0193ba9a7.jpg)

**Comment by JimmyLeonardson** [comment]
@kenlunde i see!! So the font has the Japanese name in Illustrator? Where is that specified in the font, in the metadata? It might be that it was a miss from my part. I will look into it and get back to you.

**Comment by kenlunde** [comment]
Please keep me posted. The localized font names are specified in the 'name' table, and are also mentioned in the official ReadMe file. The Noto Sans CJK fonts do not include localized font names (Google's decision).

**Comment by miguelsousa** [comment]
@JimmyLeonardson you can switch to the non-localized names by going to Illustrator's preferences and switching on the option **Show Font Names in English**.
<img width="902" alt="illustrator" src="https://cloud.githubusercontent.com/assets/2119742/19198439/0f062988-8c74-11e6-916e-acaf4f843019.png">

**Comment by JimmyLeonardson** [comment]
@kenlunde Thanks this was my fault of not knowing about the localised font name. Thanks for the help! I will close the issue.

@miguelsousa Thanks I noticed! :)
