### ISSUE TITLE
Power Point 2016 unable to display Source han sans.

### ISSUE THREAD

**Issue by dominant08** [adobe-fonts/source-han-sans#160]
Hi, I recently upgraded to Microsoft Office 2016, while source han sans worked well with my previous version of MS Office 2010, I come across with some problem with MS Office 2016.

Firstly, MS Office is unable to display Source han sans, it became a group of Tofu. 
![1](https://cloud.githubusercontent.com/assets/22819797/19358543/dc6baf36-91a8-11e6-9820-8db74d445a76.jpg)

However, if I export the slides as .jpg files, the fonts miraculously appear.
![3](https://cloud.githubusercontent.com/assets/22819797/19358577/f7bffddc-91a8-11e6-825e-3b3ef94c193d.jpg)

I've tried some other software such as LibreOffice, it turned out that it works well with them. 
![14680685_10155505053014896_7577619132466306929_n](https://cloud.githubusercontent.com/assets/22819797/19358646/30cdf19c-91a9-11e6-8a5c-ada60450d3af.jpg)

I'm running on windows 7, and I've tried nearly all version of Source han sans available, including subset-region OTF, OTF, Noto San CJK. Some of my friends who are using MS Office 2016 for Mac reported that the font works well on their system, so it seems like MS Office 2016 for Windows is the only software that doesn't work. 

Let me summarize a little bit. 
1. The font worked well with MS Office 2010 (on the same computer)
2. MS office 2016 is unable to display the font while editing, however the font did appear when I exported the slide into .jpg files.
3. The font worked well with other software such as LibreOffice.

I'm a slide-maker who rely pretty much on the Source han sans font. Please let me know if there is any solution to this problem, and I wanna say thank you in advance, to anyone participates in the discussion, thank you :)   

![2](https://cloud.githubusercontent.com/assets/22819797/19358810/f39c6d7a-91a9-11e6-8dee-9d6b236d4c04.jpg)

**Comment by kenlunde** [comment]
I have asked our QE to reproduce this issue.

**Comment by kenlunde** [comment]
To follow up on this issue in a meaningful way, our QE was unable to reproduce this issue (using Windows 7 Japanese, Office 365 ProPlus, v16.0.6965.2092, and SourceHanSansTW-Bold.otf, v1.004):

![shstw_office2016_win7j](https://cloud.githubusercontent.com/assets/3988788/19395114/d6c8cff8-91f0-11e6-92b3-33990d89176c.jpg)

The following are some questions/suggestions that our QE conveyed to me, which may help to get the fonts working for you:

- Are you experiencing this issue only when using PowerPoint? What about the other MS Office 2016 apps, such as Word and Excel?
- Does the issue occur when editing an existing file, when creating a new file, or both?
- Which keyboard are you using (see _Control Panel>Text Services and Input Languages>General_)?
- What language is specified in your preferences (see _Office Preferences>Languages>Input language_)?
- Is PowerPoint's [Hide Text](https://support.office.com/en-gb/article/Hide-text-c17ecade-4406-4715-a193-ea5dadd20415) feature turned on?

**Comment by dominant08** [comment]
Hi Dr. Ken Lunde,

Thanks for the response from you and your team, upon seeing the question you provided, I checked with my system and here's the update. 



-Among the MS Office spectrum, only MS Excel displays the font properly. Word, Publisher and Power Point are unable to display the font.

![5](https://cloud.githubusercontent.com/assets/22819797/19396516/11b4a7a6-9276-11e6-895e-1b9c5d8d9851.png)

However, word behave a little different from Power point. Instead of displaying a Tofu, it kind of displays a "default font", we can confirm that the one displayed it is not Source Han Sans because it belong to Serif family. (given that Source Han Sans belong to sans serif family.)

![1](https://cloud.githubusercontent.com/assets/22819797/19396563/4d6277c4-9276-11e6-8e52-84b419de783e.jpg)


- The issue occur on both occasion, when creating a new file and editing an existing file.

- This is a screenshot of my language setting.

![2](https://cloud.githubusercontent.com/assets/22819797/19396606/799d06b0-9276-11e6-942b-4fbb9bd50424.png)

- This is a screenshot of my Language Preference in Power Point.
![3](https://cloud.githubusercontent.com/assets/22819797/19396631/9c01d2f8-9276-11e6-9546-9f3e0a7f5c58.png)


- The "Hide Text" feature is not turned on.


- I'm currently using Microsoft Power Point 2016 MSO (16.0.4266.1001) 64-bit.


Thank you so much on the follow-up!

**Comment by kenlunde** [comment]
Thank you for these additional details.

**Comment by kenlunde** [comment]
Our QE still cannot reproduce this issue, and noticed that your screenshots show that you're using the English version of MS Word. While it may not make any difference, have you tried the Traditional Chinese version? Also, please try setting the Windows system locale Traditional Chinese Taiwan (_Control Panel>Region and language>Administrative>System Locale_). Also, you might try toggling the default input language (currently set to English according to your screenshots).

**Comment by be5invis** [comment]
cc. @milizhang

**Comment by jimmymasaru** [comment]
Have you tried to use a Traditional Chinese IME to input in Word?
Or have you tried to apply the font again after inputing the characters using a Simplified Chinese IME?
Microsoft Office is sensitive about this.

**Comment by milizhang** [comment]
I also could not get a repro on my devbox. This might be a Windows 7 only issue, or something related particularly to 4266.1001.

**Comment by be5invis** [comment]
@dominant08 What's your font version, OTC or OTF, and your hash? How are they installed? Clean or override? What's in your `Windows/Fonts` folder?
