### ISSUE TITLE
Support OpenType Font Variation

### ISSUE THREAD

**Issue by KrasnayaPloshchad** [adobe-fonts/source-han-sans#161]
OpenType specification introduced font variation in 1.8, as _[Type is Beautiful](http://www.typeisbeautiful.com/2016/09/10968/zh-hant/)_, this technology has following advantages for CJK typefaces: it’s easy to adjust the gray scale, proportion, alignments with Western scripts, easy to implement multiple font weight and style within single font file, save unwhispered expenses for meticulous and global hinting and so on. If Source Han Sans adapt this technology, it would get better quality visual appearences.

**Comment by kenlunde** [comment]
Of course, I am aware of this. This is likely to happen, but not until after the Version 2.000 update. I will close this issue mainly because it is a logical progression of the family.

**Comment by KrasnayaPloshchad** [comment]
See: https://github.com/adobe-type-tools/afdko/issues/153
