### ISSUE TITLE
Adding more weights of SHS into Android systerm?

### ISSUE THREAD

**Issue by fatloong** [adobe-fonts/source-han-sans#164]
Google started to use Source Han Sans (Noto Sans CJK) as default font of Chinese, Korean and Japanese from Android 5.0. Although SHS has seven weights, Google only integrate one weight - Regular into Android system. Even in Android 7.0, it still contains one weight of SHS and not add other weights of SHS. May I know the reason?

Related code of /system/etc/fonts.xml from Android 7.0:

`    <family lang="zh-Hans">`
`        <font weight="400" style="normal" index="2">NotoSansCJK-Regular.ttc</font>`
`    </family>`
`    <family lang="zh-Hant">`
`        <font weight="400" style="normal" index="3">NotoSansCJK-Regular.ttc</font>`
`    </family>`
`    <family lang="ja">`
`        <font weight="400" style="normal" index="0">NotoSansCJK-Regular.ttc</font>`
`    </family>`
`    <family lang="ko">`
`        <font weight="400" style="normal" index="1">NotoSansCJK-Regular.ttc</font>`

Some people rooted their device and added other weights of SHS result in different appearance. Following are some screen shots:

**Left:** Only Regular originally, **Right:** Adding Medium and Light
![0b612643f16332646cc41c5dec750d37_r](https://cloud.githubusercontent.com/assets/11400000/21470015/d1de9eb6-cab0-11e6-97ba-948489e7626f.png)

**Left:** Regular with fake Bold originally, **Right:** Adding Bold
(many strokes of fake Bold stick together and the edge of fake Bold character is blurry)
![2e39781e40e7b5f38f25b052d9fe16bc_r](https://cloud.githubusercontent.com/assets/11400000/21470021/097b436a-cab1-11e6-8061-69c286fa02ee.png)

Picture from https://www.zhihu.com/question/25529554/answer/94207134

I am not sure how to report this to Google but I hope Google fully make use of seven weights of SHS, I know it is not a issue of SHS.

Thanks.

**Comment by showerying** [comment]
[https://code.google.com/p/android/issues/detail?id=188772&q=cjk&colspec=ID%20Status%20Priority%20Owner%20Summary%20Stars%20Reporter%20Opened](url)

**Comment by kenlunde** [comment]
While I completely understand this issue, it is completely outside the scope of this project, which simply provides fully-functional font resources and their sources, not a complete ecosystem that consumes these and other fonts. Many thanks to @showerying for referencing the appropriate Google issue.

Also, please be aware that the Regular weight will be style-linked to the Bold weight in Version 2.000, for apps that depend on such a configuration to apply Bold as a style.
