### ISSUE TITLE
The Writing of "家" Glyph in TW variant

### ISSUE THREAD

**Issue by zerng07** [adobe-fonts/source-han-sans#166]
![-source han sans](https://cloud.githubusercontent.com/assets/1706450/21985443/abbfb580-dc35-11e6-9e75-bba971589965.png)
There is an issue about "家" glyph with the 豕 part which is often mentioned on forum by Taiwanese user Ian Ho to criticize Source Han Sans not following the MOE standard in Taiwan . 
According to 國字標準字體明體母稿、楷體母稿、方體母稿 (which served as a "reference" - "提供給各界使用參考"), the lower right part of 豕 is more like ofㄑwhich strokes connecting at one point.
Is that a designer approach (designed as-is) or a bug?
Thanks.

**Comment by zerng07** [comment]
I found the design now is more like of 小篆, 大篆 and 楚系簡帛. 
豕 evolution from 中研院 http://chardb.iis.sinica.edu.tw/evolution.jsp?cid=22712
豕 from wikiwand http://www.wikiwand.com/ja/%E8%B1%95%E9%83%A8#/.E9.83.A8.E9.A6.96.E5.AD.97

That makes me feel that is not a bug, but a design approach to follow the origin to mimic the pig tail.
Anyway, still waiting for the official response though.

**Comment by kenlunde** [comment]
Thank you for raising this issue.

The official response is that 1) if one follows the Taiwan MOE standard too closely, the end result is simply a clone of the font that was used to prepare the Taiwan MOE standard; 2) for a Pan-CJK typeface design, the sharing of glyphs across regions and languages is important for both space-saving and design-consistency purpose; and 3) this difference was deemed not significant enough to include separate CN and TW versions of the character.

**Comment by acuteaccent** [comment]
https://github.com/adobe-fonts/source-han-sans/issues/126
Then, why does 簡 have two different glyphs? The glyph difference of 𥫗 is subtle.

**Comment by kenlunde** [comment]
This is a typeface design, and such differences, subtle or otherwise, are the result of designer discretion. Source Han Sans is no different than other typeface designs in this regard. Source Han Sans simply gets more exposure than most typeface designs due to its price tag.

**Comment by Vdragon** [comment]
I wondered if you've maintained a list of not-compliant glyphs?
