### ISSUE TITLE
Bopomofo tone marks displaying incorrectly in horizontal text?

### ISSUE THREAD

**Issue by practik** [adobe-fonts/source-han-sans#167]
When I set Source Han Sans TW as the default font for "Traditional Chinese (Taiwan)" in Firefox, it looks to me like the tone marks are too low and too big. I'm attaching a screenshot from http://uncyclopedia.tw/wiki/%E3%84%93%E3%84%A8%CB%8B_%E3%84%A7%E3%84%A3_%E3%84%A8%E3%84%A3%CB%8A as an example.

![bopomofoff](https://cloud.githubusercontent.com/assets/12074235/22407168/855531e8-e61e-11e6-9689-0118d250082b.jpg)

The tone marks appear the same way when I paste the text into a text editor and set the font to Source Han Sans TW.

**Comment by kenlunde** [comment]
Thank you for the feedback. I welcome comments from others about this issue.

**Comment by kenlunde** [comment]
Assuming that the equivalent glyphs in [Source Han Serif](https://github.com/adobe-fonts/source-han-serif/) are okay, we will make adjustments to U+02C7 ˇ, U+02CA ˊ, and U+02CB ˋ as part of the Version 2.000 update.

**Comment by practik** [comment]
I just checked Source Han Serif, and those three glyphs look much better in it than the current sans versions. Thank you!

**Comment by kenlunde** [comment]
@practik: Thank you for checking the corresponding glyphs in _Source Han Serif_.

**Comment by kenlunde** [comment]
Consolidated with Issue #178.
