### ISSUE TITLE
Vertical baseline alignment in Word 2016

### ISSUE THREAD

**Issue by mashabow** [adobe-fonts/source-han-sans#168]
In Word 2016, Latin glyphs don't align properly in vertical text:

![word2016](https://cloud.githubusercontent.com/assets/6268183/22819893/b5fa2edc-efb7-11e6-8021-5f16962bcd3f.png)

- SourceHanSans-Bold.otf
- Word 2016 v16.0.7571.7095
- Windows 10 Pro

**Comment by kenlunde** [comment]
Please double-check your font or text options, because we are unable to reproduce this issue.

Does this issue occur consistently? Please try creating a fresh file, being sure to select Source Han Sans. Also try to create a file by selecting another (Japanese) font, then change the selected font to Source Han Sans.

**Comment by mashabow** [comment]
Hmm, on my Windows machine I can reproduce with a fresh file. Furthermore, I found that this problem also occurs with KozGoPr6N:

![shs-kozpr6n](https://cloud.githubusercontent.com/assets/6268183/22913517/945c4d74-f2ae-11e6-88da-6f87290aded5.png)

This is the docx file: [shs_kozpr6n.docx](https://github.com/adobe-fonts/source-han-sans/files/773055/shs_kozpr6n.docx)

**Comment by mashabow** [comment]
As I privately mailed to @kenlunde, now I suspect it has something to do with [fsSelection](https://www.microsoft.com/typography/otspec/os2.htm#fss) bit 7, and it seems a very MS Word-specific problem.

**Comment by be5invis** [comment]
@milizhang ← WORD GUY

**Comment by acuteaccent** [comment]
FYI, I don't have problems.
![aiuabckanji-word2016](https://cloud.githubusercontent.com/assets/8185770/24976086/f2f219fe-1f7c-11e7-8668-60708685e0cf.png)
- SourceHanSans-Bold.otf
- Word 2016 (English), version 16.0.7870.2031
- Windows 10 Home (English)
