### ISSUE TITLE
Unused Scripts and CJK Ideograms

### ISSUE THREAD

**Issue by TsavyPrince** [adobe-fonts/source-han-sans#170]
You probably already know this and are planning to fix this but some Unicode scripts are missing as well as CJK ideograms and perhaps other symbols.

**Comment by kenlunde** [comment]
More details would be helpful, because what you wrote is very ambiguous.

**Comment by TsavyPrince** [comment]
What I mean is that some CJK symbols are missing and some scripts for languages are missing. You may not be concerned with the languages which is fine since I don't need them as much as theother CJK symbols.

**Comment by kenlunde** [comment]
Which specific CJK symbols are missing? Also, which scripts? I need something more than vague terms. If the missing CJK symbols were added in Unicode Version 8.0 or above, they'd be on the roadmap to be supported.

**Comment by kenlunde** [comment]
I am closing this issue until actionable details are provided.
