### ISSUE TITLE
Slash or Dot should be added to the zero glyph in Source Han Sans HW, as a font for programming

### ISSUE THREAD

**Issue by tats-u** [adobe-fonts/source-han-sans#175]
I would like to use Source Han Sans HW as the font of text editors and terminals because I feel ASCII glyphs in Source Han Code JP too wide.  Zero glyphs in programming fonts like Souce Code Pro, Inconsolata, and Consolas are with central dots or slashes because it is necessary to distinguish zeros from large Os, but that of Source Han Sans HW looks like the large O.  Therefore, I would like a slash or a dot (I prefer slash, like Inconsolata) to be added to the zero of Souce Han Sans HW.

**Comment by kenlunde** [comment]
The half-width Western glyphs, which are limited to ASCII and an extremely small number of additional characters, are included for reasons other than the fonts' use as a programming font, so I have marked this as _as designed_, _do it yourself_ (DIY), and _invalid_, and will now close it.
