### ISSUE TITLE
Wrong substitutes regarding to "~"

### ISSUE THREAD

**Issue by jimmymasaru** [adobe-fonts/source-han-sans#176]
I found these substitutes regarding "~" are wrong in all feature files.
`substitute \59085 by \95;`
`substitute \95 by \ 59085;`
`substitute \63133 by \59085;`
`substitute \59085 by \63133;`

**Comment by jimmymasaru** [comment]
This one can be closed since it has been reported in #153

**Comment by kenlunde** [comment]
Right. You should have also noticed that this was fixed in _Source Han Serif_ Version 1.000.
