### ISSUE TITLE
Consolidation of Glyph Correction Suggestions

### ISSUE THREAD

**Issue by kenlunde** [adobe-fonts/source-han-sans#178]
The following table shows the glyph corrections that are planned for the Version 2.000 update, and does not yet include those for supporting HKSCS-2016 (though a small number of HK glyph corrections are specified so that they are not overlooked), and unless otherwise noted, the corrections are consolidated from Issue #99 or were from my own notes:

**Character** | **Glyph Name** | **Description**
--- | --- | ---
U+1134 | _uni1134.ljmo02_ |
U+116F | _uni116F.vjmo02_ |
U+1171 | _uni1171.vjmo02_ |
U+1176 | _uni1176.vjmo02_ |
U+1178 | _uni1178.vjmo02_ |
U+1179 | _uni1179.vjmo02_ |
U+117A | _uni117A.vjmo02_ |
U+117C | _uni117C.vjmo02_ |
U+117D | _uni117D.vjmo02_ |
U+1189 | _uni1189.vjmo02_ |
U+118E | _uni118E.vjmo02_ |
U+1194 | _uni1194.vjmo02_ |
U+1197 | _uni1197.vjmo02_ |
U+119A | _uni119A.vjmo02_ |
U+119C | _uni119C.vjmo02_ |
U+11A3 | _uni11A3.vjmo02_ |
U+11C1 | _uni11C1.tjmo04_ | Issue #90
U+11C2 | _uni11C2.tjmo01_ |
U+11D6 | _uni11D6.tjmo04_ | Issue #90
U+11EC | _uni11EC_ |
U+11ED | _uni11ED_ |
U+11F5 | _uni11F5.tjmo04_ |
U+20DD ⃝ | _uni20DD_ (AJ16 CID+16328) | Make the glyph zero-width and shift 1000 units to the left; [Noto CJK Issue 72](https://github.com/googlei18n/noto-cjk/issues/72)
U+20DE  ⃞ | _uni20DE_ (AJ16 CID+11035) | Make the glyph zero-width and shift 1000 units to the left; Related to [Noto CJK Issue 72](https://github.com/googlei18n/noto-cjk/issues/72)
U+2673 ♳ | _uni2673_ | Make generic in weight by using Heavy master for ExtraLight master
U+2674 ♴ | _uni2674_ | Make generic in weight by using Heavy master for ExtraLight master
U+2675 ♵ | _uni2675_ | Make generic in weight by using Heavy master for ExtraLight master
U+2676 ♶ | _uni2676_ | Make generic in weight by using Heavy master for ExtraLight master
U+2677 ♷ | _uni2677_ | Make generic in weight by using Heavy master for ExtraLight master
U+2678 ♸ | _uni2678_ | Make generic in weight by using Heavy master for ExtraLight master
U+2679 ♹ | _uni2679_ | Make generic in weight by using Heavy master for ExtraLight master
U+3099 ゙  | _uni3099_ (AJ16 CID+16326) | Make the glyph zero-width and shift 1000 units to the left
U+309A ゚  | _uni309A_ (AJ16 CID+16327) | Make the glyph zero-width and shift 1000 units to the left
U+33C2 ㏂ | _uni33C2_ | Add periods; [Noto CJK Issue 32](https://github.com/googlei18n/noto-cjk/issues/32)
U+33CB ㏋ | _uni33CB_ | Adjust to be a single (connected) glyph
U+33D8 ㏘ | _uni33D8_ | Add periods; [Noto CJK Issue 32](https://github.com/googlei18n/noto-cjk/issues/32)
U+3665 㙥 | _uni3665-CN_ | Change the middle component of the right side from Radical 30 to Radical 28
U+3B9D 㮝 | _uni3B9D-CN_ | The right side component should be Radical 163
U+3D78 㵸 | _uni3D78-CN_ | Remove the extra Radical 30 component from the middle of the glyph
U+4389 䎉 | _uni4389-CN_ | The short diagonal stroke in the right component should be horizontal
U+454E 䕎 | _uni454E-CN_ | The lower-left component should look like Radical 72
U+4578 䕸 | _uni4578-CN_ & _uni4578-HK_ | The primary vertical stroke of the lower-left component has inconsistent thickness in the lighter intermediate weights
U+465B 䙛 | _uni465B-CN_ | Change the middle component of the right side from Radical 30 to Radical 28
U+4723 䜣 | _uni4723-CN_ | The LEs for the lower-left corner of the ⻈ component don't join correctly in the Heavy master; Issue #120
U+4724 䜤 | _uni4724-CN_ | The LEs for the lower-left corner of the ⻈ component don't join correctly in the Heavy master; Issue #120
U+4727 䜧 | _uni4727-CN_ | The LEs for the lower-left corner of the ⻈ component don't join correctly in the Heavy master; Issue #120
U+47E1 䟡 | _uni47E1-CN_ | The short diagonal stroke should not connect, and should be lower
U+497B 䥻 | _uni497B-CN_ | The LEs for the lower-left corner of the 钅 component don't join correctly in the Heavy master; Issue #120
U+497F 䥿 | _uni497F-CN_ | The LEs for the lower-left corner of the 钅 component don't join correctly in the Heavy master; Issue #120
U+49B4 䦴 | _uni49B4-CN_ | Transpose the widths of the bottom two horizontal strokes
U+4B6A 䭪 | _uni4B6A-CN_ | The LEs for the lower-left corner of the 饣 component don't join correctly in the Heavy master; Issue #120
U+4B96 䮖 | _uni4B96-CN_ | Fix the connection error
U+4E35 丵 | _uni4E35-CN_ | The bottom two horizontal strokes are not symmetrical (the bottom one should remain longer than the top one)
U+4FB4 侴 | _uni4FB4-CN_ | Adjust the lower-left horizontal stroke to be diagonal
U+4FB9 侹 | _uni4FB9-CN_ | The middle horizontal stroke of the right-side component should be longer/wider
U+5002 倂 | _uni5002-JP_ (AJ16 CID+20299) | The diagonal stroke in the middle of the glyph should be horizontal
U+506E 偮 | _uni506E-TW_ | The right component is too wide
U+5329 匩 | _uni5329-CN_ | The inner components are incorrectly connected
U+5357 南 | _uni5357-CN_ | Adjust the top vertical stroke to be completely vertical and centered
U+555A 啚 | _uni555A-CN_ | Adjust the short vertical stroke to be perfectly vertical, not slightly diagonal
U+5747 均 | _uni5747-TW_ | The left and right components are too far apart
U+57D3 埓 | _uni57D3-JP_ (AJ16 CID+4497) | Adjust the top-right component
U+5829 堩 | _uni5829-CN_ | The right-side component is incorrect
U+5940 奀 | _uni5940-JP_ | Adjust the proportions of the top and bottom components; Issue #138
U+5B4D 孍 | _uni5B4D-CN_ | Fix the left component to be Radical 38
U+5D9F 嶟 | _uni5D9F-TW_ | The inner horizontal stroke of the upper-right component should not touch the vertical strokes
U+5DD5 巕 | _uni5DD5-TW_ | The lower-right component should be Radical 38, not Radical 39 (see U+21FD2 𡿒); Issue #169
U+5EF3 廳 | _uni5EF3-TW_ | The lower diagonal stroke of the Radical 128 component should be horizontal
U+5EF4 廴 | _uni5EF4-CN_ | Adjust the top to be perfectly flat, not diagonal, on the right side
U+5F73 彳 | _uni5F73-CN_ | Adjust the glyph by making it slightly wider and centered
U+6012 怒 | _uni6012-TW_ | Fix the second stroke of the upper-right component by making it curve outward
U+613F 愿 | _uni613F-TW_ | The Radical 27 enclosure should not extend downward beyond the top enclosed component
U+61CC 懌 | _uni61CC-CN_ | Adjust the bottom horizontal stroke of the right side so that it is wider than the stroke above it
U+61F2 懲 | _uni61F2-CN_ | The upper-middle part of the glyph is missing a horizontal stroke
U+61F2 懲 | _uni61F2-TW_ | The last stroke of the upper-right component should curve outward
U+6424 搤 | _uni6424-JP_ (AJ16 CID+19408) | Adjust the top corner so that it doesn't have a roof
U+64FB 擻 | _uni64FB-TW_ | The third stroke of the Radical 38 component should be horizontal, not diagonal; [Source Han Serif Issue 36](https://github.com/adobe-fonts/source-han-serif/issues/36#issuecomment-304496928)
U+6578 數 | _uni6578-TW_ | The third stroke of the Radical 38 component should be horizontal, not diagonal; [Source Han Serif Issue 36](https://github.com/adobe-fonts/source-han-serif/issues/36#issuecomment-304496928)
U+6975 極 | _uni6975-CN_ & _uni6975-TW_ | The Radical 30 component should have a "foot" only on its left side
U+6A5C 橜 | _uni6A5C-CN_ | Fix the 12th stroke to curve outward
U+6B5D 歝 | _uni6B5D-CN_ | Adjust the bottom horizontal stroke of the left side so that it is wider than the stroke above it
U+6BA9 殩 | _uni6BA9-CN_ | Fix the upper-left component of the right side
U+6C11 民 | _uni6C11-CN_ | Shift the glyph slightly to the left to better balance it within the em-box
U+6E09 渉 | _uni6E09-CN_ | Adjust the bottom vertical stroke to not touch the curved stroke below
U+70E2 烢 | _uni70E2-TW_ | The middle diagonal stroke should be horizontal
U+716A 煪 | _uni716A-TW_ | The inner horizontal stroke of the right component should not touch the vertical strokes
U+71C7 燇 | _uni71C7-TW_ | The inner horizontal stroke of the upper-right component should not touch the vertical strokes
U+72C5 狅 | _uni72C5-TW_ | The middle horizontal stroke of the right component should be the narrowest
U+7436 琶 | _uni7436-CN_ | The top components are not symmetric
U+745F 瑟 | _uni745F-CN_ | The top components are not symmetric 
U+7464 瑤 | _uni7464-JP_ (AJ16 CID+7477) | Adjust the upper-right component so that the dots don't connect
U+7662 癢 | _uni7662-JP_ (AJ16 CID+5775) | Adjust the final stroke so that it curves outward
U+7809 砉 | _uni7809-TW_ | The top and bottom components should not connect
U+7A3D 稽 | _uni7A3D-TW_ | The middle component of the right side should use a horizontal stroke
U+7B80 简 | _uni7B80-CN_ | Remove the "foot" from the Radical 72 component, and make the lower-right hook shorter; Issue #93
U+7C54 籔 | _uni7C54-TW_ | The third stroke of the Radical 38 component should be horizontal, not diagonal; [Source Han Serif Issue 36](https://github.com/adobe-fonts/source-han-serif/issues/36#issuecomment-304496928)
U+7F5A 罚 | _uni7F5A-CN_ | The LEs for the lower-left corner of the ⻈ component don't join correctly in the Heavy master; Issue #120
U+7F6A 罪 | _uni7F6A-CN_ | Adjust the horizontal strokes, especially the bottom two ones, to be symmetric
U+7FA1 羡 | _uni7FA1-CN_ | Disconnect the first and second strokes of the lower-right component from its third and fourth strokes
U+8028 耨 | _uni8028-TW_ | The upper-right component should not extend downward beyond the Radical 41 component
U+807D 聽 | _uni807D-TW_ | The lower diagonal stroke of the Radical 128 component should be horizontal
U+8084 肄 | _uni8084-TW_ | The upper-left component is incorrect
U+81AC 膬 | _uni81AC-TW_ | The lower-left Radical 82 component is incorrect
U+82AE 芮 | _uni82AE-TW_ | The bottom component is too close to the top radical/component
U+82CC 苌 | _uni82CC-CN_ | The lower-left corner has an LE connection issue only in the Heavy master; Issue #120
U+8328 茨 | _uni8328-CN_ | Disconnect the first and second strokes of the lower-right component from its third and fourth strokes
U+8585 薅 | _uni8585-TW_ | The middle-right component should not extend downward beyond the Radical 41 component
U+85EA 藪 | _uni85EA-TW_ | The third stroke of the Radical 38 component should be horizontal, not diagonal; [Source Han Serif Issue 36](https://github.com/adobe-fonts/source-han-serif/issues/36#issuecomment-304496928)
U+864B 虋 | _uni864B-CN_ | The horizontal stroke in the middle component should touches at both ends
U+87FC 蟼 | _uni87FC-TW_ | The last stroke of the upper-right component should curve inward
U+884B 衋 | _uni884B-CN_ | The center of the glyph is missing a horizontal stroke
U+88B1 袱 | _uni88B1-CN_ | The left component is missing a stroke; [Noto CJK Issue 95](https://github.com/googlei18n/noto-cjk/issues/95)
U+896C 襬 | _uni896C-TW_ | The upper Radical 21 component should use a horizontal stroke, not a hook
U+897E 襾 | _uni897E-JP_ (AJ16 CID+6635) | Adjust to fill more of the em-box
U+8999 覙 | _uni8999-CN_ | The top and bottom of the left component should touch
U+8BA3 讣 | _uni8BA3-CN_ | The LEs for the upper-right corner of the ⻈ component don't join correctly in the Heavy master; Issue #120
U+8BAC 讬 | _uni8BAC-CN_ | The LEs for the lower-left corner of the ⻈ component don't join smoothly in both masters; Issue #120
U+8BAE 议 | _uni8BAE-CN_ | The LEs for the lower-left corner of the ⻈ component don't join correctly in the Heavy master; Issue #120
U+8BB6 讶 | _uni8BB6-CN_ | The LEs for the lower-left corner of the ⻈ component don't join correctly in the Heavy master; Issue #120
U+8BC0 诀 | _uni8BC0-CN_ | The LEs for the upper-right corner of the ⻈ component don't join correctly in both masters; Issue #120
U+8BCB 诋 | _uni8BCB-CN_ | The LEs for the lower-left corner of the ⻈ component don't join correctly in the Heavy master; Issue #120
U+8BD1 译 | _uni8BD1-CN_ | The LEs for the lower-left and upper-right corners of the ⻈ component don't join correctly in the Heavy master; Issue #120
U+8BDE 诞 | _uni8BDE-CN_ | The LEs for the lower-left corner of the ⻈ component don't join correctly in the Heavy master; Issue #120
U+8BE8 诨 | _uni8BE8-CN_ | The LEs for the upper-right corner of the ⻈ component don't join correctly in both masters; Issue #120
U+8BEB 诫 | _uni8BEB-CN_ | The LEs for the lower-left corner of the ⻈ component don't join correctly in the Heavy master; Issue #120
U+8BF6 诶 | _uni8BF6-CN_ | The LEs for the upper-right corner of the ⻈ component don't join correctly in the Heavy master; Issue #120
U+8BF9 诹 | _uni8BF9-CN_ | The LEs for the upper-right corner of the ⻈ component don't join correctly in the Heavy master; Issue #120
U+8C06 谆 | _uni8C06-CN_ | An LE is protruding through another LE at the bottom-right of the ⻈ component in the Heavy master; Issue #120
U+8C07 谇 | _uni8C07-CN_ | The LEs for the upper-right corner of the ⻈ component don't join correctly in the Heavy master; Issue #120
U+8C09 谉 | _uni8C09-CN_ | The LEs for the upper-right corner of the ⻈ component don't join correctly in the Heavy master; Issue #120
U+8C0B 谋 | _uni8C0B-CN_ | The LEs for the upper-right corner of the ⻈ component don't join correctly in the Heavy master; Issue #120
U+8C13 谓 | _uni8C13-CN_ | The LEs for the lower-left corner of the ⻈ component don't join correctly in the Heavy master; Issue #120
U+8C15 谕 | _uni8C15-CN_ | The LEs for the lower-left corner of the ⻈ component don't join correctly in the Heavy master, and the LEs for the upper-right corner of the ⻈ component don't join correctly in both masters; Issue #120
U+8C1C 谜 | _uni8C1C-CN_ | The LEs for the upper-right corner of the ⻈ component don't join correctly in the Heavy master; Issue #120
U+8C25 谥 | _uni8C25-CN_ | The LEs for the lower-left corner of the ⻈ component don't join correctly in the Heavy master; Issue #120
U+8C28 谨 | _uni8C28-CN_ | The LEs for the lower-left corner of the ⻈ component don't join correctly in the Heavy master; Issue #120
U+8C30 谰 | _uni8C30-CN_ | The LEs for the upper-right corner of the ⻈ component don't join correctly in the Heavy master; Issue #120
U+8C32 谲 | _uni8C32-CN_ | The LEs for the upper-right corner of the ⻈ component don't join correctly in the Heavy master; Issue #120
U+8C3B 谻 | _uni8C3B-TW_ | The upper-right component is the wrong style
U+8F27 輧 | _uni8F27-JP_ (AJ16 CID+19874) | The diagonal stroke in the middle of the glyph should be horizontal
U+8FD0 运 | _uni8FD0-CN_ | The LEs for the lower-left corner of the 云 component don't join correctly in the Heavy master; Issue #196
U+8FF5 迵 | _uni8FF5-CN_ | Adjust the Radical 30 component to have a "foot" only on its left side
U+8FF5 迵 | _uni8FF5-TW_ | The Radical 30 component is missing a "foot" on the left side
U+900F 透 | _uni900F-TW_ | The fifth stroke of the upper-right component should curve outward
U+9020 造 | _uni9020-KR_ & _uni9020-TW_ | Remove the feet from the Radical 30 component of the enclosure
U+906F 遯 | _uni906F-TW_ | The middle component should be Radical 130, not Radical 74
U+907F 避 | _uni907F-CN_ | Adjust the Radical 30 component to have a "foot" only on its left side
U+908D 邍 | _uni908D-TW_ | The last stroke of the upper-right component should curve outward
U+9119 鄙 | _uni9119-CN_ | Adjust the vertical stroke on the left side to be perfectly vertical and centered
U+9173 酳 | _uni9173-TW_ | The inner horizontal stroke of Radical 164 should not touch the vertical strokes
U+9190 醐 | _uni9190-TW_ | The inner horizontal stroke of Radical 164 should not touch the vertical strokes
U+9191 醑 | _uni9191-TW_ | The inner horizontal stroke of Radical 164 should not touch the vertical strokes
U+919D 醝 | _uni919D-TW_ | The inner horizontal stroke of Radical 164 should not touch the vertical strokes
U+91A0 醠 | _uni91A0-TW_ | The inner horizontal stroke of Radical 164 should not touch the vertical strokes
U+91A1 醡 | _uni91A1-TW_ | The inner horizontal stroke of Radical 164 should not touch the vertical strokes
U+91AD 醭 | _uni91AD-TW_ | The inner horizontal stroke of Radical 164 should not touch the vertical strokes
U+945D 鑝 | _uni945D-TW_ | The last stroke of the upper-right component of the lower-right component should curve outward
U+9477 鑷 | _uni9477-TW_ | The second-to-last stroke of the lower-left Radical 128 component should not penetrate the last stroke
U+94A1 钡 | _uni94A1-CN_ | The LEs for the lower-left corner of the 钅 component don't join correctly in the Heavy master; Issue #120
U+94AE 钮 | _uni94AE-CN_ | The LEs for the lower-left corner of the 钅 component don't join correctly in the Heavy master; Issue #120
U+94AF 钯 | _uni94AF-CN_ | The LEs for the lower-left corner of the 钅 component don't join correctly in the Heavy master; Issue #120
U+94B5 钵 | _uni94B5-CN_ | The LEs for the lower-left corner of the 钅 component don't join correctly in the Heavy master; Issue #120
U+94B8 钸 | _uni94B8-CN_ | The LEs for the lower-left corner of the 钅 component don't join correctly in the Heavy master; Issue #120
U+94C2 铂 | _uni94C2-CN_ | The LEs for the lower-left corner of the 钅 component don't join correctly in the Heavy master; Issue #120
U+94C4 铄 | _uni94C4-CN_ | The LEs for the lower-left corner of the 钅 component don't join correctly in the Heavy master; Issue #120
U+94C6 铆 | _uni94C6-CN_ | The LEs for the lower-left corner of the 钅 component don't join correctly in the Heavy master; Issue #120
U+94CB 铋 | _uni94CB-CN_ | The LEs for the lower-left corner of the 钅 component don't join correctly in the Heavy master; Issue #120
U+94D1 铑 | _uni94D1-CN_ | The LEs for the lower-left corner of the 钅 component don't join correctly in the Heavy master; Issue #120
U+94D3 铓 | _uni94D3-CN_ | The LEs for the lower-left corner of the 钅 component don't join correctly in the Heavy master; Issue #120
U+94D6 铖 | _uni94D6-CN_ | The LEs for the lower-left corner of the 钅 component don't join correctly in the Heavy master; Issue #120
U+94D8 铘 | _uni94D8-CN_ | The LEs for the lower-left corner of the 钅 component don't join correctly in the Heavy master; Issue #120
U+94DA 铚 | _uni94DA-CN_ | The LEs for the lower-left corner of the 钅 component don't join correctly in the Heavy master; Issue #120
U+94F3 铳 | _uni94F3-CN_ | The LEs for the lower-left corner of the 钅 component don't join correctly in the Heavy master; Issue #120
U+94F9 铹 | _uni94F9-CN_ | The LEs for the lower-left corner of the 钅 component don't join correctly in the Heavy master; Issue #120
U+94FC 铼 | _uni94FC-CN_ | The LEs for the lower-left corner of the 钅 component don't join correctly in the Heavy master; Issue #120
U+94FE 链 | _uni94FE-CN_ | The LEs for the lower-left corner of the 钅 component don't join correctly in the Heavy master; Issue #120
U+9503 锃 | _uni9503-CN_ | The LEs for the lower-left corner of the 钅 component don't join correctly in the Heavy master; Issue #120
U+950D 锍 | _uni950D-CN_ | The LEs for the lower-left corner of the 钅 component don't join correctly in the Heavy master; Issue #120
U+9512 锒 | _uni9512-CN_ | The LEs for the lower-left corner of the 钅 component don't join correctly in the Heavy master; Issue #120
U+9513 锓 | _uni9513-CN_ | The LEs for the lower-left corner of the 钅 component don't join correctly in both masters; Issue #120
U+951C 锜 | _uni951C-CN_ | The LEs for the lower-left corner of the 钅 component don't join correctly in the Heavy master; Issue #120
U+9521 锡 | _uni9521-CN_ | The LEs for the lower-left corner of the 钅 component don't join correctly in both masters; Issue #120
U+9523 锣 | _uni9523-CN_ | The LEs for the lower-left corner of the 钅 component don't join correctly in the Heavy master; Issue #120
U+9524 锤 | _uni9524-CN_ | The LEs for the lower-left corner of the 钅 component don't join correctly in the Heavy master; Issue #120
U+9526 锦 | _uni9526-CN_ | The LEs for the lower-left corner of the 钅 component don't join correctly in the Heavy master; Issue #120
U+952E 键 | _uni952E-CN_ | The LEs for the lower-left corner of the 钅 component don't join correctly in the Heavy master; Issue #120
U+9530 锰 | _uni9530-CN_ | The LEs for the lower-left corner of the 钅 component don't join correctly in the Heavy master; Issue #120
U+9533 锳 | _uni9533-CN_ | The LEs for the lower-left corner of the 钅 component don't join correctly in the Heavy master; Issue #120
U+9534 锴 | _uni9534-CN_ | The LEs for the lower-left corner of the 钅 component don't join correctly in the Heavy master; Issue #120
U+9535 锵 | _uni9535-CN_ | The LEs for the lower-left corner of the 钅 component don't join correctly in the Heavy master; Issue #120
U+9540 镀 | _uni9540-CN_ | The LEs for the lower-left corner of the 钅 component don't join correctly in the Heavy master; Issue #120
U+9552 镒 | _uni9552-CN_ | The LEs for the lower-left corner of the 钅 component don't join correctly in the Heavy master; Issue #120
U+9553 镓 | _uni9553-CN_ | The LEs for the lower-left corner of the 钅 component don't join correctly in the Heavy master; Issue #120
U+9555 镕 | _uni9555-CN_ | The LEs for the lower-left corner of the 钅 component don't join correctly in the Heavy master; Issue #120
U+9564 镤 | _uni9564-CN_ | The LEs for the lower-left corner of the 钅 component don't join correctly in the Heavy master; Issue #120
U+9567 镧 | _uni9567-CN_ | The LEs for the lower-left corner of the 钅 component don't join correctly in the Heavy master; Issue #120
U+9569 镩 | _uni9569-CN_ | The LEs for the lower-left corner of the 钅 component don't join correctly in the Heavy master; Issue #120
U+9572 镲 | _uni9572-CN_ | The LEs for the lower-left corner of the 钅 component don't join correctly in the Heavy master; Issue #120
U+9574 镴 | _uni9574-CN_ | The LEs for the lower-left corner of the 钅 component don't join correctly in the Heavy master; Issue #120
U+95D9 闙 | _uni95D9-CN_ | Fix the arrangement of the three inner components
U+96E0 雠 | _uni96E0-CN_ | The LEs for the lower-left corner of the ⻈ component don't join correctly in the Heavy master
U+9746 靆 | _uni9746-JP_ (AJ16 CID+7141) | Adjust the last two strokes so that they do not touch
U+98BE 颾 | _uni98BE-TW_ | The second stroke of the Radical 29 component should curve outward
U+996A 饪 | _uni996A-CN_ | The LEs for the lower-left corner of the 饣 component don't join correctly in the Heavy master; Issue #120
U+9991 馑 | _uni9991-CN_ | The LEs for the lower-left corner of the 饣 component don't join correctly in the Heavy master; Issue #120
U+99A8 馨 | _uni99A8-TW_ | The second stroke of the Radical 29 component should curve inward
U+99B0 馰 | _uni99B0-CN_ | Fix the connection error
U+99C6 駆 | _uni99C6-JP_ (AJ16 CID+1766) | Fix the connection errors (masters are okay)
U+99CC 駌 | _uni99CC-CN_ & _uni99CC-TW_ | Fix the connection error
U+9A4E 驎 | _uni9A4E-KR_ | Connection error
U+9A5A 驚 | _uni9A5A-JP_ (AJ16 CID+1723) | Fix the connection errors
U+9CD6 鳖 | _uni9CD6-CN_ | Adjust the Y-axis position of the bottom horizontal stroke; the top of the vertical stroke on the left side has an interpolation issue in the intermediate weights
U+9D3F 鴿 | _uni9D3F-CN_ | Adjust the Radical 30 component to have a "foot" only on its left side
U+9DBE 鶾 | _uni9DBE-TW_ | Fix the LE connection error
U+9E82 麂 | _uni9E82-TW_ | The left side of the Radical 198 component should extend downward
U+9EA4 麤 | _uni9EA4-TW_ | The right Radical 21 component of the lower-left component should be the same as the left one
U+9EF9 黹 | _uni9EF9-CN_ | Adjust the last two diagonal strokes so that they touch the center vertical stroke
U+9F39 鼹 | _uni9F39-JP_ (Adobe-Japan1-6 CID+15376) | Fix the ExtraLight master such that the 鼠 and 女 components do not touch; Issue #194
U+A975 | _uniA975.ljmo02_ |
U+D7B1 | _uniD7B1.vjmo02_ |
U+D7B1 | _uniD7B1_ |
U+D7B5 | _uniD7B5.vjmo02_ |
U+D7BD | _uniD7BD.vjmo02_ |
U+D7C1 | _uniD7C1.vjmo01_ |
U+D7C1 | _uniD7C1.vjmo02_ |
U+D7C2 | _uniD7C2.vjmo02_ |
U+D7C6 | _uniD7C6.vjmo02_ |
U+D7F5 | _uniD7F5_ |
U+D7F6 | _uniD7F6_ |
U+D7FA | _uniD7FA.tjmo01_ |
U+1F250 🉐 | _u1F250-JP_ | The Heavy weight is missing two subpaths; Issue #163
U+20087 𠂇 | _u20087-CN_ | The glyph should fill more of the em-box
U+257E0 𥟠 | _u257E0-HK_ | Remove the extra stroke from the bottom-right component (current glyph is identical to U+7A2D 稭)
U+28D34 𨴴 | _u28D34-HK_ | Fixed the enclosed component (it should be U+5175 兵, not U+5171 共)
U+2CB6F 𬭯 | _u2CB6F-CN_ | The bottom portion of the vertical stroke of the middle component has different thicknesses in the lighter intermediate weights
U+2CB73 𬭳 | _2CB73-CN_ | The LEs for the lower-left corner of the 钅 component don't join correctly in the Heavy master; Issue #120

**Comment by Explorer09** [comment]
Some of the glyph issues that are reported in Source Han Serif issues page also affects Source Han Sans. Is the font team aware of them as well, or have they been all fixed already?

**Comment by kenlunde** [comment]
I am in the process of putting up a consolidated issue for redesign suggestions. Please check it after it is posted, which should be today.

**Comment by hfhchan** [comment]
![image](https://user-images.githubusercontent.com/8191296/27052686-0f0ba948-4fed-11e7-99b3-a1c926ba53b0.png)


There is an issue with U+8A7C: it seems that the vertical stroke has not been aligned properly with the horizontal stroke of the bottom left 口

**Comment by kenlunde** [comment]
Wrong typeface, but noted in the appropriate [issue](https://github.com/adobe-fonts/source-han-serif/issues/39).

**Comment by hfhchan** [comment]
🤦🏻‍♂️🤦🏻‍♂️🤦🏻‍♂️🤦🏻‍♂️
My bad

**Comment by tamcy** [comment]
The 女 component looks garbled in U+9F39 (JP & KR) (鼹) when rendered in a "small enough" scaling on Windows:
![9f39-word](https://user-images.githubusercontent.com/959433/36348050-4cd4810c-14a3-11e8-9b83-b67b998ad8d8.png)

This seems to be caused by an oddity in the merged contour of the glyph:
![9f39-ff](https://user-images.githubusercontent.com/959433/36348123-c9e631a4-14a3-11e8-88a7-609563ce7947.png)

**Comment by kenlunde** [comment]
See Issue #204 for Version 2.000 and beyond.
