### ISSUE TITLE
Questions relating to different standards on “归”

### ISSUE THREAD

**Issue by starkshaw** [adobe-fonts/source-han-sans#183]
### Prerequisites

* [x] If you are reporting an issue that affects glyphs for characters for a particular region or regions, did you verify that the characters are within the supported scope of the region or regions? This generally means GB 18030 or Tōngyòng Guīfàn Hànzìbiǎo (通用规范汉字表) for China, Big Five or CNS 11643 Planes 1 & 2 for Taiwan, HKSCS-2016 for Hong Kong (though support has been deferred until Version 2.000), the JIS standards for Japan, and KS X 1001 and KS X 1002 for Korea.
* [x] Did you thoroughly search the [open](https://github.com/adobe-fonts/source-han-sans/issues) and [closed](https://github.com/adobe-fonts/source-han-sans/issues?q=is%3Aissue+is%3Aclosed) issues to avoid reporting a duplicate issue?
* [x] Did you go through the [official font readme file](https://github.com/adobe-fonts/source-han-sans/raw/release/SourceHanSansReadMe.pdf) to better understand the scope of the project, to include the *Known Issues* section at the very end?

### Description

I happened to test KR standard in Noto Serif CJK, which is the closest subset to the old Kangxi standard, and I found the glyph “归” looked very different. I consulted the Unicode standard 9.0 [here](http://www.unicode.org/charts/PDF/U4E00.pdf) (A PDF document of glyphs started from U+4E00, 归 is at U+5F52) and I could not find any standard for JP and KR. And later found out same issue happened on Noto Sans CJK as well. What is the original intention of designing that glyph in such way in JP and KR? Considering it is a simplified Chinese glyph, I guess it is more appropriate to map it to the SC standard.

Also, considering this is happened on both Sans and Serif, should I opened an issue on the other side?

Here is a comparison chart below:
<img width="760" alt="screen shot 2017-06-12 at 22 04 37" src="https://user-images.githubusercontent.com/9618357/27055436-644448b0-4fbc-11e7-8d5d-ced240a3eea7.png">

**Comment by kenlunde** [comment]
The short answer is that the JP glyph for U+5F52 归, which is also referenced in the KR CMap resource, is already on the proverbial _chopping block_ for the Version 2.000 update for both _Source Han_ families, which renders this issue moot.

The long answer can be found [here](https://github.com/adobe-fonts/source-han-serif/issues/58#issuecomment-299451405).
