### ISSUE TITLE
Full-width question mark and exclamation mark in vertical writing are not aligning appropriately (Both Source Han Sans and Source Han Serif)

### ISSUE THREAD

**Issue by hitchhiker-42** [adobe-fonts/source-han-sans#185]
### Description
Full-width Question Mark (？, U+FF1F) and Full-width Exclamation Mark (！, U+FF01) does not align to center and is aligned to the right side when written in the vertical direction.

![screenshot 17](https://user-images.githubusercontent.com/31951923/32470614-516a7c4c-c39c-11e7-8ee3-4bdef4b243d1.png)

In this picture, every 3 sentences are written in (from right to left in the picture): 
Noto Serif CJK JP Regular / Batang
Noto Serif CJK JP Regular / Yu Mincho
Noto Sans CJK JP Regular / Malgun Gothic
Noto Sans CJK JP Regular / Yu Gothic

As seen in the picture, other fonts align their full-width punctuation marks to the center when written vertically, but it seems Source Han Sans and Source Han Serif doesn't, and it really hurts the overall structure of a vertical-written sentence.

Is this a intended design, or a bug?

**Comment by kenlunde** [comment]
This is either an MS Word bug whereby the Simplified Chinese (or Korean) versions of the punctuation are being invoked, or something in your settings is flagging the text as Simplified Chinese (or Korean). It's hard to tell from the other characters in your example, but if you were to add U+9AA8 骨 and U+9020 造, that would help to make the determination. In any case, it's not a font problem, but either an app bug or an app/OS language-settings issue.

Remember that the _Noto CJK_ (the ones with "CJK" in their name) and _Source Han_ fonts are Pan-CJK fonts, meaning that they include glyphs for the four supported regions, and are sensitive to language settings. Typical CJK fonts, such as the ones you included in your example, are single-region, and include only the glyphs for their supported region. If you were to use the region-specific subset fonts, you would likely not encounter this issue, and it's also a way to determine whether it is an app bug or an app/OS language-settings issue.
