### ISSUE TITLE
The “思源黑体” take more space than others

### ISSUE THREAD

**Issue by Leroy-X** [adobe-fonts/source-han-sans#186]
![00](https://user-images.githubusercontent.com/13515498/33194969-b8553288-d10e-11e7-93a2-395aa1d3d7fd.png)
![000](https://user-images.githubusercontent.com/13515498/33194972-bedc3886-d10e-11e7-98f9-c73d9fad08c7.png)

In the top image, you can find the "思源黑体" take more space under the line,  this is not easy for the align operation, especially in some image editor software, like Adobe illustrator, if possible, hope can fix this, it's really necessary, very thanks.

I don't know where to report, so post at here, sorry for my poor English.

**Comment by kenlunde** [comment]
The presence of "tall" glyphs, such as for U+3031 and U+3032, along with the vertical glyphs for U+2E3A and U+3E3B, result in a font bounding box that is unusually tall. We opened a bug against Illustrator a couple of years ago about this very issue, but they have been reluctant to fix it. The only way to fix this in the fonts is to remove such glyphs, which is a non-starter.

**Comment by Leroy-X** [comment]
Thank you for your answer :D
