### ISSUE TITLE
non-Regular styled fonts has Regular

### ISSUE THREAD

**Issue by tagoh** [adobe-fonts/source-han-sans#188]
How come all of fonts has Regular style in the naming table regardless of they are Regular or not? as most major font subsystem deals with separate fonts as same font if they has same family name but different styles, having Regular in non-Regular fonts may becomes a trouble. even though I guess it may be for the family name of Source Han Sans * + "style" like Source Han Sans JP Light. they could be used for "Source Han Sans JP" right?

So I'd suggest to remove Regular style from the naming table except for -Regular.otf.

**Comment by Explorer09** [comment]
Which software are you using that shows this problem? This might not be the bug on the font files, but on the software that cannot work with more than two weights (regular & bold).

**Comment by tagoh** [comment]
Not seeing any real problem at this moment but just a concern. for instance, SourceHanSansJP-Regular.otf  has "Source Han Sans JP" as a family name in the naming table and "Regular" as a style, also SourceHanSansJP-Light.otf has "Source Han Sans JP" as a family name as well and "Regular" as a style too.

Or am I misunderstanding the spec in the naming table?

**Comment by Explorer09** [comment]
Please give the link to the "spec" you are taking about.

**Comment by kenlunde** [comment]
This is according to the [spec](https://www.microsoft.com/en-us/Typography/OpenTypeSpecification.aspx). Please carefully read the second paragraph of the [_name.ID=2_](https://www.microsoft.com/typography/otspec/name.htm) description to confirm this, which states that for non-Regular fonts, the subfamily (aka weight) name is specified in the _name.ID=17_ string.
