### ISSUE TITLE
Will Source Han Sans future release use style links like Source Han Serif does for Regular and Bold?

### ISSUE THREAD

**Issue by zerng07** [adobe-fonts/source-han-sans#190]
It is known that Source Han Serif have the style link for Source Han Serif Regular and Source Source Serif Bold. I am wondering if Source Han Sans adopt this method as well in the future release?

Thanks.

**Comment by kenlunde** [comment]
Per the second prerequisite in the issue template, you didn't thoroughly search the open issues to find that the second bullet in Issue #181 already—and clearly—indicates this:

* Style-link the Regular weight to the Bold weight. Issue #103.
