### ISSUE TITLE
`meta` table, and the `dlng` and `slng` entries in it

### ISSUE THREAD

**Issue by be5invis** [adobe-fonts/source-han-sans#193]
Since Windows Insider build 17083, Windows contains a new UI to view and manage fonts. After some test, I found that the new UI uses the `meta` table to identify the design language and supported language of a particular font family.
SHS could add them to provide better identification information.

**Comment by hfhchan** [comment]
Interestingly, in the Microsoft [docs](https://www.microsoft.com/typography/otspec/meta.htm) for the `meta` OpenType table...

![image](https://user-images.githubusercontent.com/8191296/35582108-be65ff28-0628-11e8-8004-2fa3e85b6f39.png)

While Hong Kong (SAR) is a part of China, I think the 6th bullet point should read 
> “Hant-HK” denotes Traditional Chinese as used in Hong Kong SAR.

**Comment by kenlunde** [comment]
Consolidated with Issue #181.
