### ISSUE TITLE
U+9F39 (鼹): garbled outline

### ISSUE THREAD

**Issue by tamcy** [adobe-fonts/source-han-sans#194]
The 女 component looks garbled in U+9F39 (JP & KR) (鼹) when rendered in a "small enough" scaling on Windows:
![9f39-word](https://user-images.githubusercontent.com/959433/36348050-4cd4810c-14a3-11e8-9b83-b67b998ad8d8.png)

This seems to be caused by an oddity in the merged contour of the glyph:
![9f39-ff](https://user-images.githubusercontent.com/959433/36348123-c9e631a4-14a3-11e8-88a7-609563ce7947.png)

This only affects ~~Normal and~~ Regular weights.

**Comment by kenlunde** [comment]
Thank you for reporting this somewhat obscure issue. When I inspect the outlines, I can see why this is happening in the _Regular_ weight, but the _Normal_ weight looks okay. I feel that the best fix is to handle this at the design level, by disconnecting the second stroke of the 女 component from the 鼠 component to its left.

**Comment by tamcy** [comment]
You're right, *Normal* is fine. I suspected that the glyph is exposing a rare bug in the contour-merging code.

**Comment by kenlunde** [comment]
The overlapping-subpath removal process seems to be working fine, but it results in an outline that some rasterizers don't like.

In any case, I see no reason why the two components need to completely touch, especially at the lighter weights. The opposite is usually the case, meaning that components tend to overlap in the heavier weights, not the lighter ones. The fix that I will therefore suggest is to redesign the _ExtraLight_ master such that the components do not touch, like in its TW glyph.

**Comment by kenlunde** [comment]
Consolidated with Issue #178.
