### ISSUE TITLE
Where can I find Copyright notice for OFL license?

### ISSUE THREAD

**Issue by coldfog** [adobe-fonts/source-han-sans#195]
We are developing an online game and trying to use source-han-sans as our main font. We want to include the license file and copyright notice in our distribution package. However, the copyright notice is missing in license file. Where can I find the copyright notice?

**Comment by hfhchan** [comment]
Copyright 2014, 2015 Adobe Systems Incorporated (http://www.adobe.com/).

**Comment by hfhchan** [comment]
https://github.com/adobe-fonts/source-han-sans/blob/9e3f3cb9e5840e4c6aa71155572d26844176a4fb/Regular/cidfontinfo.CN#L15

**Comment by kenlunde** [comment]
An alternative method is to perform the equivalent of a "Get Info" for any of the _Source Han_ fonts to capture the copyright string.
<img width="477" alt="sourcehansans-regular" src="https://user-images.githubusercontent.com/3988788/37487780-d5294c80-284f-11e8-8d62-b69d30d71a82.png">
