### ISSUE TITLE
U+8FD0 (运): garbled outline on CN/SC variant

### ISSUE THREAD

**Issue by Pal3love** [adobe-fonts/source-han-sans#196]
The "云" component looks garbled in U+8FD0 (运), and it happens only on the CN/SC variant:

![u 8fd0](https://user-images.githubusercontent.com/8181271/37553681-06367ee8-298a-11e8-97d6-dcf049e9017d.png)

From my observation, affected weights are Normal, Regular, Medium, Bold and Heavy.

Please check the outline of corresponding weights. Thank you so much!

**Comment by kenlunde** [comment]
Thank you for for catching—and reporting—this, which is an issue on the Heavy master.

**Comment by kenlunde** [comment]
Consolidated with Issue #178.
