### ISSUE TITLE
Localized glyphs (locl) have unicode value U+FFFD (�)

### ISSUE THREAD

**Issue by svenper** [adobe-fonts/source-han-sans#200]
### Prerequisites

* [x] If you are reporting an issue that affects glyphs for characters for a particular region or regions, did you verify that the characters are within the supported scope of the region or regions? This generally means GB 18030 or Tōngyòng Guīfàn Hànzìbiǎo (通用规范汉字表) for China, Big Five or CNS 11643 Planes 1 & 2 for Taiwan, HKSCS-2016 for Hong Kong (though support has been deferred until Version 2.000), the JIS standards for Japan, and KS X 1001 and KS X 1002 for Korea.
* [x] Did you thoroughly search the [open](https://github.com/adobe-fonts/source-han-sans/issues) and [closed](https://github.com/adobe-fonts/source-han-sans/issues?q=is%3Aissue+is%3Aclosed) issues to avoid reporting a duplicate issue?
* [x] Did you go through the [official font readme file](https://github.com/adobe-fonts/source-han-sans/raw/release/SourceHanSansReadMe.pdf) to better understand the scope of the project, to include the *Known Issues* section at the very end?

### Description

If another language than the font file default is used, substituted glyphs have unicode value `U+FFFD` `�` `REPLACEMENT CHARACTER`. This makes searching and copying in a PDF file impossible for those glyphs.

The expected behavior would be that the substituted glyphs have the same unicode value as the default glyph they are replacing.

(This applies equally to Source Han *Serif*. Should I make an issue there as well with reference to this one?)

#### Copied output from [SourceHanExample.pdf](https://github.com/adobe-fonts/source-han-sans/files/2393994/SourceHanExample.pdf):

```none
SourceHanSerif-Regular.otf:
[JAN] 刃令毒骨縣誤船述煙贈雪及角條低詩函純賭難海喝練灰起英次能窗化
[KOR] �令�骨縣����贈��角條低詩函純賭難海喝練�起英�能窗�
[ZHS] ���⻣����煙���⻆������������英����
[ZHT] ������������角�����������������

SourceHanSerifK-Regular.otf:
[JAN] �令�骨縣�������角條低詩函純賭�����起英�能窗�
[KOR] 刃令毒骨縣誤船述煙贈雪及角條低詩函純賭難海喝練灰起英次能窗化
[ZHS] 刃��⻣��������⻆������������英���化
[ZHT] �����������及角�����������������

SourceHanSerifSC-Regular.otf:
[JAN] �令�⾻����煙���⾓������������英����
[KOR] 刃令�⾻�����贈��⾓������難海喝練��英���化
[ZHS] 刃令毒⻣縣誤船述煙贈雪及⻆條低詩函純賭難海喝練灰起英次能窗化
[ZHT] ���������贈��⾓���函純賭難海�練�������

SourceHanSerifTC-Regular.otf:
[JAN] �令����������角�����������������
[KOR] �令�������贈�及角������難海喝練�������
[ZHS] ���⻣�����贈��⻆���函純賭難海�練�������
[ZHT] 刃令毒骨縣誤船述煙贈雪及角條低詩函純賭難海喝練灰起英次能窗化

SourceHanSans-Regular.otf:
[JAN] 刃令毒骨縣誤船述煙贈雪及角條低詩函純賭難海喝練灰起英次能窗化
[KOR] �令�骨縣����贈��角條低詩函純賭難海喝練�起英�能窗�
[ZHS] ���⻣����煙���⻆������������英����
[ZHT] ������������角�����������������

SourceHanSansK-Regular.otf:
[JAN] �令�骨縣�������角條低詩函純賭�����起英�能窗�
[KOR] 刃令毒骨縣誤船述煙贈雪及角條低詩函純賭難海喝練灰起英次能窗化
[ZHS] ���⻣��������⻆������������英����
[ZHT] ������������角�����������������

SourceHanSansSC-Regular.otf:
[JAN] �令�⾻����煙���⾓������������英����
[KOR] �令�⾻�����贈��⾓������難海喝練��英����
[ZHS] 刃令毒⻣縣誤船述煙贈雪及⻆條低詩函純賭難海喝練灰起英次能窗化
[ZHT] ���������贈��⾓���函純賭難海�練�������

SourceHanSansTC-Regular.otf:
[JAN] �令����������角�����������������
[KOR] �令�������贈��角������難海喝練�������
[ZHS] ���⻣�����贈��⻆���函純賭難海�練�������
[ZHT] 刃令毒骨縣誤船述煙贈雪及角條低詩函純賭難海喝練灰起英次能窗化
```

#### L<sup>A</sup>T<sub>E</sub>X source of the example PDF:

```tex
\documentclass[11pt]{article}
\usepackage{fontspec}
\setmainfont{Latin Modern Mono}
\pagestyle{empty}
\setlength{\parindent}{0mm}

\newcommand*{\chars}{%
	刃令毒骨縣誤船述煙贈雪及角條低詩函純賭難海喝練灰起英次能窗化}

\newcommand*{\samplepars}[1]{{%
  \vspace{\normalbaselineskip}%
  #1:\par
  \fontspec{#1}[Script=CJK]%
  {\normalfont [JAN]} {\addfontfeature{Language=Japanese           }\chars}\par
  {\normalfont [KOR]} {\addfontfeature{Language=Korean             }\chars}\par
% {\normalfont [ZHH]} {\addfontfeature{Language=Chinese Hong Kong  }\chars}\par
  {\normalfont [ZHS]} {\addfontfeature{Language=Chinese Simplified }\chars}\par
  {\normalfont [ZHT]} {\addfontfeature{Language=Chinese Traditional}\chars}\par
}}

\begin{document}

\newpage
  \samplepars{SourceHanSerif-Regular.otf}%
  \samplepars{SourceHanSerifK-Regular.otf}%
% \samplepars{SourceHanSerifHK-Regular.otf}%
  \samplepars{SourceHanSerifSC-Regular.otf}%
  \samplepars{SourceHanSerifTC-Regular.otf}%

\newpage
  \samplepars{SourceHanSans-Regular.otf}%
  \samplepars{SourceHanSansK-Regular.otf}%
% \samplepars{SourceHanSansHK-Regular.otf}%
  \samplepars{SourceHanSansSC-Regular.otf}%
  \samplepars{SourceHanSansTC-Regular.otf}%

\end{document}
```

**Comment by kenlunde** [comment]
This is a PDF producer issue, not a font issue.

**Comment by svenper** [comment]
If it were the fault of the PDF producer, I think I would have the same problem with other fonts, which I don't, as indicated by [EBGaramondExample.pdf](https://github.com/adobe-fonts/source-han-sans/files/2394116/EBGaramondExample.pdf). I should have made this clearer.

#### Copied output:

```none
EBGaramond12-Italic.otf:
[ - ] бгдпт
[SRB] бгдпт
```

#### L<sup>A</sup>T<sub>E</sub>X source:

```tex
\documentclass[11pt]{article}
\usepackage{fontspec}
\setmainfont{Latin Modern Mono}

\newcommand*{\chars}{бгдпт}

\newcommand*{\samplepars}[1]{{%
  \vspace{\normalbaselineskip}%
  #1:\par
  \fontspec{#1}[Script=Cyrillic]%
  {\normalfont [ - ]} {\chars}\par
  {\normalfont [SRB]} {\addfontfeature{Language=Serbian}\chars}\par
}}

\begin{document}

\samplepars{EBGaramond12-Italic.otf}%

\end{document}
```

**Comment by kenlunde** [comment]
I recreated your document using Adobe InDesign, each line being language-tagged for the corresponding language. The appropriate/expected glyphs are used, and Copy&Paste works as expected.

[locl-test.pdf](https://github.com/adobe-fonts/source-han-sans/files/2394171/locl-test.pdf)

**Comment by kenlunde** [comment]
BTW, some of the characters that appear to be copied correctly from your original document actually have different code points when copied:

U+2EE3 ⻣ CJK RADICAL BONE
U+2EC6 ⻆ CJK RADICAL SIMPLIFIED HORN
U+FA45 海 CJK COMPATIBILITY IDEOGRAPH-FA45
U+FA68 難 CJK COMPATIBILITY IDEOGRAPH-FA68
U+FA45 海 CJK COMPATIBILITY IDEOGRAPH-FA45
U+FA36 喝 CJK COMPATIBILITY IDEOGRAPH-FA36
U+F996 練 CJK COMPATIBILITY IDEOGRAPH-F996
U+FA65 贈 CJK COMPATIBILITY IDEOGRAPH-FA65

Again, this is a PDF producer issue.
