### ISSUE TITLE
Consolidation of Post-V2 Glyph Sharing Suggestions

### ISSUE THREAD

**Issue by kenlunde** [adobe-fonts/source-han-sans#203]
The following table shows the glyphs that have been explicitly targeted for removal due to glyph sharing or other reasons:

**Character** | **Glyph Name** | **Notes**
--- | --- | ---
U+720B 爋 | _uni720B-JP_ | The CN glyph, _uni720B-CN_, will be default for all regions
U+89BE 覾 | _uni89BE-TW_ | The CN glyph, _uni89BE-CN_, will be default for all regions (see Issue #214); remove HK mapping override to _uni89BE-TW_
U+24A01 𤨁 | _u24A01-KR_ | Identical to CN glyph for U+7468 瑨, _uni7468-CN_ (see Issue #202)

**Comment by kenlunde** [comment]
@tamcy I am actually inclined to map U+4F2C 伬, U+544E 呎, U+54AB 咫, U+5C3A 尺, U+5EB9 庹, and U+8687 蚇 in the TW CMap resource to the corresponding HK glyphs. Also note that there are three additional cases whose forms are consistent, and used for both the TW and HK CMap resources: U+7C8E 粎, U+9FC8 鿈, and U+26B28 𦬨. These six mapping overrides are now reflected in the table in Issue #202.

**Comment by tamcy** [comment]
@kenlunde Ah yes, I forgot to also include the codepoints without regional-specific glyphs. Thanks.

**Comment by kenlunde** [comment]
Because actual glyph removal won't happen until Version 3.000 (unscheduled), I am closing this issue, and will track such cases in Issue #227.

For Version 2.000 dot releases, such cases will be handled via mapping overrides to the appropriate CMap resources (see Issue #202), leaving some glyphs unused.
