### ISSUE TITLE
Consolidation of Miscellaneous Post-V2 Changes

### ISSUE THREAD

**Issue by kenlunde** [adobe-fonts/source-han-sans#207]
The following miscellaneous changes are expected to made in the Version 2.002 update that might be released by the end of this year:

**Character** | **Glyph Name** | **Description**
--- | --- | ---
U+4E08 丈 | _uni4E08uE0101-JP_ | Make the glyph identical to the CN glyph, _uni4E08-CN_
U+5C83 岃 | _uni5C83-CN_ | Change identity to _uni5C83-HK_, and adjust the glyph per [IRG N2368](http://appsrv.cse.cuhk.edu.hk/~irg/irg/irg52/IRGN2368-HKSAR-Horizontal-Extension-20190412.pdf)
U+30EDD | _u00791-JP_ | Change identity to _u30EDD-JP_ (Extension G); remove special-casing for 'locl' GSUB feature; remove 'ccmp' GSUB feature entry
U+30EDD | _u00791-KR_ | Change identity to _u30EDD-KR_ (Extension G); remove special-casing for 'locl' GSUB feature; remove 'ccmp' GSUB feature entry
U+30EDD | _u00791-CN_ | Change identity to _u30EDD-CN_ (Extension G); remove special-casing for 'locl' GSUB feature; remove 'ccmp' GSUB feature entry
U+30EDD | _u00791-HK_ | Change identity to _u30EDD-HK_ (Extension G); remove special-casing for 'locl' GSUB feature; remove 'ccmp' GSUB feature entry
U+30729 | _u01200-KR_ | Change identity to _u30729-KR_ (Extension G); remove special-casing for 'locl' GSUB feature; remove 'ccmp' GSUB feature entry
U+30EDC | _u01312-CN_ | Change identity to _u30EDC-CN_ (Extension G); remove special-casing for 'locl' GSUB feature; remove 'ccmp' GSUB feature entry
U+3106B | _u02960-JP_ | Change identity to _u3106B-JP_ (Extension G); remove special-casing for 'locl' GSUB feature; remove 'ccmp' GSUB feature entry
U+3106B | _u02960-CN_ | Change identity to _u3106B-CN_ (Extension G); remove special-casing for 'locl' GSUB feature; remove 'ccmp' GSUB feature entry
U+3106B | _u02960-TW_ | Change identity to _u3106B-TW_ (Extension G); remove special-casing for 'locl' GSUB feature; remove 'ccmp' GSUB feature entry
U+3106B | _u02960-HK_ | Change identity to _u3106B-HK_ (Extension G); remove special-casing for 'locl' GSUB feature; remove 'ccmp' GSUB feature entry
_N/A_ | _N/A_ | Add the soon-to-be-registered 'chws' (_Contextual Half-width Spacing_) and 'vchw' (_Vertical Contextual Half-width Spacing_) GPOS features

The following miscellaneous changes were made in the Version 2.001 update:

**Character** | **Glyph Name** | **Description**
--- | --- | ---
U+32FF | _uni32FF_ & _uni32FF-V_ | Populate the blank placeholder glyphs with actual glyphs; change the glyph names to _uni32FF-JP_ and _uni32FF-JP-V_ to be consistent with the names of similar glyphs
U+752D 甭 | _uni752D-TW_ | Rename glyph as _uni752D-CN_ (see Issue #202)
U+752D 甭 | _uni752D-CN_ | Rename glyph as _uni752D-HK_ (see Issue #202); remove HK mapping override to _uni752D-CN_ (see Issue #202); add JP (and, by extension, KR) mapping override to _uni752D-HK_ (see Issue #202)

**Comment by wyuenho** [comment]
@kenlunde  Has the changes for #193 been released? I don't even see a `meta` table in 2.001.

**Comment by J-Vin** [comment]
Are these issues still unresolved? 🤯

**Comment by punchcutter** [comment]
The table above was addressed in the 2.002 release except for `chws` and `vchw` which require more discussion. The missing `meta` table will be addressed in https://github.com/adobe-fonts/source-han-sans/issues/270.
