### ISSUE TITLE
fallback issue of CJK-B block

### ISSUE THREAD

**Issue by CNMan** [adobe-fonts/source-han-sans#209]
### Description
I'm using `SourceHanSansHWSC-Regular.otf` and `SourceHanSansHWSC-Bold.otf` version 2.0.0 on RHEL 7.6,but it seems CJK-B block can't fallback to other fonts,and CJK-C/D/E/F blocks work fine.

![screenshot from 2018-11-22 01-04-10](https://user-images.githubusercontent.com/8692234/48857491-f818a280-edf3-11e8-92e3-42c4dbebecc4.png)
![screenshot from 2018-11-22 01-04-45](https://user-images.githubusercontent.com/8692234/48857492-f818a280-edf3-11e8-9f0d-77d478591c5f.png)

**Comment by kenlunde** [comment]
You're describing an RHEL issue, not a font issue. Something in RHEL is obviously special-casing Extension B.
