### ISSUE TITLE
Inconsistency in the 炙 (the top ⺼) component for HK

### ISSUE THREAD

**Issue by tamcy** [adobe-fonts/source-han-sans#210]
I am opening a new issue here because it may span multiple consolidated issues.

The resulting design of characters with the "⺼ on the top" component isn't quite consistent for HK (codepoints mentioned here are all within Big5 or HKSCS).

Take 然 (U+7136) as an example:
![20181126-g](https://user-images.githubusercontent.com/959433/49021170-fe7c9500-f1cc-11e8-8cde-b3da2f4f1acd.png)

TW's version is very different and is not discussed here. For the top left component, the two dots in JP version touch the first stroke, while the CN version don't. Let's call the former form "touched" and the CN one "untouched". This is the only difference for this particular component. For this codepoint a new glyph for HK is needed because 犬 is different from JP and CN. As shown above, new HK glyphs (there're about 43 of them) follow the JP form of ⺼, where two dots touch the first stroke, i.e. the "touched" form is used.

<details><summary>[Edit: Click to show are list of characters I found using the "touched" form for HK]</summary>
<p>

```
U+3625 㘥
U+3723 㜣
U+42A2 䊢
U+430A 䌊
U+4504 䔄
U+4533 䔳
U+4B19 䬙
U+509C 傜
U+55C2 嗂
U+5AB1 媱
U+5FAD 徭
U+612E 愮
U+649A 撚
U+6503 攃
U+669A 暚
U+69A3 榣
U+6A6A 橪
U+6AAB 檫
U+7099 炙
U+7136 然
U+718E 熎
U+71C3 燃
U+733A 猺
U+734E 獎
U+78D8 磘
U+7924 礤
U+7AB0 窰
U+7E47 繇
U+8521 蔡
U+8523 蔣
U+8628 蘨
U+8E68 蹨
U+9059 遙
U+91AC 醬
U+9390 鎐
U+98BB 颻
U+9C29 鰩
U+9DC2 鷂
U+21077 𡁷
U+24277 𤉷
U+26FBE 𦾾
U+28AE5 𨫥
U+297D4 𩟔
```
</p>
</details>

But when "whether the two dots touch the first stroke" is the only difference among the glyphs, no new HK glyph will be designed, and all glyphs are mapped to the CN version, causing inconsistency. For instance:

![20181126-h](https://user-images.githubusercontent.com/959433/49021249-266bf880-f1cd-11e8-8736-5c91a9dc922d.png)

I don't know if this is intentional (due to lack of CIDs), and I understand that this is subtle, but as such inconsistency is found in a single font instance I would like to see if this could be improved.

Here are the codepoints that can be mapped to the JP version:
```
U+50BA	傺
U+588F	墏
U+5C07	將  [edit: fixed codepoint]
U+5D88	嶈
U+69F3	槳
U+6F08	漈
U+6F3F	漿
U+796D	祭
U+7A44	穄
U+87BF	螿
U+8C4B	豋
U+8E61	蹡
U+969B	際
U+982F	頯 [edit: added 10 Dec]
U+9C36	鰶
```

Codepoints that cannot reuse existing glyph if the JP form is to be used:
```
U+46BB	䚻 (No JP) [edit: added]
U+5693	嚓 (丶)
U+58DF	察 (丶)
U+6416	搖 (山)
U+64E6	擦 (丶)
U+66A9	暩 (No JP)
U+7464	瑤 (山)  [edit: also note that the JP glyph uses the "untouched form"]
U+7635	瘵 (丶)
U+7E29	縩 (No JP)
U+8A67	詧 (丶)
U+08B2	謠 (丶,山)
U+93D8	鏘 (金. Can map to JP if upper part of 金 is unified)
U+9454	鑔 (No JP)  [edit: added]
```

I did find _[edit: two examples]_ of an HK glyph being redesigned because the ⺼ component is different:
![20181126-i](https://user-images.githubusercontent.com/959433/49053993-84302d00-f22d-11e8-85c9-0dbd1d41ca26.png)

Please help to see if any action is needed. Thanks!

**Comment by tamcy** [comment]
Similar "touching" inconsistency for 歺 - suggest to change the mapping of `U+74A8 璨 ` from CN to JP (ref: U+6FAF 澯)

**Comment by kenlunde** [comment]
@tamcy Apologies for taking so long to reply to these issues.

In order to set expectations, the glyph set includes only 50 CIDs in reserve, and we're thus far at 37 additional glyphs, leaving only 13 in reserve. And, I am not done going through the open issues.

For this particular issue, it's subtle enough that I am afraid that we will need to live with some degree of inconsistency. For the 16 cases that benefit from mapping to the JP glyph for the HK fonts, I just added appropriate entries to the table in Issue #202. Remapping is trivial.

**Comment by tamcy** [comment]
@kenlunde No problem, and understand that it's better to utilize the CIDs for more higher priority glyphs. Thanks for looking into this.
