### ISSUE TITLE
HK glyph issues regarding characters with “奧”

### ISSUE THREAD

**Issue by tamcy** [adobe-fonts/source-han-sans#212]
Currently, characters containing the 奧 component is mostly shared between TW and HK. However the design is different according to their conventions (for the last stroke of 冂, TW is like 亅 but HK/JP/CN look like 丨), so glyphs cannot be shared. New glyphs would be needed. 

![a1-diff](https://user-images.githubusercontent.com/959433/49431620-e6b69980-f7e8-11e8-9933-a610092db4b2.png)

Below are characters that are fine for TW but not HK:

| Character |
| ------------- | 
| U+5662 噢 | 
| U+5967 奧 | 
| U+6FB3 澳 | 
| U+71E0 燠 | 
| U+8581 薁 | 
| U+8956 襖 | 
| U+96A9 隩 | 

<details>
  <summary>Click to view image</summary>

  ![a2-twok](https://user-images.githubusercontent.com/959433/49431647-f7670f80-f7e8-11e8-9470-d0f8a69cb06c.png)
</details>

<br>  
Following TW glyphs are actually fine for HK but not for TW:

| Character |
| ------------- | 
| U+58BA 墺 | 
| U+5DB4 嶴 | 
| U+64D9 擙 | 

<details>
  <summary>Click to view image</summary>

  ![a3-hkok](https://user-images.githubusercontent.com/959433/49431789-39905100-f7e9-11e8-8afb-bd20052d1a0f.png)
</details>
<br>

FYI, U+61CA 懊 is where of both TW and HK glyphs are fine.

![a4-hktwok](https://user-images.githubusercontent.com/959433/49431949-883deb00-f7e9-11e8-9d98-a905aa4d89af.png)

**Comment by kenlunde** [comment]
These additional TW and HK glyphs are now noted in the table in Issue #206.
