### ISSUE TITLE
HK glyph issues for characters with “番”

### ISSUE THREAD

**Issue by tamcy** [adobe-fonts/source-han-sans#214]
Similar to #213 , this one is about how strokes of the standard glyph is interpreted, and the characters reported points to a larger issue.

First, the following 5 characters needs attention:

![d1](https://user-images.githubusercontent.com/959433/49433477-21223580-f7ed-11e8-9b06-60c16c2b5ce5.png)

| Codepoint | 
|  ------------- |
| U+5BE9 審 | 
| U+64AD 播 | 
| U+65DB 旛 | 
| U+6A4E 橎 | 
| U+700B 瀋 |

The bottom right stroke of 釆 is different from CN. HK could use the glyphs from TW, but I also found it is intentional to use a separate glyph set for HK because of a design difference from TW:

![d2](https://user-images.githubusercontent.com/959433/49433596-647ca400-f7ed-11e8-82ab-7192b0eeda6e.png)

Looks like the interpretation is that the center vertical stroke of 釆 in TW should be joined to the center vertical stroke of 田, as if they are one single stroke. HK, similar to JP/KR/CN, uses a disjoint version.

Seems the decision is based on TW’s standard document. In [宋體](https://language.moe.gov.tw/001/Upload/files/SITE_CONTENT/M0001/SUNGTI/as25.htm?open
) and [方體](https://language.moe.gov.tw/001/Upload/files/SITE_CONTENT/M0001/fangti/af25.htm?open) (No. 102651) masters, the center vertical strokes do look joined.

In this case, 5 new HK glyphs would be needed for the above characters.

But I’d argue that the disjoint version could also be used for TW, and it's a design but not standard difference:

1. The [stroke-order document]( https://language.moe.gov.tw/001/Upload/files/SITE_CONTENT/M0001/BISHUEN/p112a.htm) clearly shows that 釆 and 田 are written separately.
2. You can install the [宋體 SongTi, a.k.a. Serif](https://depart.moe.edu.tw/ed2400/News_Content.aspx?n=8940E5C0456177C3&sms=893AAA1CBFE149DE&s=161DEBC9EACEA333)/[Direct Link](https://ws.moe.edu.tw/Download.ashx?u=C099358C81D4876C5303003B8BD1CBF5A0106AD29D0342C9882B0DCC67B29D3F3D24AA6FFF8C5EEE81939E188A93C6332E5777D36296C2C36C029F6BE963B0F4435740FC4F302D952C2A60E8877C76A9&n=C3C7A8B3B9D12E153C175B7BD4F8282215F14ACC404C40D8&icon=..rar) and [楷書 Kaishu a.k.a. Script](https://depart.moe.edu.tw/ed2400/News_Content.aspx?n=8940E5C0456177C3&sms=893AAA1CBFE149DE&s=DFBE7BE3EE0DB6AE)/[Direct Link]( https://ws.moe.edu.tw/Download.ashx?u=C099358C81D4876C5303003B8BD1CBF5A0106AD29D0342C96EB319AE2D6BDEB4EE0A878EF0A975885123826EAED0A11E0A2D8896A8BF0F1A69DF0E3360DB8EC215CFA272AC758C9C05ACF7BDBD0DCE2A&n=B7AC7BE682935BF19B6FCA6E2E979468&icon=..rar) font files supplied by MoE to inspect the actual structure. The vertical strokes are are actually not joined.

![d3](https://user-images.githubusercontent.com/959433/49433796-c3421d80-f7ed-11e8-9ee3-806d39416c53.png)

I believe you are already aware about this, as Source Han Serif also uses a disjoint version.

There're also glyphs with disjoint version in Big5 and HKSCS range due to glyph sharing. For instance, U+52EB 勫, U+9131 鄱 and U+98DC 飜. 

![d4](https://user-images.githubusercontent.com/959433/49434038-44011980-f7ee-11e8-9fba-26a507794abd.png)

In contrast, TW glyph of U+7FFB 翻 (joined version) is used by HK.

![d5](https://user-images.githubusercontent.com/959433/49434353-f933d180-f7ee-11e8-9267-b6b2f2dc14a0.png)

Honestly the issue seems subtle to me. Personally I'd like to see it unified (such that the disjoint version is used). I can provide a comprehensive list of glyphs concerned if you are to take action on this issue.

**Comment by hfhchan** [comment]
Nit: While at it, it would be better if the second and third stroke for 釆 was handled consistently across different regions, since there is glyph sharing.
![image](https://user-images.githubusercontent.com/8191296/49443796-4a9c8a80-f808-11e8-8e37-045e66a0dfdf.png)

A while ago I also made a request to CLIAC to make the strokes more explictly disjointed in HKSCS-2016, which is why they look different from their Taiwanese cousins.

**Comment by kenlunde** [comment]
@tamcy I am thinking to unify these forms for TW and HK, using the disjoint form of 番, so please send to me—or add to this issue—a comprehensive list of affected Big Five and HKSCS code points at your earliest convenience. It seems that most of these will be TW glyphs that need 釆 and 田 to be separated.

For U+5E61 幡, the HK glyph will change identity to become the TW glyph, which will be shared by TW and HK.

**Comment by tamcy** [comment]
Sure. Here lists the characters with the 番 component, categorized into 5 tables.

Actions would be needed for characters in Table A-C. Table D-E are fine, and are included for completeness.

## Table A (22 characters)

[Table A character list](https://github.com/adobe-fonts/source-han-sans/files/2872663/issue214-A.pdf)

In this table, different glyphs are used for HK and TW, but their only difference is whether the center vertical lines of 番 appears joined.

For characters of this type, I believe your workflow would be renaming the HK glyph to TW and have it shared among HK and TW.

| Codepoint |
|  ------------- |
| U+50E0 僠 |
| U+58A6 墦 |
| U+5B0F 嬏 |
| U+5B38 嬸 |
| U+5D93 嶓 |
| U+5E61 幡 |
| U+71D4 燔 |
| U+756A 番 |
| U+78FB 磻 |
| U+7C53 籓 |
| U+7E59 繙 |
| U+7FB3 羳 |
| U+81B0 膰 |
| U+8543 蕃 |
| U+85E9 藩 |
| U+87E0 蟠 |
| U+8B52 譒 |
| U+8B85 讅 |
| U+8E6F 蹯 |
| U+8F53 轓 |
| U+9407 鐇 |
| U+9C55 鱕 |

## Table B (9 characters)

[Table B character list ](https://github.com/adobe-fonts/source-han-sans/files/2872664/issue214-B.pdf)

The TW glyphs in this table needs to be modified to have the vertical strokes disjointed. Possible additional actions are on the second column.

| Codepoint | Additonal action/remarks
|  ------------- | ---- |
| U+5BE9 審 | Also remap HK to TW
| U+64AD 播 | Also remap HK to TW
| U+65DB 旛 | Also remap HK to TW
| U+6A4E 橎 | Also remap HK to TW
| U+6F58 潘 | Also remap HK to TW
| U+700B 瀋 | Also remap HK to TW
| U+74A0 璠 | Also remap HK to TW
| U+76A4 皤 | Also remap HK to TW
| U+7FFB 翻 | HK already mapped to TW. This font intentionally uses a different design of 羽 for CN and TW/HK, with only a few exceptions. Otherwise the CN glyph could be used for HK and TW.

## Table C (1 character)

[Table C character list ](https://github.com/adobe-fonts/source-han-sans/files/2872665/issue214-C.pdf)

For this single character, CN glyph can be used for TW. The TW glyph can be removed.

| Codepoint | 
|  ------------- |
| U+89BE 覾 | 

## Table D (3 characters)

[Table D character list (PDF)](https://github.com/adobe-fonts/source-han-sans/files/2872666/issue214-D.pdf)

HK and TW are shared with other regions, no action needed.

| Codepoint | Remarks 
|  ------------- | ---- |
| U+52EB 勫 | Mapped to CN
| U+9131 鄱 | Mapped to CN
| U+9DED 鷭 | Mapped to JP

## Table E (5 characters)

[Table E character list (PDF)](https://github.com/adobe-fonts/source-han-sans/files/2872667/issue214-E.pdf)

Characters in the last table are HKSCS characters. They only have glyphs dedicated to HK, so no action is neccessary.

| Codepoint | 
|  ------------- |
| U+4AA4 䪤 | 
| U+5643 噃 | 
| U+98DC 飜 | 
| U+210D3 𡃓 | 
| U+24ABA 𤪺 | 

That's all.

**Comment by kenlunde** [comment]
@tamcy: Thank you. The action for Table C is now reflected in the table at the beginning of Issue #203. Tables D and E require no action, as you stated. I appreciate the completeness. I will record the actions for Tables A and B in the appropriate consolidated issues later today, then will close this issue.

**Comment by kenlunde** [comment]
The actions for Tables A and B are now reflected in the tables at the beginning of Issues #202, #204, and #207.

**Comment by kenlunde** [comment]
I just changed the action for the glyphs in Table A. The TW CMap will be changed so that the affected code points map to the HK glyph (see Issue #202), and it won't be until Version 3.000 that the HK glyphs will be renamed to become TW glyphs (see Issue #227), meaning that TW and HK will share the TW glyphs. In other words, the HK glyphs will be unused from the upcoming dot release.
