### ISSUE TITLE
Report of characters that may need new glyphs for HK

### ISSUE THREAD

**Issue by tamcy** [adobe-fonts/source-han-sans#215]
The following HK characters cannot share glyphs with other regions. A new glyph would probably be necessary, but I didn't go through all CIDs so I'm not sure if any unmapped glyph could be used. That's why I open a new issue here.

[Edit: removed 巟 & 慌 as they're reported before]

## A. 𦐇-related characters

| Character | Current region | Remarks
| ------------- |  ----- | ---- |
| U+6428 搨 | TW | Top-right component is different 
| U+69BB 榻 | TW | Top-right component is different
| U+6BFE 毾 | TW | Top-right component is different

![e0b](https://user-images.githubusercontent.com/959433/49446215-994d2300-f80e-11e8-934a-80242e042a20.png)

(I do have doubt about why this form was chosen, and will take my query to OCGIO-CLIAC when I have time)

## B. Others

| Character | Current region | Remarks
| ------------- |  ----- | ---- |
| U+38FA 㣺   | CN | I think its height should look like the JP glyph - not 100% sure though
| U+53B4 厴   | TW | The “bottom meat” component ⺼ is different, can‘t share with TW; 犬 is different so can't map to JP
| U+5EE8 廨  | JP | The first dot of 广 is not a vertical stroke
| U+64DB 擛   | JP | The grass radical 艹 is different, can’t share with JP 
| U+6A07 樇   | CN | Top-right component: CN uses 夂 while HK uses 攵
| U+6F16 漖   | CN | Unlike CN, the 子 doesn’t protrudes the 𠂇 component in HK (ref: U+6559 教, looks subtle to me tough)
| U+95B9 閹   | JP | Last stroke of 大 is curved towards inside
| U+9B2F 鬯   | JP | The bottom component 匕 is different, can’t use JP glyph (Ref: U+9B31 鬱)

![e1a](https://user-images.githubusercontent.com/959433/49445978-19bf5400-f80e-11e8-8e14-21a89038ce6d.png)
![e1b](https://user-images.githubusercontent.com/959433/49445981-19bf5400-f80e-11e8-930b-a424f18a16e8.png)

**Comment by tamcy** [comment]
![20181210](https://user-images.githubusercontent.com/959433/49712069-b43fed00-fc7d-11e8-986b-65c3bae9ca67.png)

| Character | Current region | Remarks
| ------------- |  ----- | ---- |
| U+69A7 榧   | JP | The 匚 component is different (this can actually be considered a design difference, just that it is not consistent with other characters)
| U+7DFB 緻   | CN | Rightmost component: CN uses攵while HK uses 夂 (ref. U+81F4 致)

**Comment by tamcy** [comment]
U+6BCC 毌: Currently using CN glyph.

![20181213-a](https://user-images.githubusercontent.com/959433/49914293-aed7e200-fecb-11e8-9f46-3ebdadebdc36.png)

毌 is the component used in 貫, 實 etc. The HK Reference Glyph document states that the TW form is the same as the HK form dispite the different at the bottom-right corner. So TW is a more suitable mapping if no new glyph is to be introduced.

![20181213-b](https://user-images.githubusercontent.com/959433/49914328-c44d0c00-fecb-11e8-9db6-a5fe5d454dd4.png)

**Comment by tamcy** [comment]
U+8943 襃: The component left to 呆 is same as that in 印, which consists of 4 srokes according to TW and HK conventions. The vertical stroke and the rising stroke are disconnected. So similar to U+88E6 裦 and U+890E 褎, a new glyph would be required for U+8943 襃.

![20181214-890f](https://user-images.githubusercontent.com/959433/49983836-f7f96600-ff9f-11e8-81d0-a92972c444fc.png)

**Comment by tamcy** [comment]
U+465B 䙛: The CN glyph was fixed by changing the middle component on the right from 厶 to 口, causing a side effect that it's no longer sharable with HK.

![20181215-d](https://user-images.githubusercontent.com/959433/50041609-a4b41000-0092-11e9-8032-8760111551ec.png)

U+9834 頴: Top-left component is different, can't use JP glyph.

![20181215-c](https://user-images.githubusercontent.com/959433/50041626-cc0add00-0092-11e9-8f88-0a79be57e270.png)

**Comment by LiliCharlie** [comment]
Also, whenever 女 is a left radical, as in 好 and numerous other characters, the strokes ㇒ piě and ㇀ tí for the HK glyphs should neither intersect (as in the current Source Han Sans HK font and in the TW standard), nor meet at their exact ends (as in the CN standard). Rather, ㇀ should touch ㇒ near its upper end. (Intersecting ㇒ and ㇐ héng are correct when there is no other component to the right of 女, as in 女, 妻, and for the upper and the lower right components of 姦, as opposed to the character's lower left component.)

**Comment by LiliCharlie** [comment]
Unlike all other CJK locales the 丱 component in HK-style 關 and 聯 has ㇑ instead of ㇓.

**Comment by LiliCharlie** [comment]
In the HKSCS Reference Font "華康標準宋體"="DFSongStd" available from https://www.ogcio.gov.hk/en/our_work/business/tech_promotion/ccli/download_area/font_and_software.html the characters look like this:
![u 95dc u 806f in dfsongstd](https://user-images.githubusercontent.com/41511677/50836885-9d62e800-135a-11e9-9948-8bcfac8370fc.png)
The 丱 component has a ㇑ where the other locales have a ㇓.

**Comment by tamcy** [comment]
@LiliCharlie Note that Source Han Sans HK follows the "Reference Glyphs for Chinese Computer Systems in Hong Kong" released by OGCIO in 2017, which can be downloaded [here](https://www.ogcio.gov.hk/tc/our_work/business/tech_promotion/ccli/cliac/reference_glyphs.html). The document is more recent than the font you mentioned, which was released in around 2007.

Here's an excerpt from the document. The non-vertical form is adopted for the 丱.
![refglyph](https://user-images.githubusercontent.com/959433/50837699-3f082a80-1397-11e9-9da3-df97af14437e.png)

**Comment by LiliCharlie** [comment]
@tamcy Oh, I see. And the same thing seems to have happened to the kai-style glyphs representing 關 and 聯.
Are the fonts the 2017 "Reference Glyphs for Chinese Computer Systems in Hong Kong" document was produced with available for purchase or otherwise?

**Comment by LiliCharlie** [comment]
@tamcy That's a pity. My pdf analysing tool reports that fonts called "華康香港新標準宋體(P)", "DFHKNewStdSong-W3-HKSCSP-U", "DFHKNewStdKai-W5-HKSCSP-U", and "華康香港新標準楷書(P)" are among the ones used to produce the document. The people of DynaComware Corp. should know more.

**Comment by kenlunde** [comment]
HK and TW glyph additions from this issue are now reflected in the table in Issue #206.

**Comment by tamcy** [comment]
Thanks! As the design of 狅 is different for TW and HK (the middle horizontal stroke is narrower than the bottom one for TW, for HK the middle one is the widest), I think a new HK glyph will also be needed in addition to fixing the current TW one?

**Comment by kenlunde** [comment]
Right. I modified the table in Issues #204 and #206 accordingly.
