### ISSUE TITLE
regular font cannot use in office or other apps

### ISSUE THREAD

**Issue by helllkz** [adobe-fonts/source-han-sans#218]
I have installed the 7 OTFs from https://github.com/adobe-fonts/source-han-sans/tree/release/OTF/SimplifiedChinese
I can see them in Win10 Font folder, but I can't choose the regular font in office or other apps. When I install it, the font name is different with others.
This is the regular version
![image](https://user-images.githubusercontent.com/14025168/50409287-8b4a5b00-082c-11e9-9592-7fa3487c1f3f.png)
This is the medium version
![image](https://user-images.githubusercontent.com/14025168/50409309-a3ba7580-082c-11e9-9e9d-a32bb69f27ce.png)

**Comment by kenlunde** [comment]
Merry Christmas!

Given that this is first report of such an issue, my best guess is that it is related to the font cache. I don't use Windows, so please search for the proper way to remove the font cache. I recommend that you uninstall these seven fonts before removing the font cache.

I will keep this issue open until you have a chance to try the above suggestion.
