### ISSUE TITLE
Found extra ascent with Java's FontMetrics

### ISSUE THREAD

**Issue by tonny1983** [adobe-fonts/source-han-sans#219]
**Background:**
The Java service uses Java AWT to draw some text in center of the canvas and save it as a png file (Get a `Graphics2D` instance  from a `BufferedImage` instance and then draw text with the `Graphics2D` instance)

**Problem:**
There seems be extra ascent of the SHS font that makes the text can not be shown in the center vertically. To find the y coordinate of the baseline, I use the following method:
 
    y coordinate = (Height of image - Height of FontMetrics) / 2 + Ascent of FontMetrics

The result is just as the following image:
![source-han-sans](https://user-images.githubusercontent.com/8895687/50431364-4c3c0880-0905-11e9-863f-c128cc506827.png)

The font size is 360 and font type is bold. The blue rectangle in the images shows the width and height get from  `FontMetrics`, the red line is the baseline. Actually, the blue rectangle locates in the center of the image, but the text itself is obviously on the lower side.

There's some number of the `FontMetrics` and the font: String Bounds weight=446, String Bounds height=521, Font Metrics height=522, Font Metrics ascent=418, Font Metrics descent=104, Font Metrics leading=0.

May I know is there any method to put the text in the center please?

ps: I found some related issues in android, like [#88 Behaviour of SHS on Android](https://github.com/adobe-fonts/source-han-sans/issues/88), but I don't know if it is the same problem due to JVM.

**Comment by kenlunde** [comment]
The Good News™ is that Java AWT is actually getting the specified metrics settings for ascender and descender, and not using the FontBBox settings as specified in the 'head' table, which is what Android OS does. Tampering with those settings will result in clipping of some glyphs, such as those with stacked accents in the U+01xx and U+1Exx ranges. In other words, there is nothing to fix in the fonts, and Java AWT appears to be getting the correct (as specified by the font) vertical metrics settings.

**Comment by tonny1983** [comment]
In other words, may I consider that it is a characteristic of SHS which has had more ascent than some other fonts? I tried the character of Unicode U+0168, and the result shows as follows:

![demo](https://user-images.githubusercontent.com/8895687/50463819-bf5a8300-09c8-11e9-8296-5fb06b4015ab.png)

and there's still some blank space above the Tilde (~).

**Comment by kenlunde** [comment]
There is no glyph for U+022A Ȫ in the fonts. Try U+01D7 Ǘ, U+01D9 Ǚ, and U+01DB Ǜ instead.

**Comment by kenlunde** [comment]
As to your question about leading, page 22 of the [ReadMe](https://github.com/adobe-fonts/source-han-sans/raw/release/SourceHanSansReadMe.pdf) states the following about the vertical metrics settings:

> The _OS/2.sTypoLineGap_ value has been set to 0 (zero) units, and is also reflected in the _hhea.LineGap_ and _vhea.lineGap_ values. The _OS/2.usWinAscent_ and _OS/2.usWinDescent_ values have been calculated by removing excessively tall and other vertical-only glyphs—for U+2E3A, U+2E3B, U+302A through U+302D, U+3031, and U+3032—from the equation, and have been harmonized across all seven weights. These same harmonized settings are also reflected in the _hhea.Ascender_ and _hhea.Descender_ values. This is for the benefit of applications that use these values for determining default leading. These and other 'OS/2' table settings are intended to provide consistent cross-platform line spacing (aka vertical metrics).

**Comment by tonny1983** [comment]
I appreciate your kind reply again. I think I've got the point ans know how to use the font.
