### ISSUE TITLE
cannot use OTF in Chrome, but can use subset OTF in Chrome

### ISSUE THREAD

**Issue by extc** [adobe-fonts/source-han-sans#221]
When use subset OTF, say SourceHanSansHK-Regular.otf
It can display font correctly in webpage (Chrome 71.0 32-bit), but some CJK characters failed due to out of HKSCS coverage
![image](https://user-images.githubusercontent.com/8214015/51076159-eb1b7f80-16cf-11e9-9a92-6d5ea2180380.png)

Result: 
![image](https://user-images.githubusercontent.com/8214015/51076129-8fe98d00-16cf-11e9-9bb1-47ad2f4b1233.png)

So, I try use OTF, say SourceHanSansHC-Regular.otf
It cannot display the font correctly. It use PMingLiU instead.
![image](https://user-images.githubusercontent.com/8214015/51076174-05555d80-16d0-11e9-8470-6341903c5c3d.png)

Result:
![image](https://user-images.githubusercontent.com/8214015/51076191-2fa71b00-16d0-11e9-9047-140da05f711b.png)

How can I solve this issue?

**Comment by kenlunde** [comment]
This is obviously a Chrome issue, so the appropriate action is to reach out to that product to report the issue. I suspect that the equivalent Noto Sans CJK font behaves the same.
