### ISSUE TITLE
新版本的差异太大，建议使用v1.000这个版本的字体

### ISSUE THREAD

**Issue by AssinX** [adobe-fonts/source-han-sans#223]
### Prerequisites

 1、v1.0000
![image](https://user-images.githubusercontent.com/45528222/51111618-8d09ac00-1837-11e9-867b-27676f2c7754.png)

2、v2.0000
![image](https://user-images.githubusercontent.com/45528222/51111723-ee317f80-1837-11e9-970e-fcb7ef762a8a.png)

### Description
 The new version of the difference is too big, it is recommended to use the v1.000 version of the font。

**Comment by kenlunde** [comment]
The CN glyph for U+8292 芒 is alive and well in the Version 2.000 fonts, as evidenced by the image below:

![uni8292-cn](https://user-images.githubusercontent.com/3988788/51114215-7f154600-17b9-11e9-9528-76ae30703d84.jpg)

Be sure to check your language settings, and that you're using the Simplified Chinese fonts. The script and language declarations were improved in the Version 2.000 which may have masked language-sensitive issues that were present in the Version 1.004 fonts.

**Comment by AssinX** [comment]
Ok，谢谢


原始邮件
发件人:CNMannotifications@github.com
收件人:adobe-fonts/source-han-sanssource-han-sans@noreply.github.com
抄送:狼牙liyuangao@aliyun.com; Authorauthor@noreply.github.com
发送时间:2019年1月15日(周二) 09:26
主题:Re: [adobe-fonts/source-han-sans] 新版本的差异太大，建议使用v1.000这个版本的字体 (#223)


你要用简体中文版本
 https://github.com/adobe-fonts/source-han-sans/raw/release/OTF/SourceHanSansSC.zip
 https://github.com/adobe-fonts/source-han-sans/raw/release/OTF/SourceHanSansHWSC.zip
 或
 https://github.com/adobe-fonts/source-han-sans/raw/release/SubsetOTF/SourceHanSansCN.zip
