### ISSUE TITLE
System.TypeInitializationException occurs when starting WPF .NET3.5 application in SourceHanSans.ttc installed environment.

### ISSUE THREAD

**Issue by garusany** [adobe-fonts/source-han-sans#224]
When the WPF .NET3.5 application reads the fontlist, an error occurs because the registry name is too long. (256 characters or more)
In SourceHanSans.ttc I installed, a registry name of 276 characters was registered.

Reading the fontlists is done within the WPF startup process, so it can not be controlled by our application code.
I want the length of the registry name to be 256 characters or less so that WPF .NET3.5 application can read it.
Although it can be avoided by shortening the registry name, it is difficult for our customers to do it.

**Comment by kenlunde** [comment]
@garusany You have encountered either 1) an environment that cannot handle OpenType/CFF Collections in general; or 2) an environment that cannot handle OpenType/CFF Collections that include a large number of fonts.

The _Source Han Sans_ Super OTC, _SourceHanSans.ttc_, includes 45 fonts. If it's the latter issue, you should install the per-weight OpenType/CFF Collections, which include five or ten fonts, depending on the weight.

If they also exhibit the same error, then it's the former issue, and you should install the individual OpenType/CFF fonts.

There is nothing that can be adjusted in the fonts, because it appears to be a limitation of your environment.

**Comment by garusany** [comment]
@kenlunde Thanks your comment.
It is not just my environment. Errors will occur in all WPF .NET 3.5 Application even in your environment installed SourceHanSans.ttc. 
Because of the WPF specification(already confirmed by Microsoft), WPF reads all installed fonts even though our application is not using SourceHanSans.ttc.
SourceHanSans.ttc is unnecessary to use our application, but if our customers install SourceHanSans.ttc for another purpose, our application can not be launched.

Do you know SourceHanSans.ttc has long name to register in the registory?
(below is SourceHanSans.ttc's name in"HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Fonts")
''源ノ角ゴシック ExtraLight & Source Han Sans K ExtraLight & Source Han Sans SC ExtraLight & Source Han Sans TC ExtraLight & Source Han Sans HC ExtraLight & 源ノ角ゴシック Light & Source Han Sans K Light & Source Han Sans SC Light & Source Han Sans TC Light & Source Han Sans""

The long name registered in the registry is in the SourceHanSans.ttc file.
Will you shorten this name?

**Comment by kenlunde** [comment]
@garusany First and foremost, there is nothing that can be changed in _SourceHanSans.ttc_ to fix this. How a font installation writes to the Registry is a Windows issue. The font really has no control over that. The font names are actually as short as they can possibly be. 

Not being a user of Windows, it seems that there are newer versions of WPF .NET. What is the behavior in such environments?

**Comment by garusany** [comment]
@kenlunde I confirmed that Windows will create a name to register in the registry when installing the ttc file.
Apparently, unless we shorten the registry name, it seems that .NET 3.5 applications can not be launched in the environment where SourceHanSans.ttc is installed.
In the latest. NET, as the length of registry names that can be read has been extended, we plan to upgrade the application.
Thanks.
