### ISSUE TITLE
Inconsistent shapes for 着, 魔, 麿 (T Chinese)

### ISSUE THREAD

**Issue by azurerime** [adobe-fonts/source-han-sans#23]
The top part of the 着 should be the same as 差, not the SChinese writing.
The 鬼 of 魔 is wrong, not the SChinese writing.
The 麻 of 麿 is wrong, not the Japanese writing.

**Comment by kenlunde** [comment]
Consolidated with Issue #48.

**Comment by hfhchan** [comment]
For the record, http://dict2.variants.moe.edu.tw/variants/rbt/word_attribute.rbt?educode=A03506-003#51 has since been updated to show the correct glyph.

**Comment by kenlunde** [comment]
@hfhchan: Thank you for the update. It is interesting to note that the glyph correction was made by hand, not by correcting the font.

**Comment by hfhchan** [comment]
They reused the scans from version 5.  Most likely because the glyph forms for version 6 is outsourced, and the glyph they designed is incorrect (see CNS11643)
