### ISSUE TITLE
Please add several characters used in Gan Chinese

### ISSUE THREAD

**Issue by showerying** [adobe-fonts/source-han-sans#231]
[𠮶](https://gan.wikipedia.org/wiki/%E5%B0%81%E9%9D%A2) (U+20BB6)
[𠵹](https://gan.wikipedia.org/wiki/%E5%B9%AB%E5%8A%A9:%F0%A0%B5%B9) (U+20D79)
[𡃙](https://gan.wikipedia.org/wiki/%E5%B9%AB%E5%8A%A9:%F0%A1%83%99%E5%90%A4) (U+210D9)
[𠿓](https://gan.wikipedia.org/wiki/%E5%B9%AB%E5%8A%A9:%F0%A0%BF%93%E5%8F%AB) (U+20FD3)
[𠸂](https://gan.wikipedia.org/wiki/%E5%B9%AB%E5%8A%A9:%E5%91%B9%E5%91%B9%F0%A0%B8%82%F0%A0%B8%82) (U+20E02)
[𡁎](https://gan.wikipedia.org/wiki/%E5%B9%AB%E5%8A%A9:%E5%97%97%E3%96%A1%F0%A1%81%8E) (U+2104E)
[𡄟](https://gan.wikipedia.org/wiki/%E5%B9%AB%E5%8A%A9:%F0%A1%84%9F) (U+2111F)
[𪫮](https://gan.wikipedia.org/wiki/%E5%B9%AB%E5%8A%A9:%F0%AA%AB%AE%E9%A9%9A) (U+2AAEE)
[𨈢](https://gan.wikipedia.org/wiki/%E5%B9%AB%E5%8A%A9:%F0%A8%88%A2%E7%98%A6) (U+28222)
[𡨢](https://gan.wikipedia.org/wiki/%E5%B9%AB%E5%8A%A9:%E9%9B%9E%F0%A1%A8%A2) (U+21A22)
[𦑃](https://gan.wikipedia.org/wiki/%E5%B9%AB%E5%8A%A9:%E7%BF%BC%F0%A6%91%83) (U+26443)
[𧎩](https://gan.wikipedia.org/wiki/%E5%B9%AB%E5%8A%A9:%F0%A7%8E%A9%E8%9F%86) (U+273A9)
[𡱶](https://gan.wikipedia.org/wiki/%E5%B9%AB%E5%8A%A9:%F0%A1%B1%B6%E5%B0%BF) (U+21C76)
[𤆷](https://gan.wikipedia.org/wiki/%E5%B9%AB%E5%8A%A9:%F0%A4%86%B7) (U+241B7)
[𥣘](https://gan.wikipedia.org/wiki/%E5%B9%AB%E5%8A%A9:%F0%A5%A3%98%E7%A9%80) (U+258D8)
[𨶪](https://gan.wikipedia.org/wiki/%E5%B9%AB%E5%8A%A9:%F0%A8%B6%AA%E9%9D%A2) (U+28DAA)
[𩑦](https://gan.wikipedia.org/wiki/%E5%B9%AB%E5%8A%A9:%F0%A9%91%A6%E6%AD%BB) (U+29466)
[𨡭](https://gan.wikipedia.org/wiki/%E5%B9%AB%E5%8A%A9:%E5%80%92%F0%A8%A1%AD) (U+2886D)
[𣒣](https://gan.wikipedia.org/wiki/%E5%B9%AB%E5%8A%A9:%F0%A3%92%A3%E6%A7%8C) (U+234A3)
[𥬝](https://gan.wikipedia.org/wiki/%E5%B9%AB%E5%8A%A9:%F0%A5%AC%9D%E5%AD%90) (U+25B1D)
[𥵦](https://gan.wikipedia.org/wiki/%E5%B9%AB%E5%8A%A9:%F0%A5%B5%A6%E9%9E%AD) (U+25D66)
[𣗺](https://gan.wikipedia.org/wiki/%E5%B9%AB%E5%8A%A9:%F0%A3%97%BA%E9%A4%85) (U+235FA)
[𩪕](https://gan.wikipedia.org/wiki/%E5%B9%AB%E5%8A%A9:%E7%88%9B%F0%A9%AA%95) (U+29A95)
[𦺔](https://gan.wikipedia.org/wiki/%E5%B9%AB%E5%8A%A9:%E9%9D%92%F0%A6%BA%94%E5%91%B3) (U+26E94)
[𤓋](https://gan.wikipedia.org/wiki/%E5%B9%AB%E5%8A%A9:%F0%A4%93%8B) (U+244CB)
[𣴶](https://gan.wikipedia.org/wiki/%E5%B9%AB%E5%8A%A9:%F0%A3%B4%B6) (U+23D36)
[𤋦](https://gan.wikipedia.org/wiki/%E5%B9%AB%E5%8A%A9:%F0%A4%8B%A6) (U+242E6)
[𠒱](https://gan.wikipedia.org/wiki/%E5%B9%AB%E5%8A%A9:%E5%A4%A7%F0%A0%92%B1) (U+204B1)
[𢝜](https://gan.wikipedia.org/wiki/%E5%B9%AB%E5%8A%A9:%E8%80%81%F0%A2%9D%9C) (U+2275C)
[𧬪](https://gan.wikipedia.org/wiki/%E5%B9%AB%E5%8A%A9:%F0%A7%AC%AA%E5%AD%90%E7%BE%85%E6%BC%A2) (U+27B2A)
[𪃏](https://gan.wikipedia.org/wiki/%E5%B9%AB%E5%8A%A9:%F0%AA%83%8F%E5%AD%90) (U+2A0CF)
[𠖫](https://gan.wikipedia.org/wiki/%E5%B9%AB%E5%8A%A9:%F0%A0%96%AB) (U+205AB)
[𠞊](https://gan.wikipedia.org/wiki/%E5%B9%AB%E5%8A%A9:%F0%A0%9E%8A) (U+2078A)
[𠞭](https://gan.wikipedia.org/wiki/%E5%B9%AB%E5%8A%A9:%F0%A0%9E%AD) (U+207AD)
[𢄺](https://gan.wikipedia.org/wiki/%E5%B9%AB%E5%8A%A9:%F0%A2%84%BA) (U+2213A)
[𢫈](https://gan.wikipedia.org/wiki/%E5%B9%AB%E5%8A%A9:%F0%A2%AB%88) (U+22AC8)
[𢫯](https://gan.wikipedia.org/wiki/%E5%B9%AB%E5%8A%A9:%F0%A2%AB%AF) (U+22AEF)
[𢯩](https://gan.wikipedia.org/wiki/%E5%B9%AB%E5%8A%A9:%F0%A2%AF%A9) (U+22BE9)
[𢰩](https://gan.wikipedia.org/wiki/%E5%B9%AB%E5%8A%A9:%F0%A2%B0%A9) (U+22C29)
[𢰹](https://gan.wikipedia.org/wiki/%E5%B9%AB%E5%8A%A9:%F0%A2%B0%B9) (U+22C39)
[𢲵](https://gan.wikipedia.org/wiki/%E5%B9%AB%E5%8A%A9:%F0%A2%B2%B5) (U+22CB5)
[𢵫](https://gan.wikipedia.org/wiki/%E5%B9%AB%E5%8A%A9:%F0%A2%B5%AB) (U+22D6B)
[𢶫](https://gan.wikipedia.org/wiki/%E5%B9%AB%E5%8A%A9:%F0%A2%B6%AB) (U+22DAB)
[𢷺](https://gan.wikipedia.org/wiki/%E5%B9%AB%E5%8A%A9:%F0%A2%B7%BA) (U+22DFA)
[𢺯](https://gan.wikipedia.org/wiki/%E5%B9%AB%E5%8A%A9:%F0%A2%BA%AF) (U+22EAF)
[𥾵](https://gan.wikipedia.org/wiki/%E5%B9%AB%E5%8A%A9:%F0%A5%BE%B5) (U+25FB5)
[𫐩](https://gan.wikipedia.org/wiki/%E5%B9%AB%E5%8A%A9:%F0%AB%90%A9%E5%8B%95) (U+2B429)
[𧻙](https://gan.wikipedia.org/wiki/%E5%B9%AB%E5%8A%A9:%F0%A7%BB%99) (U+27ED9)
[𧾛](https://gan.wikipedia.org/wiki/%E5%B9%AB%E5%8A%A9:%F0%A7%BE%9B) (U+27F9B)
[𧿨](https://gan.wikipedia.org/wiki/%E5%B9%AB%E5%8A%A9:%F0%A7%BF%A8) (U+27FE8)
[𨃰](https://gan.wikipedia.org/wiki/%E5%B9%AB%E5%8A%A9:%F0%A8%83%B0) (U+280F0)
[𨅃](https://gan.wikipedia.org/wiki/%E5%B9%AB%E5%8A%A9:%F0%A8%85%83) (U+28143)
[𨅎](https://gan.wikipedia.org/wiki/%E5%B9%AB%E5%8A%A9:%F0%A8%85%8E) (U+2814E)
[𨅔](https://gan.wikipedia.org/wiki/%E5%B9%AB%E5%8A%A9:%F0%A8%85%94) (U+28154)
[𨅞](https://gan.wikipedia.org/wiki/%E5%B9%AB%E5%8A%A9:%F0%A8%85%9E%E8%B7%A4) (U+2815E)
[𨆄](https://gan.wikipedia.org/wiki/%E5%B9%AB%E5%8A%A9:%F0%A8%86%84) (U+28184)
[𥆝](https://gan.wikipedia.org/wiki/%E5%B9%AB%E5%8A%A9:%F0%A5%86%9D) (U+2519D)
[𥇇](https://gan.wikipedia.org/wiki/%E5%B9%AB%E5%8A%A9:%F0%A5%87%87) (U+251C7)
[𥈆](https://gan.wikipedia.org/wiki/%E5%B9%AB%E5%8A%A9:%F0%A5%88%86) (U+25206)
[𥉟](https://gan.wikipedia.org/wiki/%E5%B9%AB%E5%8A%A9:%F0%A5%89%9F) (U+2525F)
[𥌮𥉶](https://gan.wikipedia.org/wiki/%E5%B9%AB%E5%8A%A9:%F0%A5%8C%AE) (U+2532E、U+25276)
[𢭎](https://gan.wikipedia.org/wiki/%E5%B9%AB%E5%8A%A9:%F0%A2%AD%8E) (U+22B4E)
[𢺴](https://gan.wikipedia.org/wiki/%E5%B9%AB%E5%8A%A9:%F0%A2%BA%B4) (U+22EB4)
[𢿤](https://gan.wikipedia.org/wiki/%E5%B9%AB%E5%8A%A9:%F0%A2%BF%A4%E5%A3%81) (U+22FE4)
[𨆎](https://gan.wikipedia.org/wiki/%E5%B9%AB%E5%8A%A9:%F0%A8%86%8E%E5%8B%95) (U+2818E)
[𨑜](https://gan.wikipedia.org/wiki/%E5%B9%AB%E5%8A%A9:%F0%A8%91%9C) (U+2845C)
[𩏠](https://gan.wikipedia.org/wiki/%E5%B9%AB%E5%8A%A9:%F0%A9%8F%A0%E5%B1%8E) (U+293E0)
[𠸟](https://gan.wikipedia.org/wiki/%E5%B9%AB%E5%8A%A9:%E6%89%93%F0%A0%B8%9F) (U+20E1F)
[𠯑](https://gan.wikipedia.org/wiki/%E5%B9%AB%E5%8A%A9:%F0%A0%AF%91) (U+20BD1)
[𠲰](https://gan.wikipedia.org/wiki/%E5%B9%AB%E5%8A%A9:%F0%A0%B2%B0) (U+20CB0)
[𠷀](https://gan.wikipedia.org/wiki/%E5%B9%AB%E5%8A%A9:%F0%A0%B7%80) (U+20DC0)
[𠱽](https://gan.wikipedia.org/wiki/%E5%B9%AB%E5%8A%A9:%F0%A0%B1%BD) (U+20C7D)
[𧨀](https://gan.wikipedia.org/wiki/%E5%B9%AB%E5%8A%A9:%F0%A7%A8%80) (U+27A00)
[𧬩](https://gan.wikipedia.org/wiki/%E5%B9%AB%E5%8A%A9:%F0%A7%AC%A9) (U+27B29)
[𧮙](https://gan.wikipedia.org/wiki/%E5%B9%AB%E5%8A%A9:%F0%A7%AE%99) (U+27B99)
[𢜴](https://gan.wikipedia.org/wiki/%E5%B9%AB%E5%8A%A9:%F0%A2%9C%B4) (U+22734)
[𠱇](https://gan.wikipedia.org/wiki/%E5%B9%AB%E5%8A%A9:%E4%BD%9C%F0%A0%B1%87) (U+20C47)
[𪶶](https://gan.wikipedia.org/wiki/%E5%B9%AB%E5%8A%A9:%F0%AA%B6%B6) (U+2ADB6)
[𩱚](https://gan.wikipedia.org/wiki/%E5%B9%AB%E5%8A%A9:%F0%A9%B1%9A) (U+29C5A)
[𢾖](https://gan.wikipedia.org/wiki/%E5%B9%AB%E5%8A%A9:%F0%A2%BE%96%E6%B0%B4) (U+22F96)
[𣹧](https://gan.wikipedia.org/wiki/%E5%B9%AB%E5%8A%A9:%F0%A3%B9%A7%E6%B0%B4) (U+23E67)
[𣽼](https://gan.wikipedia.org/wiki/%E5%B9%AB%E5%8A%A9:%F0%A3%BD%BC) (U+23F7C)
[𥟁](https://gan.wikipedia.org/wiki/%E5%B9%AB%E5%8A%A9:%F0%A5%9F%81) (U+257C1)
[𥣰](https://gan.wikipedia.org/wiki/%E5%B9%AB%E5%8A%A9:%F0%A5%A3%B0) (U+258F0)
[𩗁](https://gan.wikipedia.org/wiki/%E5%B9%AB%E5%8A%A9:%F0%A9%97%81) (U+295C1)
[𠋬](https://gan.wikipedia.org/wiki/%E5%B9%AB%E5%8A%A9:%F0%A0%8B%AC) (U+202EC)
[𠍀](https://gan.wikipedia.org/wiki/%E5%B9%AB%E5%8A%A9:%F0%A0%8D%80) (U+20340)
[𡠜](https://gan.wikipedia.org/wiki/%E5%B9%AB%E5%8A%A9:%F0%A1%A0%9C) (U+2181C)
[𪐀](https://gan.wikipedia.org/wiki/%E5%B9%AB%E5%8A%A9:%F0%AA%90%80) (U+2A400)
[𨐖](https://gan.wikipedia.org/wiki/%E5%B9%AB%E5%8A%A9:%E7%B5%95%F0%A8%90%96) (U+28416)
[𤽥](https://gan.wikipedia.org/wiki/%E5%B9%AB%E5%8A%A9:%F0%A4%BD%A5%E7%99%BD) (U+24F65)
[𦧮](https://gan.wikipedia.org/wiki/%E5%B9%AB%E5%8A%A9:%F0%A6%A7%AE%E8%8B%A6) (U+269EE)
[𨐣](https://gan.wikipedia.org/wiki/%E5%B9%AB%E5%8A%A9:%F0%A8%90%A3%E8%BE%A3) (U+28423)
[𨡲](https://gan.wikipedia.org/wiki/%E5%B9%AB%E5%8A%A9:%F0%A8%A1%B2%E9%85%B8) (U+28872)
[𩟓](https://gan.wikipedia.org/wiki/%E5%B9%AB%E5%8A%A9:%F0%A9%9F%93%E6%B7%A1) (U+297D3)
[𤁂](https://gan.wikipedia.org/wiki/%E5%B9%AB%E5%8A%A9:%F0%A4%81%82%E5%86%B7) (U+24042)
[𤈽](https://gan.wikipedia.org/wiki/%E5%B9%AB%E5%8A%A9:%F0%A4%88%BD%E6%BB%BE) (U+2423D)
[𦄓](https://gan.wikipedia.org/wiki/%E5%B9%AB%E5%8A%A9:%F0%A6%84%93) (U+26113)
[𦖝](https://gan.wikipedia.org/wiki/%E5%B9%AB%E5%8A%A9:%F0%A6%96%9D%E8%80%B3) (U+2659D)
[𦟳](https://gan.wikipedia.org/wiki/%E5%B9%AB%E5%8A%A9:%F0%A6%9F%B3%E4%BA%BA) (U+267F3)
[𨢇](https://gan.wikipedia.org/wiki/%E5%B9%AB%E5%8A%A9:%F0%A8%A2%87) (U+28887)
[𩢎](https://gan.wikipedia.org/wiki/%E5%B9%AB%E5%8A%A9:%F0%A9%A2%8E) (U+2988E)
[𪏻](https://gan.wikipedia.org/wiki/%E5%B9%AB%E5%8A%A9:%F0%AA%8F%BB) (U+2A3FB)
[𨈓](https://gan.wikipedia.org/wiki/%E5%B9%AB%E5%8A%A9:%F0%A8%88%93) (U+28213)
[𣽛](https://gan.wikipedia.org/wiki/%E5%B9%AB%E5%8A%A9:%F0%A3%BD%9B%E9%BB%8F) (U+23F5B)
[𣇤](https://gan.wikipedia.org/wiki/%E5%B9%AB%E5%8A%A9:%F0%A3%87%A4%E7%86%B1) (U+231E4)
[𡋿](https://gan.wikipedia.org/wiki/%E5%B9%AB%E5%8A%A9:%F0%A1%8B%BF) (U+212FF)
[𦢛](https://gan.wikipedia.org/wiki/%E5%B9%AB%E5%8A%A9:%E6%B2%B9%F0%A6%A2%9B) (U+2689B)
[𢧵](https://gan.wikipedia.org/wiki/%E5%B9%AB%E5%8A%A9:%E4%B8%80%F0%A2%A7%B5%E5%AD%90) (U+229F5)
[𡐶](https://gan.wikipedia.org/wiki/%E5%B9%AB%E5%8A%A9:%F0%A1%90%B6) (U+21436)
[𥭭](https://gan.wikipedia.org/wiki/%E5%B9%AB%E5%8A%A9:%F0%A5%AD%AD) (U+25B6D)
[𡰿](https://gan.wikipedia.org/wiki/%E5%B9%AB%E5%8A%A9:%E6%8D%8A%E6%8D%8A%F0%A1%B0%BF%F0%A1%B0%BF) (U+21C3F)
[𢺑](https://gan.wikipedia.org/wiki/%E5%B9%AB%E5%8A%A9:%E6%94%A6%E6%94%A6%F0%A2%BA%91%F0%A2%BA%91) (U+22E91)

**Comment by kenlunde** [comment]
Without additional information as to their importance, you just created a huge non-starter issue. At some point, in the far future, we hope to support all CJK Unified Ideographs, but doing it piece-meal isn't going to work. Supporting Macao SAR as a third form of Traditional Chinese has higher priority.

**Comment by kenlunde** [comment]
@showerying If you'd like these 114 ideographs—111 from Extension B and three from Extension C—added to Issue #222 for consideration for Version 3.000 (unscheduled), you will need to provide more details, such as 1) whether this is a definitive list of required ideographs; 2) which regional conventions should be used, with CN, TW, and HK being the choices (based on the [Wikipedia article](https://en.wikipedia.org/wiki/Gan_Chinese), I am guessing CN); and 3) and any additional details that you think would be helpful for me and others who are watching this project.

**Comment by showerying** [comment]
@kenlunde I see. Thanks for explanations.

**Comment by hfhchan** [comment]
@showerying Based on the links, it seems the data is pulled out of Wikipedia directly.  If there are more published sources, such as an authoritative dictionary, that would definitely help.
