### ISSUE TITLE
SourceHanSansSC-Regular.otf的「演」字问题

### ISSUE THREAD

**Issue by xiezuoziti** [adobe-fonts/source-han-sans#238]
SourceHanSansSC-Regular.otf 里的「演」字，某些字号会有笔画缺失的显示问题，如图所示。
![2019-06-02 20 19 08  d234c3418d26](https://user-images.githubusercontent.com/48599154/58763798-402e3400-8592-11e9-96be-c30c5b55b843.png)
有人关注或者解决就再补充说明：
系统为debian最新版，显示器是24寸16：9的2K屏，「演」字在该系统下的各种应用里，在调整到一定字号，或者缩放到一定值的时候，都会出现笔画缺失的显示问题，而这个大小比例又刚好是适合阅读的值，所以很明显就能察觉到这个问题。
所使用其他的字体，比如 Droid Sans Fallback 和思源宋体等等则不会有此类问题。
希望能针对这个显示环境进行优化。
具体还需要什么信息可以再问，后续补充。

**Comment by showerying** [comment]
描述太少了
