### ISSUE TITLE
Microsoft Word with Acrobat add-in cannot embed certain SuperOTC weights in a PDF

### ISSUE THREAD

**Issue by Synacrystal** [adobe-fonts/source-han-sans#239]
This seems to be an app-side problem but I’d like to mention here. I’m using Windows 10 1903 and working with Office 365 and Acrobat add-in installed. When creating PDF, the add-in cannot embed the Medium or Heavy weights of SuperOTC. However, ExtraLight, Light, Normal, or Regular weights are fine. And using seperated OTC has no problem.

**Comment by kenlunde** [comment]
We have open bugs against our (Adobe) apps when running on Windows 10 that are similar to this, and it is definitely an app or OS bug, and not a font one. Until this is fixed on the app or OS side, your work-around is the correct one.

Exposing poor behavior is always a good idea, and this is one reason why I developed the [Source Han & Noto CJK Mega/Ultra OTCs](https://github.com/adobe-fonts/source-han-super-otc/) project. The 216-font Ultra OTC is excellent testing fodder. It works perfectly on macOS..
