### ISSUE TITLE
Half Width Source Han Sans font width looks strange in MATLAB

### ISSUE THREAD

**Issue by pianzuo** [adobe-fonts/source-han-sans#241]
Hi, hello. I was writing some code a few minutes ago. I found that source hans sans HW SC (Version 2.001) in MATLAB （2018b, Windows 10 x64 v1809）looks strange. English letters and digit are not the monospaced. So I generate some random combination of readable-ASCII character. 

And it looks like this in MATLAB

![image](https://user-images.githubusercontent.com/13371759/60757995-2a55d800-a044-11e9-8a0f-49f0e27b9ce6.png)

I don't whether or not it is a bug of MATLAB. But if I choose another font in MATLAB, for example Courier New, it looks normal:

![image](https://user-images.githubusercontent.com/13371759/60757998-32157c80-a044-11e9-86c5-70930bb781fc.png)

thanks for your time!

**Comment by pianzuo** [comment]
These are the example I use:
mv,v\):Sz{.|zNl-Hvk{^#px`gfE^0c#:$)nb>z#IDhk1NJ]cg:`^/+O{@W5g8Pbt{S-.8o8m7xA27ZL
AnWTw;ggDU'%Rjx,VL!@/k=R/Y8^agJ'5v.nS~'J*{ imr(E8lHv19-,rWT-q[APF'6+16G$uyNN@uC*
jE6F),yzV%6An!$0]e]JS<f1a1C[j'xiNIJ=PPmk]CmRAysT[W3<L5p2505I=wH1u}I*8FX8Yc5+<>HP
(8l"xeNV6K{SQ6N[`EB}#tvk)8?`,d*^Njcut?b2"fOMuYZqlV16t"N/|cOL%`$&Q)mmd.^Q|]lKIn',
0Enl%ERG^[;I!}/*C2N@zw%f9HTyG}<b_Sb_0,~0#Us_2CK}.q]C2HM+X5DW7;Z9n}e@W*vsm8X"H=/0
H(XLbb\#&>R^Fmd|R>*ZiH(9.:IRKsQy\z6`;_b&85_p@j` YDw KHKi>jL#0dL.@Y2f7w9h1;(V`SH]
]`\y3c6+YJK^iA^Goo8ZWSr9>+y]M\S]SdQ~4**&FJBh[ix|2-b(QRqNE_fQA.W8$g7JaBeE`bJ!?H92
nHtEiElgC4kz?_Ioi/q~PtW.2Fgnk>R(*,`O2O.%pUxbWms} rZ~RMl5OuVpfW7_'[^et}iWxW!+qNp3
T[#ZB$N2+3-1$\:SbORJ+Nqs93U\G3z'*-/ZV$xef&qx}qjP0E,"y<<?L]"pUqAJ%0^?u+}Sc~;GLhm)
0B%Q?03u`Lv)feU1X<,4u&7%I!u2(=K)~?<%<$Ph[('iuR*n@;f $_YQecj;aTE%j@Yf),TNtke$&(ky

**Comment by stone-zeng** [comment]
Can't reproduce the issue in VS Code (v1.36.0 on macOS):

![image](https://user-images.githubusercontent.com/18233088/60758232-85d59500-a047-11e9-99bd-d1ad9f111b62.png)

**Comment by pianzuo** [comment]
It seems it appear only on MATLAB. But other Monospace font looks normally
in
MATLAB.

Xiangdong Zeng <notifications@github.com> 于 2019年7月6日周六 23:43写道：

**Comment by kenlunde** [comment]
@pianzuo Try using [_Source Han Mono_](https://github.com/adobe-fonts/source-han-mono/) instead.

**Comment by pianzuo** [comment]
Better， but still not monospace
![image](https://user-images.githubusercontent.com/13371759/60762412-a9253200-a091-11e9-912d-a05b98985b97.png)

**Comment by kenlunde** [comment]
You're dealing with a MATLAB peculiarity. _Source Han Mono_ includes no GPOS features and no alternate forms of those glyphs that have different metrics.
