### ISSUE TITLE
how to compile form source(.ttc)? I just want 'HW' include 'SC','TC'. I want use it in website. All font too big size for website

### ISSUE THREAD

**Issue by ganluo960214** [adobe-fonts/source-han-sans#252]
how to compile form source(.ttc)? I just want 'HW' include 'SC','TC'. I want use it in website. All font too big size for website

**Comment by frankrolf** [comment]
FYI: The .ttc file is not the source file for this project.
You may have some look looking into the https://github.com/adobe-fonts/source-han-sans/blob/master/COMMANDS.txt file – here the different parts of the project are assembled.

That said, it is probably worth looking into serving the font via Adobe Typekit webfonts, which supports dynamic augmentation (and therefore limits the file size): https://fonts.adobe.com/fonts/source-han-sans-traditional-chinese

**Comment by ganluo960214** [comment]
can I build .ttc file from this project?

**Comment by sgalal** [comment]
I am not the project maintainer, but I believe the web fonts are quite easy to access on Google fonts.

It contains Noto Sans JP/KR/SC/TC/HK. The web fonts are split into parts so there will be no size concern. You do not need to compile the fonts on your own.
