### ISSUE TITLE
Would you like to make a variable version of Source Han Sans?

### ISSUE THREAD

**Issue by BornForFever** [adobe-fonts/source-han-sans#254]

**Comment by Explorer09** [comment]
> Would you like to make a variable version of Source Han Sans?

Who does "you" in this title refer to? If it is wishing for an official variable version of the font, I think they have been working on the way now. (Look here https://github.com/adobe-fonts/variable-font-collection-test )

**Comment by BornForFever** [comment]
Oh, yes😄
