### ISSUE TITLE
Missing U+2B6AA 𫚪, U+2B695 𫚕, U+2B6AD 𫚭

### ISSUE THREAD

**Issue by BDO-CnHope** [adobe-fonts/source-han-sans#256]
### Prerequisites

* [x] If you are reporting an issue that affects glyphs for characters for a particular region or regions, did you verify that the characters are within the supported scope of the region or regions? This generally means GB 18030 or Tōngyòng Guīfàn Hànzìbiǎo (通用规范汉字表) for China, Big Five or CNS 11643 Planes 1 & 2 for Taiwan, HKSCS-2016 for Hong Kong, JIS X 0208, JIS X 0212, and JIS X 0213 for Japan, and KS X 1001 and KS X 1002 for Korea.
* [x] Did you thoroughly search the [open](https://github.com/adobe-fonts/source-han-sans/issues) and [closed](https://github.com/adobe-fonts/source-han-sans/issues?q=is%3Aissue+is%3Aclosed) issues to avoid reporting a duplicate issue?
* [x] Did you go through the [official font readme file](https://github.com/adobe-fonts/source-han-sans/raw/release/SourceHanSansReadMe.pdf) to better understand the scope of the project, to include the *Known Issues* section at the very end?

### Description

Missing U+2B6AA 𫚪, U+2B695 𫚕, U+2B6AD 𫚭

![sample](https://github.com/BDO-CnHope/issues/raw/master/images/Capture.PNG)

Thank you.
### Reference
[Unihan Database Lookup](https://www.unicode.org/charts/unihan.html)

**Comment by JPRidgeway** [comment]
The source reference for the glyphs you mentioned in GCH (Ci Hai Encyclopedia). There are more than 30'000 characters with a G-Source in Unicode that are not covered by fonts, ad these do not have a good reason to have a priority compared to others.

**Comment by BDO-CnHope** [comment]
> 
> 
> The source reference for the glyphs you mentioned in GCH (Ci Hai Encyclopedia). There are more than 30'000 characters with a G-Source in Unicode that are not covered by fonts, ad these do not have a good reason to have a priority compared to others.

Thanks for your reply. Those "special" glyphs makes me crazy...

Maybe I should try to add those glyphs by using AFDKO tools to build my own font.

**Comment by tamcy** [comment]
Note that `U+2B695 𫚕` and `U+2B6AD 𫚭` are already covered by Source Han Sans and Source Han Serif.

**Comment by BDO-CnHope** [comment]
This is weird, because those three glyphs are not display correctly in the application. It shows as a box/square(something unreadable).&nbsp;


I'm using Source Han Sans Medium, Version 2.001;hotconv 1.0.107;makeotfexe 2.5.65593

 



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Tamcy"<notifications@github.com&gt;; 
发送时间: 2020年3月27日(星期五) 晚上10:15
收件人: "adobe-fonts/source-han-sans"<source-han-sans@noreply.github.com&gt;; 
抄送: "Sasulaw"<2376032538@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [adobe-fonts/source-han-sans] Missing U+2B6AA &#x2B6AA;, U+2B695 &#x2B695;, U+2B6AD &#x2B6AD; (#256)





 
Note that U+2B695 𫚕 and U+2B6AD 𫚭 are already covered by Source Han Sans and Source Han Serif.

**Comment by JPRidgeway** [comment]
Indeed. U+2B695 and U+2B6AD are apparently TGH 3, and thus eligible for a G-Form to be incorporated. Their appearance in the font attached. U+2B6AA is not.
![image](https://user-images.githubusercontent.com/9803610/77819811-d7024900-70ee-11ea-8a59-298c708ae5a6.png)

**Comment by BDO-CnHope** [comment]
After some troubleshooting, I found the problem is because the file convert from UTF8 to UTF16 cause it not display correctly. It is not the font's problem😂

I don't have screenshot here for TC in UTF16, but TC display correctly in UTF16.
(From left to right, TC in UTF8, SC in UTF8, SC in UTF16).


![shi2](https://user-images.githubusercontent.com/36084857/77835959-5d874c80-7128-11ea-8edf-9d835ecc3ee4.png)
![yu2](https://user-images.githubusercontent.com/36084857/77835960-5d874c80-7128-11ea-973d-3138fb126b7a.png)
![lie2](https://user-images.githubusercontent.com/36084857/77835961-5e1fe300-7128-11ea-96c7-d727ff6e3c43.png)

Thanks everyone's help.
