### ISSUE TITLE
How can I install the fonts in Win 10?

### ISSUE THREAD

**Issue by AudenTang** [adobe-fonts/source-han-sans#257]
Dear developers,

I don't know how to install the font files after downloading the zip file. Please advice me.

Sincerely yours,

Auden

### Prerequisites

* [ ] If you are reporting an issue that affects glyphs for characters for a particular region or regions, did you verify that the characters are within the supported scope of the region or regions? This generally means GB 18030 or Tōngyòng Guīfàn Hànzìbiǎo (通用规范汉字表) for China, Big Five or CNS 11643 Planes 1 & 2 for Taiwan, HKSCS-2016 for Hong Kong, JIS X 0208, JIS X 0212, and JIS X 0213 for Japan, and KS X 1001 and KS X 1002 for Korea.
* [ ] Did you thoroughly search the [open](https://github.com/adobe-fonts/source-han-sans/issues) and [closed](https://github.com/adobe-fonts/source-han-sans/issues?q=is%3Aissue+is%3Aclosed) issues to avoid reporting a duplicate issue?
* [ ] Did you go through the [official font readme file](https://github.com/adobe-fonts/source-han-sans/raw/release/SourceHanSansReadMe.pdf) to better understand the scope of the project, to include the *Known Issues* section at the very end?

### Description

[Please provide here a thorough description of the issue, being sure to specify at least a Unicode code point if it affects a character or a particular glyph for a character. Including the character itself after the Unicode code point also helps, for visual reasons. Images with annotations that pinpoint the issue also help. If you are referencing standards, please keep in mind that they may have known or unknown errors. It is not necessary to provide CIDs.]

**Comment by CrotchBurnt** [comment]
Unzip the file, select them all and right click on them, install them all. Or you can just copy all files into C:\Windows\Fonts

**Comment by AudenTang** [comment]
Dear Crotch Burnt,

Thank you for your help.

Sincerely yours,

Auden
