### ISSUE TITLE
Without Dr Ken Lunde, how is the status of the project?

### ISSUE THREAD

**Issue by Marcus98T** [adobe-fonts/source-han-sans#258]
With Dr Ken Lunde no longer employed at Adobe, and thus no longer maintainer of the Source Han projects, how is the release of Source Han Sans v2.002 going to be affected?

My only answer so far as of recently is that [Source Han Serif is still on a big v2 update and will likely still be WIP in 2021](https://github.com/adobe-fonts/source-han-serif/issues/84), however, on another note, I wanted to ask if Source Han Serif v1.002 can be released in the meantime, especially with the missing JP glyph of U+54E5 哥 and U+68D7 棗. It's been a very long time since the last Source Han Serif release.

**Comment by punchcutter** [comment]
Development continues on both Source Han Sans and Source Han Serif. I'm not sure about a Serif v1.002, but I'll check.

**Comment by Marcus98T** [comment]
Thanks for the helpful reply. I'll await whether the interim release of Source Han Serif v1.002 is actually planned, although it will be quite a while.

**Comment by Marcus98T** [comment]
I'll close this issue because 5 months have passed without reply and I have reason to believe that Source Han Serif v2.000 is more likely to happen than v1.002.

**Comment by cjchapman** [comment]
@Marcus98T Sorry that we didn't get back to you sooner. Yes, we are planning to do a Source Han Serif v1.002 release.

**Comment by Marcus98T** [comment]
Thank you very much for the reply. I'm hoping it comes soon enough.

On a side note, [I opened a new issue regarding the KR glyph mapping error](https://github.com/adobe-fonts/source-han-serif/issues/88). Hopefully a fix gets into the v1.002 release.
