### ISSUE TITLE
U+21B9 (↹, LEFTWARDS ARROW TO BAR OVER RIGHTWARDS ARROW TO BAR) is incorrect

### ISSUE THREAD

**Issue by be5invis** [adobe-fonts/source-han-sans#260]
Source Han Serif mirror: https://github.com/adobe-fonts/source-han-serif/issues/86

### Description

The glyph for U+21B9 (↹, LEFTWARDS ARROW TO BAR OVER RIGHTWARDS ARROW TO BAR) is incorrect in Source Han Sans.
![image](https://user-images.githubusercontent.com/240091/79927565-086feb00-83f5-11ea-8df8-c03eb6527cdc.png)

According to the code chart, this particular character has leftward arrow on top, rightward arrow on bottom.
![image](https://user-images.githubusercontent.com/240091/79927620-32c1a880-83f5-11ea-9b0a-d309b33e657c.png)

**Comment by punchcutter** [comment]
Fixed in 2.002.
