### ISSUE TITLE
I want to extract the strokes from each Chinese character, but I don't know how to do it...

### ISSUE THREAD

**Issue by aboutboy** [adobe-fonts/source-han-sans#267]
### Prerequisites

I'm a coder, and a project need to show the strokes and strokes order of some Chinese character.
I want to know how to analyse the source data of these fonts.
Does the data includes the strokes information to help me?

### Description

I don't know how to use the source data...

Can the software that Adobe Font Development Kit for OpenType (AFDKO) help me to analyse the source data?

Thank you...

**Comment by sgalal** [comment]
Have a look at this project: https://github.com/skishore/makemeahanziEmail domain proudly hosted at migadu.com

**Comment by aboutboy** [comment]
> Have a look at this project: https://github.com/skishore/makemeahanzi

thanks very much...it helps
