### ISSUE TITLE
官方字体readme文件超链接失效

### ISSUE THREAD

**Issue by AnLazyOtter** [adobe-fonts/source-han-sans#268]
### Prerequisites

* [x] If you are reporting an issue that affects glyphs for characters for a particular region or regions, did you verify that the characters are within the supported scope of the region or regions? This generally means GB 18030 or Tōngyòng Guīfàn Hànzìbiǎo (通用规范汉字表) for China, Big Five or CNS 11643 Planes 1 & 2 for Taiwan, HKSCS-2016 for Hong Kong, JIS X 0208, JIS X 0212, and JIS X 0213 for Japan, and KS X 1001 and KS X 1002 for Korea.
* [x] Did you thoroughly search the [open](https://github.com/adobe-fonts/source-han-sans/issues) and [closed](https://github.com/adobe-fonts/source-han-sans/issues?q=is%3Aissue+is%3Aclosed) issues to avoid reporting a duplicate issue?
* [x] Did you go through the [official font readme file](https://github.com/adobe-fonts/source-han-sans/raw/release/SourceHanSansReadMe.pdf) to better understand the scope of the project, to include the *Known Issues* section at the very end?

### Description

[Please provide here a thorough description of the issue, being sure to specify at least a Unicode code point if it affects a character or a particular glyph for a character. Including the character itself after the Unicode code point also helps, for visual reasons. Images with annotations that pinpoint the issue also help. If you are referencing standards, please keep in mind that they may have known or unknown errors. It is not necessary to provide CIDs.]
问题描述：
在 [README-CN.md](https://github.com/adobe-fonts/source-han-sans/blob/master/README-CN.md) 中，有超链接指向《官方字体readme文件》，但该链接是失效的，提示找不到主机。
具体链接为：
https://github.com/adobe-fonts/source-han-sans/raw/release/SourceHanSansReadMe.pdf
这一链接同样出现在提出新issue时的文本框中。
（或者，找不到主机是因为我身处墙内？）

**Comment by punchcutter** [comment]
链接是没有问题的。原因应该是你说的身处墙内。
