### ISSUE TITLE
自愿提供 gitee 备份库为国内下载源

### ISSUE THREAD

**Issue by LYF511** [adobe-fonts/source-han-sans#271]
我在 gitee 上用“导入已有仓库”导入了此仓库，目的就是方便国内开发者下载（顺便说一句，挂在梯子也没下载到github的。。。）
仓库地址：[https://gitee.com/LYF511511/source-han-sans](https://gitee.com/LYF511511/source-han-sans)
使用方法：把下载连接的“github.com/adobe-fonts”改为“gitee.com/LYF511511”即可（由于特殊原因，readme的连接还是github）
本人承诺，**不会更改任何仓库内内容**，但 releases 由于功能限制未能同步
希望在 readme 中加入本下载源

**Comment by redchenjs** [comment]
@LYF511 本仓库码云已有官方镜像：[https://gitee.com/mirrors/source-han-sans](https://gitee.com/mirrors/source-han-sans)
