### ISSUE TITLE
Are Source Han Sans Linux redistributions legal?

### ISSUE THREAD

**Issue by kiwi0fruit** [adobe-fonts/source-han-sans#274]
The only officially available for download version of Source Han Sans is ttc files here. But according to SIL OFL:

> "Modified Version" refers to any derivative made by adding to, deleting, or substituting -- in part or in whole -- any of the components of the Original Version, by **changing formats** or by porting the Font Software to a new environment.

And if someone makes a modified version they may not use "Source" name.

Hence if someone splits ttc into separate CH, JP, ... files then they change formats and should not use "Source" name. But that exactly what they do.

**Comment by sgalal** [comment]
> The only officially available for download version of Source Han Sans is ttc files here.

No, there are other formats officially avaliable in the `release` branch.

**Comment by kiwi0fruit** [comment]
Thanks!
