### ISSUE TITLE
Missing Some Latin Glyphs in Version 2.001

### ISSUE THREAD

**Issue by lychichem** [adobe-fonts/source-han-sans#278]
### Description

Some glyphs for Latin Characters are missing. For example, U+0104 to U+010F, U+0114 to U+0119, U+0159 and more. They are uesd in some East European languages, for example, Czech. Please consider add them.
Bad display using Source Han Sans:
![image](https://user-images.githubusercontent.com/9316590/98062668-778cc880-1e89-11eb-8948-2937bdbc1818.png)
Good display using Microsoft Yahei:
![image](https://user-images.githubusercontent.com/9316590/98062843-bb7fcd80-1e89-11eb-935e-1d55de4327da.png)

**Comment by frankrolf** [comment]
You are describing a bit of a catch-22 here (and it’s a similar issue as #273).

The Source Han fonts contain 2 ** 16 glyphs, and therefore have reached the architectural limit of the OpenType spec. It simply is not possible to add more glyphs.
Since the Han fonts are focused on CJK support, the Latin set cannot be very extensive. Latin is limited to something like [AL-2](http://adobe-type-tools.github.io/adobe-latin-charsets/adobe-latin-2.html).
If you need broader support for Latin characters, use Source Han Sans in combination with [Source Sans](http://github.com/adobe-fonts/source-sans-pro/releases/latest).

**Comment by lychichem** [comment]
The problem is not the limit of glyphs contained in Source Han Sans. The developer added the glyph in Source Han Sans, so I believe at the beginning these glyphs should be included. But it's empty now. And I don't know why but Source Han Sans mistakenly tell Windows that it has these characters (In fact it displays a notdef glyph in Windows character mapper). So maybe the title of this issue should be "empty glyph for some latin characters"?

**Comment by frankrolf** [comment]
Are you saying that Source Han Sans did include these glyphs in an earlier version, but no longer?
Can you say which version of SHS includes the glyphs in question?

**Comment by lychichem** [comment]
> Are you saying that Source Han Sans did include these glyphs in an earlier version, but no longer?
> Can you say which version of SHS includes the glyphs in question?

I mean, they created a container for these glyphs, but they forget to put glyph data into it. If there is no container, Windows will use fallback fonts and can show the correct characters, but as there are containers in Source Han Sans, Windows will show bad glyph instead.

**Comment by punchcutter** [comment]
If you see .notdef for any character it means the font does not support it. There are no Latin glyphs in Source Han Sans where we "forgot to put glyph data into it". Windows Character Map shows .notdef for characters that the font does not support, not for characters that are in the font with no glyph data.

**Comment by lychichem** [comment]
> If you see .notdef for any character it means the font does not support it. There are no Latin glyphs in Source Han Sans where we "forgot to put glyph data into it". Windows Character Map shows .notdef for characters that the font does not support, not for characters that are in the font with no glyph data.

I think Windows doesn't do as what you said. Here I will use Windows character map to look for a Chinese glyph 好（U+597D）in Arial, but it show nothing as Arial doesn't support Chinese characters:
![image](https://user-images.githubusercontent.com/9316590/98192838-c81e2780-1f56-11eb-8942-320ee8ce445d.png)
So, if you really don't want to support these characters, you should delete the container of the glyph, at least for windows users, to make windows use fallback fonts.

**Comment by frankrolf** [comment]
The Windows character map is not a suitable application to deduce character support for a given font. To support this statement, I have made a test font, which only contains A, space, and .notdef (attached).

<img width="1136" alt="Screen Shot 2020-11-05 at 09 05 28" src="https://user-images.githubusercontent.com/2049645/98214269-92714280-1f46-11eb-8eb5-d97f0d336884.png">

What the character map shows:
![win_charmap1](https://user-images.githubusercontent.com/2049645/98214165-7372b080-1f46-11eb-843c-7b9baa1e1897.png)
You can see the supported A, but all other glyphs falling back to other fonts on the system.

In later areas, you will observe .notdef symbols from not one but multiple different fonts:
![win_charmap2](https://user-images.githubusercontent.com/2049645/98214332-a61ca900-1f46-11eb-847d-fa267875d071.png)

Please use other methods to substantiate missing glyph claims, such as fonttools or OTMaster.

---

Side note:

None of your original screenshots do show Source Han Sans. The site https://onlinelibrary.wiley.com/doi/abs/10.1002/anie.202005776 uses a version of Open Sans, which does not support Č and ř, and falls back to a system font, even on Mac:

<img width="529" alt="Screen Shot 2020-11-05 at 09 12 36" src="https://user-images.githubusercontent.com/2049645/98214718-280cd200-1f47-11eb-8c81-0b9da64df3bd.png">

I do not know what you mean when you specify “using Source Han Sans”, but I think it is safe to close the issue with my original statement: if you need those glyphs, please use Source (not Han) Sans, which has broader Latin support.
