### ISSUE TITLE
Apostrophe stands incorrect width

### ISSUE THREAD

**Issue by rschiang** [adobe-fonts/source-han-sans#28]
The apostrophe in Source Han Sans appears problematic on its width. It's significantly wider (almost full-width) than its latin derivative counterpart.

Here's a comparision among Helvetica, Noto Sans (Latin), Noto Sans T Chinese, and Source Han Sans TWHK:
![2014-07-20 1 56 10](https://cloud.githubusercontent.com/assets/1512231/3635390/ffead46a-0f6d-11e4-8f54-60e5082bf733.png)

Hope this could be fixed soon!

**Comment by jidanni** [comment]
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=995214
