### ISSUE TITLE
㋿ (U+32FF) is incorrect in Source Han Sans (HC, TC, SC)

### ISSUE THREAD

**Issue by a2y4** [adobe-fonts/source-han-sans#281]
### Prerequisites

* [x] If you are reporting an issue that affects glyphs for characters for a particular region or regions, did you verify that the characters are within the supported scope of the region or regions? This generally means GB 18030 or Tōngyòng Guīfàn Hànzìbiǎo (通用规范汉字表) for China, Big Five or CNS 11643 Planes 1 & 2 for Taiwan, HKSCS-2016 for Hong Kong, JIS X 0208, JIS X 0212, and JIS X 0213 for Japan, and KS X 1001 and KS X 1002 for Korea.
* [x] Did you thoroughly search the [open](https://github.com/adobe-fonts/source-han-sans/issues) and [closed](https://github.com/adobe-fonts/source-han-sans/issues?q=is%3Aissue+is%3Aclosed) issues to avoid reporting a duplicate issue?
* [x] Did you go through the [official font readme file](https://github.com/adobe-fonts/source-han-sans/raw/release/SourceHanSansReadMe.pdf) to better understand the scope of the project, to include the *Known Issues* section at the very end?

### Description

<img width="1024" alt="Reiwa in Source Han Sans" src="https://user-images.githubusercontent.com/53612225/101247410-d54c5300-375c-11eb-9aec-5daa906715f4.png">

㋿ (U+32FF) isn't incorrect in Source Han Sans (HC, TC, SC).

㋿ is ligature of 令(U+4EE4) and 和 (U+548C).

Therefore, ㋿ in Chinese looks like this.

![Reiwa in Chinese](https://user-images.githubusercontent.com/53612225/101256736-d1233400-3762-11eb-9ce8-308b61200434.png) ![Reiwa in Chinese](https://user-images.githubusercontent.com/53612225/101256720-d08a9d80-3762-11eb-98ba-078c16700fcf.png)

**Comment by c933103** [comment]
Is it really expected for the character to be renedered as Chinese, even in Chinese environment?

**Comment by jungshik** [comment]
U+32FF is for the Japanese era. Using multiple glyph slot (note that there is 64k limit and there are not many slots left) for U+32FF is not a wise use of the limited available slots. 

This is WAI.

**Comment by davelab6** [comment]
Oops, I thought for a second this was a Noto CJK repo. I suggest someone at Adobe acknowledge and close the issue :)
