### ISSUE TITLE
Simplified Chinese "袱"

### ISSUE THREAD

**Issue by Scratchbin** [adobe-fonts/source-han-sans#287]
Wrong component. The one of its left should be "衤", instead of "礻".
(Unknown version, displayed on my Android.)

**Comment by punchcutter** [comment]
That must be an old version of the font so sounds like an old Android version. The latest version has 衤
<img width="128" alt="88B1" src="https://user-images.githubusercontent.com/11257204/109151653-cbf7e300-77ad-11eb-81c4-d31223e2d477.png">
