### ISSUE TITLE
Problems downloading the huge ZIP for the full release branch

### ISSUE THREAD

**Issue by SilSinn9801** [adobe-fonts/source-han-sans#294]
I don’t know if this is the correct channel for reporting this kind of problem below or if I should forward it to some other place (because it’s more of a problem external to the project itself, but I can’t determine if it’s a GitHub issue, a browser issue, or an ISP timeout issue):

I am having problems downloading the full ZIP archive for the full release branch of this project, which seems to measure way beyond 2 GiB. Even if I do nothing else on my computer (I close all background online apps like Discord) & refrain from using other Internet-connected devices (smartphone, Roku, etc.) so as to have all the bandwidth available for the computer browser alone, the **source-han-sans-release.zip** download stops short of 2 GiB (sometimes it ends at 1.91 GiB, other times it cuts off at 1.95 GiB, & most other times it stops somewhere between), & the resulting incomplete ZIP
① opens on 7Zip but fails to extract anything from the SuperOTC & subsequent subfolders within the ZIP contents:
![source-han-sans-release_problem1](https://user-images.githubusercontent.com/50897778/114252085-8f550500-9971-11eb-8e2e-b50d59cd4395.png)
![source-han-sans-release_problem2](https://user-images.githubusercontent.com/50897778/114252086-8fed9b80-9971-11eb-9df8-cd49e545cd84.png)
② refuses to open on both Windows Explorer & WinRAR:
![source-han-sans-release_problem3](https://user-images.githubusercontent.com/50897778/114252087-8fed9b80-9971-11eb-9ec3-23404f2c41a7.png)
![source-han-sans-release_problem4](https://user-images.githubusercontent.com/50897778/114252088-90863200-9971-11eb-8490-fa3c5e38152e.png)
I don’t know if it’s an issue with the GitHub ZIP-over-HTTPS delivery system, an issue with my web browser (I tried both Microsoft Edge [the Chromium-based one] & the 64-bit version of Internet Explorer 11 on Windows 10; for the download to start on IE11, I had to right-click-&-copy the download link address from Edge & paste it onto the IE11 address bar because the GitHub UI buttons don’t work under IE), or an issue with my ISP’s bandwidth (my internet averages around 14–15 Mbps for downloads) which forces a time-out.
I would like to ask whether other people here have the same problem as I have or if any people here have instead had any success downloading the release-branch ZIP & under what conditions (including browser type & ISP bandwidth).

**Comment by punchcutter** [comment]
Sorry about that. I would guess this is because zip files over 2GB have historically been problematic. With variable fonts added the release got bigger so that isn't ideal. We should probably rethink the release setup.

**Comment by punchcutter** [comment]
The new release strategy splits the assets into two parts to hopefully help with this. If you go to https://github.com/adobe-fonts/source-han-sans/releases/tag/2.004R you can click on Part 1 (All fonts except Variable) and Part 2 (Variable fonts only). If you don't actually need everything you can select from the attached assets or use the download guide [here](https://github.com/adobe-fonts/source-han-sans/tree/release).
