### ISSUE TITLE
Building VF source files

### ISSUE THREAD

**Issue by NightFurySL2001** [adobe-fonts/source-han-sans#297]
I would like to build and interpolate the font files myself and would like to see how to build them. There are a few questions currently:

1. There are no build commands in `COMMANDS.txt`.
2. The VF source provided only seems to be so:

| Latin style | Available VF weight | Available set | 
| ----------- | --------------------- | -------------- | 
| Proportional width | Extralight, Heavy | Full CJK + Local subset | 
| Fixed width | Regular, Bold | Local subset | 

Are there no intermediate masters for proportional widths?

**Comment by punchcutter** [comment]
`COMMANDS.txt` says "Command line for building Variable Fonts will be added soon" 

Those are the only masters, but you have Fixed width listed as "Local subset" when it's Full CJK.

**Comment by NightFurySL2001** [comment]
Ok got it, thank you.

**Comment by NightFurySL2001** [comment]
@punchcutter May I ask if the font is interpolated linearly or is there any intermediate instances that are not in a linear form?

**Comment by punchcutter** [comment]
There are only two masters and no intermediates. There is mapping, though.
0 -> 250
160 -> 300
320 -> 350
390 -> 400
560 -> 500
780 -> 700
1000 -> 900

**Comment by tamcy** [comment]
For those who can't wait to try building the VF font instance themselves, here are the **unofficial** instructions.
1. Enter the root directory of the `master` branch.
2. Create a new `build` directory and `cd` into it.
3. In this directory, create a new `SourceHanSansHCVF.designspace` file with the following content:

```
<?xml version="1.0" encoding="utf-8"?>
<designspace format="3">
    <axes>
        <axis default="250.0" maximum="900.0" minimum="250.0" name="weight" tag="wght">
                <map input="250" output="0" />   <!-- ExtraLight -->
                <map input="300" output="160" /> <!-- Light -->
                <map input="350" output="320" /> <!-- Normal -->
                <map input="400" output="390" /> <!-- Regular -->
                <map input="500" output="560" /> <!-- Medium -->
                <map input="700" output="780" /> <!-- Bold -->
                <map input="900" output="1000" /><!-- Heavy -->
        </axis>
    </axes>
    <sources>
        <source filename="SourceHanSansHCVF-ExtraLight-Master.ufo" name="master_0">
            <lib copy="1" />
            <groups copy="1" />
            <info copy="1" />
            <location>
                <dimension name="weight" xvalue="0" />
            </location>
        </source>
        <source filename="SourceHanSansHCVF-Heavy-Master.ufo" name="master_2">
            <location>
                <dimension name="weight" xvalue="1000" />
            </location>
        </source>
    </sources>
    <instances>
        <instance familyname="Source Han Sans HC VF" filename="../Instances/ExtraLight/font.ufo" postscriptfontname="SourceHanSansHCVF-ExtraLight" stylename="ExtraLight">
            <location>
                <dimension name="weight" xvalue="0" />
            </location>
            <kerning />
            <info />
        </instance>
        <instance familyname="Source Han Sans HC VF" filename="../Instances/Light/font.ufo" postscriptfontname="SourceHanSansHCVF-Light" stylename="Light">
            <location>
                <dimension name="weight" xvalue="160" />
            </location>
            <kerning />
            <info />
        </instance>
        <instance familyname="Source Han Sans HC VF" filename="../Instances/Normal/font.ufo" postscriptfontname="SourceHanSansHCVF-Normal" stylename="Normal">
            <location>
                <dimension name="weight" xvalue="320" />
            </location>
            <kerning />
            <info />
        </instance>
        <instance familyname="Source Han Sans HC VF" filename="../Instances/Regular/font.ufo" postscriptfontname="SourceHanSansHCVF-Regular" stylename="Regular">
            <location>
                <dimension name="weight" xvalue="390" />
            </location>
            <kerning />
            <info />
        </instance>
        <instance familyname="Source Han Sans HC VF" filename="../Instances/Medium/font.ufo" postscriptfontname="SourceHanSansHCVF-Medium" stylename="Medium">
            <location>
                <dimension name="weight" xvalue="560" />
            </location>
            <kerning />
            <info />
        </instance>
        <instance familyname="Source Han Sans HC VF" filename="../Instances/Bold/font.ufo" postscriptfontname="SourceHanSansHCVF-Bold" stylename="Bold">
            <location>
                <dimension name="weight" xvalue="780" />
            </location>
            <kerning />
            <info />
        </instance>
        <instance familyname="Source Han Sans HC VF" filename="../Instances/Heavy/font.ufo" postscriptfontname="SourceHanSansHCVF-Heavy" stylename="Heavy">
            <location>
                <dimension name="weight" xvalue="1000" />
            </location>
            <kerning />
            <info />
        </instance>
    </instances>
</designspace>
```

4. Run the following commands, which builds the VF instance of the Traditional Chinese (Hong Kong) variant (mind the directory separator, I am using Windows):

```
makeotf -f ..\ExtraLight\OTC\VF\cidfont.VF.HC.unhinted -omitMacNames -ff ..\ExtraLight\OTC\VF\features.VF.HC -fi ..\ExtraLight\OTC\cidfontinfo.OTC.HC -mf ..\FontMenuNameDB.VF -r -nS -cs 2 -ch ..\UniSourceHanSansHK-UTF32-H -ci ..\SourceHanSans_HK_sequences.txt -o SourceHanSansHCVF-ExtraLight-Master.otf

makeotf -f ..\Heavy\OTC\VF\cidfont.VF.HC.unhinted -omitMacNames -ff ..\Heavy\OTC\VF\features.VF.HC -fi ..\Heavy\OTC\cidfontinfo.OTC.HC -mf ..\FontMenuNameDB.VF -r -nS -cs 2 -ch ..\UniSourceHanSansHK-UTF32-H -ci ..\SourceHanSans_HK_sequences.txt -o SourceHanSansHCVF-Heavy-Master.otf

buildcff2vf -c -d SourceHanSansHCVF.designspace
```

I didn't come up with the above instructions by myself, but by referring to the build commands in this and the [Source Sans 3](https://github.com/adobe-fonts/source-sans) repositories, which are very helpful (thanks!). The `designspace` file was crafted with reference to the comment above.

**Comment by punchcutter** [comment]
Thanks @tamcy. I haven't had the chance to put all this together yet. The designspace you made is basically the same as the original except I have `familyname="SourceHanSansHC"` instead of `familyname="Source Han Sans HC VF"`

**Comment by tamcy** [comment]
@punchcutter Thank you! I have updated my comment accordingly.

**Comment by NightFurySL2001** [comment]
@tamcy Thank you for your information! However, according to the instructions (and in the .designspace file), the file required is .ufo and not .otf. Converting with FontForge (and most other font editing programs) will crash easily. How do I convert the file to ufo?

**Comment by punchcutter** [comment]
@NightFurySL2001 You don't need UFOs. `buildcff2vf` expects UFOs first and then it makes OTFs from those and uses those. If you already have the OTFs like we do in this case you can just change those names to `.otf` and it will work. The actual designspace file I used to build the variable fonts here has `.otf` for the paths, not `.ufo`

**Comment by tamcy** [comment]
@NightFurySL2001 You don't need to. `buildcff2vf` (or the underlying varLib) will use the `.otf` masters when available.

**Comment by punchcutter** [comment]
I should mention one reason I haven't put all of this up yet is because it's a little more complicated. One thing is that the current variable fonts use feature variations for `vpal`/`palt` to match the values in the static fonts. That can't be done easily with current tools (yet...that's also in progress) so I built that part manually and add it with `ttx` during the build process.

**Comment by NightFurySL2001** [comment]
Oooh.... I finally made the file successfully. Thank you for both your patience.

**Comment by jimmymasaru** [comment]
Hi @tamcy , would you please double check whether it's 390 for Regular? Per this [ReadMe](https://github.com/adobe-fonts/source-han-sans/blob/release/SourceHanSansReadMe.pdf) file, it should be 420.

**Comment by jimmymasaru** [comment]
Never mind @tamcy , I saw the comments earlier from @punchcutter .

**Comment by punchcutter** [comment]
Ah, thanks for catching that. I need to update the PDF. The whole build process changed from when that was written, but I overlooked those values in the last PDF update.

**Comment by NightFurySL2001** [comment]
@punchcutter since the build result is CFF2 which can crash Windows currently, what is the method used to build the font into glyf/TTF?

**Comment by punchcutter** [comment]
Right now the TTFs are built by passing UFOs to `ufo2ft.compileVariableTTF`. I haven't updated the repos yet for Source Han Sans or Serif because the whole build process is also making use of CID-keyed UFOs and there are still some bugs to work out in the tools implementation before that's ready for a release. It's possible to convert the two master OTFs to UFOs and then run `fontmake` on the designspace to build a variable TTF, but for 65,535 glyphs you will probably run into the issue of post table 2.0 vs 3.0. I pass in an outlineCompiler here to make sure that part works. A short version of it all is 

```
import ufoLib2
import ufo2ft
from ufo2ft.fontInfoData import getAttrWithFallback
from fontTools.designspaceLib import DesignSpaceDocument

def open_ufo(path):
    """
    Use the same designspace for both buildcff2vf and ufo2ft
    buildcff2vf expects master OTF source files, but ufo2ft will use UFOs here
    to build TTFs
    """
    path = path.replace('.otf', '.ufo')
    return ufoLib2.Font.open(path)

class CJKOutlineTTFCompiler(ufo2ft.outlineCompiler.OutlineTTFCompiler):

    @staticmethod
    def makeMissingRequiredGlyphs(font, glyphSet, sfntVersion, notdefGlyph=None):
        # Make sure we don't add .notdef
        return

    def setupTable_post(self):
        # post table must be format 3
        if "post" not in self.tables:
            return

        self.otf["post"] = post = newTable("post")
        font = self.ufo
        post.formatType = 3.0
        # italic angle
        italicAngle = getAttrWithFallback(font.info, "italicAngle")
        post.italicAngle = italicAngle
        # underline
        underlinePosition = getAttrWithFallback(
            font.info, "postscriptUnderlinePosition"
        )
        post.underlinePosition = otRound(underlinePosition)
        underlineThickness = getAttrWithFallback(
            font.info, "postscriptUnderlineThickness"
        )
        post.underlineThickness = otRound(underlineThickness)
        post.isFixedPitch = getAttrWithFallback(font.info, "postscriptIsFixedPitch")
        # misc
        post.minMemType42 = 0
        post.maxMemType42 = 0
        post.minMemType1 = 0
        post.maxMemType1 = 0

designspace = DesignSpaceDocument.fromfile(ds_path)
designspace.loadSourceFonts(opener=open_ufo)

font = ufo2ft.compileVariableTTF(
        designspace,
        outlineCompilerClass=CJKOutlineTTFCompiler,
        inplace=True,
    )

font.save(output_path)
```

That won't run as is so you'd have to add the paths and I might have missed something, but that's the basic idea. 
There are also other ways to do this, but for the moment this works.

**Comment by NightFurySL2001** [comment]
@punchcutter  @tamcy How do you prepare the intermediate weights (Light/Normal/Regular/Medium/Bold) source file? Both `buildcff2vf` and `ufo2ft` code doesnt seem to generate the intermediate weights file when parsing the `designspace` file.

**Comment by punchcutter** [comment]
The current intermediate weights were done with `makeinstancesufo`, but that's using the temp UFO masters that I make first. It's possible to do in other ways, but that was a good way to do it for this project. The tools to deal with CID-keyed UFO files aren't quite ready for release yet, but that's what I did internally. Basically CID-keyed Type 1 -> UFO -> makeinstancesufo and then take all of those UFOs and convert back to CID-keyed Type 1 before running makeotf. Most of the tools like makeinstancesufo are built more around a UFO workflow so it's easy to pipe UFOs into all of these tools, but not as easy to use something like a Type 1 CID-keyed file. Of course there's more going on here and more I could write, but for your main question it's `makeinstancesufo`.
