### ISSUE TITLE
Gridfit

### ISSUE THREAD

**Issue by be5invis** [adobe-fonts/source-han-sans#3]
Gridfitted TTFs are extremely useful for low-density display devices and web use, however there is still NO CJK font which is well fitted. Gridfits of MSYH often make characters ragged, due to lack of blue zone alignments.

Manually adding gridfits is unacceptable due to the quantity of characters, therefore is it possible to create an automatic gridfit generation algorithm which generates gridfits for thousands of characters? Adding it into `ttfautohint` might be a great help because people may reuse Source Han Sans in their own composite font and re-generate gridfits.

**Comment by be5invis** [comment]
It has been THREE years...
![image](https://cloud.githubusercontent.com/assets/240091/26356708/7e2039b4-3fff-11e7-995c-b6f4b287c291.png)

**Comment by be5invis** [comment]
![image](https://cloud.githubusercontent.com/assets/240091/26356981/7d000158-4000-11e7-8a9d-bb765a3e3ee5.png)

**Comment by be5invis** [comment]
![image](https://cloud.githubusercontent.com/assets/240091/26357051/af46c69c-4000-11e7-9cba-0a4e6997c060.png)

**Comment by be5invis** [comment]
“Technology is what turns Impossible into Possible.”
![image](https://user-images.githubusercontent.com/240091/28519543-9c145868-709e-11e7-8dd8-9c26b350bd81.png)

**Comment by hfhchan** [comment]
Would these hinting instructions be implemented in Microsoft CJK fonts?

(Although this is not related at all the Source Han Sans, I'm quite sure Source Han Sans played a good role in stirring competition.)

**Comment by be5invis** [comment]
@hfhchan I cannot tell you the real products but, YES, we are using IDH in MS fonts.

https://github.com/be5invis/source-han-sans-ttf/releases ← Hinted version of SHS

**Comment by behdad** [comment]
> https://github.com/be5invis/source-han-sans-ttf/releases ← Hinted version of SHS

Do you have comparisons of the CFF version with Adobe hinter, and TTF version with yours?

**Comment by be5invis** [comment]
@behdad CFF definitely cannot do stroke reduction for very small size (~12ppem), because its mechanism simply cannot let you to assign a point's coordinates.
And in TTF we can.

**Comment by be5invis** [comment]
@lemzwerg @behdad 
Another interesting solution for hinting is that, we can grab the **intermediate contour** from the Adobe rasterizer embedded in Freetype, as described in this article: https://blog.typekit.com/2013/05/01/adobe-contributes-cff-rasterizer-to-freetype/
This image below revealed that Adobe has some very interesting mechanism to deal with complex PS hints:
![](https://typekit.files.wordpress.com/2013/05/kozgo10-900.png)
We can have this workflow:

```
CFF outline --> Adobe rasterizer --> CFF outline under ---.
      |                                a certain PPEM     }---> TT hints
      `-------> Quadratic outline ------------------------'
```

**Comment by lemzwerg** [comment]
Nice idea!  Maybe you can tweak ttfautohint to handle this – I still have doubts whether conversion of CFF to TTF is useful, but I agree that there might be situations where a TTF must be used.

**Comment by be5invis** [comment]
@lemzwerg In TT at least you have more control.
Here is the diagram:

```
CFF --+-> Semantic hints (stems, blues, etc) --> Size-independent TT instr -.
 |    `-> “Hinted” outline under each PPEM   --> Size-dependent TT instr   -+--> TTF
 `------> Quadratic outline ------------------------------------------------’
```

The size-independent part would be “semantic” hints, while size-dependent part would be a lot of deltas applied to it. For simple glyphs SD part is very little, and for dense glyphs SD part would be significant.
