### ISSUE TITLE
Error with AI0 source file

### ISSUE THREAD

**Issue by NightFurySL2001** [adobe-fonts/source-han-sans#302]
The AI0 source file (https://raw.githubusercontent.com/adobe-fonts/source-han-sans/release/Resources/AI0-SourceHanSans) has a problem at line 62068 (ID 62067):

`62067	Generic     Reserved    reserved05`

The space between "Generic" and "Reserved", "Reserved" and "reserved05" is spaces (U+0020) instead of tab (U+0009) which caused problem when trying to parse it with CSV reader and tab as delimiter.

**Comment by punchcutter** [comment]
Thanks, I updated the file. I won't do a whole new release just for that so downloading the packaged release files won't have it until the next update, but the file linked above should be ok.
