### ISSUE TITLE
一些關於思源黑體的建議（2021年8月4日）

### ISSUE THREAD

**Issue by Guest-615695028** [adobe-fonts/source-han-sans#305]
### Prerequisites

* [x] If you are reporting an issue that affects glyphs for characters for a particular region or regions, did you verify that the characters are within the supported scope of the region or regions? This generally means CJK Unified Ideographs, CJK Unified Ideographs Extended A-F, CJK Compatibility Ideographs and ~ Supplement.
* [x] Did you thoroughly search the [open](https://github.com/adobe-fonts/source-han-sans/issues) and [closed](https://github.com/adobe-fonts/source-han-sans/issues?q=is%3Aissue+is%3Aclosed) issues to avoid reporting a duplicate issue?
* [x] Did you go through the [official font readme file](https://github.com/adobe-fonts/source-han-sans/raw/release/SourceHanSansReadMe.pdf) to better understand the scope of the project, to include the *Known Issues* section at the very end?

### Description

[Please provide here a thorough description of the issue, being sure to specify at least a Unicode code point if it affects a character or a particular glyph for a character. Including the character itself after the Unicode code point also helps, for visual reasons. Images with annotations that pinpoint the issue also help. If you are referencing standards, please keep in mind that they may have known or unknown errors. It is not necessary to provide CIDs.]

**Comment by Guest-615695028** [comment]
《傳承字形部件檢校表》云：『Google與 Adobe 合製的「思源黑體」裏，製作者竟把「𠆢」形頂部
出頭與否視作地區分別，例如上述「金、合、令」等例子，日版、韓版本來不
出頭，但香港版、臺灣版、簡體版不但故意改成出頭，還要出得甚爲明顯。這
既影響字形平衡觀感，也無字理字源之據，絕不可取。』

**Comment by oscarsun72** [comment]
菩薩慈悲：請多禮聘、請教一些真正有名有姓專家學者的意見吧。不要都是一些化名、暱稱的無名氏、沒品牌、不負責任，像路邊攤、沒實體店面、到時無法追究的關起門來自己幹、閉門造車。且參與者當如功德碑、四庫館臣題名職官一樣，具名負責以示後世才好。
　　末學業師臺大退休教授黃沛榮先生即是這方面的專家之一。末學孫守真（字任真，中國文化大學中文博士）也略懂一二。沒有文字學、漢字學的基礎的，千萬不要師心自用才好。現在電腦字型猶如當年秦始皇書同文統一文字，影響之大，非同小可，已不宜再當作鄉民、網友們的次文化、暗地裡的地下活動來看待了。感恩感恩　南無阿彌陀佛

**Comment by USHI-J** [comment]
> If you are reporting an issue that affects glyphs for characters for a particular region or regions, **did you verify that the characters are within the supported scope of the region or regions? This generally means GB 18030 or Table of General Standard Han Characters (通用规范汉字表) for Mainland China**, Big Five or CNS 11643 Planes 1 & 2 for Taiwan, HKSCS-2016 for Hong Kong, JIS X 0208, JIS X 0212, and JIS X 0213 for Japan, and KS X 1001 and KS X 1002 for Korea.

**Comment by Guest-615695028** [comment]
> 菩薩慈悲：請多禮聘、請教一些真正有名有姓有頭有臉專家學者的意見吧。不要都是一些化名、暱稱的無名氏、沒品牌、不負責任，像路邊攤、沒實體店面、到時無法追究的關起門來自己幹、閉門造車、師心自用的伙伴。且參與者當如功德碑、四庫館臣題名職官一樣，具名負責以示後世才好。
> 　　末學業師臺大退休教授黃沛榮先生即是這方面的專家之一。末學孫守真（字任真，中國文化大學中文博士）也略懂一二。沒有文字學、漢字學的基礎的，千萬不要師心自用才好。現在電腦字型猶如當年秦始皇書同文統一文字，影響之大，非同小可，已不宜再當作鄉民、網友們的次文化、暗地裡的地下活動來看待了。感恩感恩　南無阿彌陀佛

吾所師者皆真人也，非子所謂閉門造車、師心自用者。思源黑體、宋體，字庫已滿，凡陸萬伍仟伍佰叁拾陸形，不減不能增新，不損不能益民。

**Comment by Guest-615695028** [comment]
>> USHI-J requires us to verify that the characters are within the supported scope of the region or regions: **GB 18030 or Table of General Standard Han Characters (通用规范汉字表) for Mainland China, Big Five or CNS 11643 Planes 1 & 2 for Taiwan, HKSCS-2016 for Hong Kong, JIS X 0208, JIS X 0212, and JIS X 0213 for Japan, and KS X 1001 and KS X 1002 for Korea.**

Then we shall extend the supported range to U+3400-4DBF, 4E00-9FFF, 20000-2FFFC.

**Comment by c933103** [comment]
> 1. [ ] 金、合、令等字中，人字頭應全用平頂如日韓版形態。
> 《傳承字形部件檢校表》云：「思源黑體」裏，製作者竟把「𠆢」形頂部出頭與否視作地區分別，例如金、合、令，日、韓版不出頭，但陸港臺版不但故意改成出頭，還要出得甚爲明顯。此出頭既影響字形平衡觀感，又無字理字源之據，絕不可取。
> 2. [ ] [過細的字形差異，如瀀、煗、燚之中日版差異，取較（最）美觀者。](http://coder.zoomquiet.top/data/20170421215148/index.html)
> 3. [ ] 廢香港版、HW諸版，香港已用[昭源宋體](https://github.com/chiron-sans)代之。
> 4. [ ] 日韓版作捺畫的，陸臺版不作長點。
> 5. [ ] [印刷體美學](https://zhuanlan.zhihu.com/p/26393056)：缶、山、表、艮、云、至、女等字或部件中竪橫、竪挑、撇橫、撇挑、撇點等折筆，一如日韓版形態。
> 6. [ ] 愿、感部件只用上下結構形態，如日韓版。
> 7. [ ] 亠、广、亡、宀、文、方、疒、立、衣等字或部件，首筆用直點（亦往字第四筆）；亥、言、旁、帝等字或部件，及立部件直接位於另一部件上方時，首筆用橫，陸版用點。
> 8. [ ] 雨部件居上，末四筆作四橫，否則做四點。
> 9. [ ] 辱部件亦只用上下結構形態。
> 10. [ ] 以上各條亦適用於思源宋體。
> 11. [ ] 按以上各條所示並結合陸臺日韓習慣寫法補全中日韓統一表意文字擴展B至F區、中日韓兼容表意文字增補區入思源黑（宋）體ExtB（Source Han Sans/Serif SC/TC/J/K-ExtB）；原有字庫移除第二輔助平面内所有字元。
> 12. [ ] 增設思源黑（宋）體舊字形版（Source Han Sans/Serif, Source Han Sans/Serif ExtB），不帶地方識別標識。

就第3項，這牽涉到思源字體目的問題。按個人理解，思源字體的目的是為了創造適合不同地區使用並風格相同的字體，從而方便互相組合使用。非官方支持，並在其他名義下分發的字體，並不能取代這角色。
就第12項，我認為要達到這目的，首要是讓電腦系統能區別並調用舊字形，Adobe和Google及其他造字廠商才會有動力去支持。為了讓電腦系統區別和調用舊字形，個人認為其中一個可行方案，是在ISO 15924 文字系統代號國際標準中，像繁體中文=Hant、簡體中文=Hans一般，加入代表舊字形文字系統的代號。但個人在漢字方面並非專家，無力代表全球漢字使用者向[有關當局](https://unicode.org/iso15924/)提供相關資料以申請相關代號。如果這裡有更適任者的話，希望能代為提出相關申請。

**Comment by Guest-615695028** [comment]
> > 1. [ ]  金、合、令等字中，人字頭應全用平頂如日韓版形態。
> >    《傳承字形部件檢校表》云：「思源黑體」裏，製作者竟把「𠆢」形頂部出頭與否視作地區分別，例如金、合、令，日、韓版不出頭，但陸港臺版不但故意改成出頭，還要出得甚爲明顯。此出頭既影響字形平衡觀感，又無字理字源之據，絕不可取。
> > 2. [ ]  [過細的字形差異，如瀀、煗、燚之中日版差異，取較（最）美觀者。](http://coder.zoomquiet.top/data/20170421215148/index.html)
> > 3. [ ]  廢香港版、HW諸版，香港已用[昭源宋體](https://github.com/chiron-sans)代之。
> > 4. [ ]  日韓版作捺畫的，陸臺版不作長點。
> > 5. [ ]  [印刷體美學](https://zhuanlan.zhihu.com/p/26393056)：缶、山、表、艮、云、至、女等字或部件中竪橫、竪挑、撇橫、撇挑、撇點等折筆，一如日韓版形態。
> > 6. [ ]  愿、感部件只用上下結構形態，如日韓版。
> > 7. [ ]  亠、广、亡、宀、文、方、疒、立、衣等字或部件，首筆用直點（亦往字第四筆）；亥、言、旁、帝等字或部件，及立部件直接位於另一部件上方時，首筆用橫，陸版用點。
> > 8. [ ]  雨部件居上，末四筆作四橫，否則做四點。
> > 9. [ ]  辱部件亦只用上下結構形態。
> > 10. [ ]  以上各條亦適用於思源宋體。
> > 11. [ ]  按以上各條所示並結合陸臺日韓習慣寫法補全中日韓統一表意文字擴展B至F區、中日韓兼容表意文字增補區入思源黑（宋）體ExtB（Source Han Sans/Serif SC/TC/J/K-ExtB）；原有字庫移除第二輔助平面内所有字元。
> > 12. [ ]  增設思源黑（宋）體舊字形版（Source Han Sans/Serif, Source Han Sans/Serif ExtB），不帶地方識別標識。
> 
> 就第3項，這牽涉到思源字體目的問題。按個人理解，思源字體的目的是為了創造適合不同地區使用並風格相同的字體，從而方便互相組合使用。非官方支持，並在其他名義下分發的字體，並不能取代這角色。
> 
> 就第12項，我認為要達到這目的，首要是讓電腦系統能區別並調用舊字形，Adobe和Google及其他造字廠商才會有動力去支持。為了讓電腦系統區別和調用舊字形，個人認為其中一個可行方案，是在ISO 15924 文字系統代號國際標準中，像繁體中文=Hant、簡體中文=Hans一般，加入代表舊字形文字系統的代號。但個人在漢字方面並非專家，無力代表全球漢字使用者向[有關當局](https://unicode.org/iso15924/)提供相關資料以申請相關代號。如果這裡有更適任者的話，希望能代為提出相關申請。

舊字形文字系統屬於漢字（Hani）、繁體中文（Hant），參考《傳承字形部件檢校表》《傳承字形筆畫表》《傳承字型推薦形體表》。
[table_of_recom_inherited_glyphs-1.03.pdf](https://github.com/adobe-fonts/source-han-sans/files/7004077/table_of_recom_inherited_glyphs-1.03.pdf)

[stroke_of_inherited_glyphs-1.26.pdf](https://github.com/adobe-fonts/source-han-sans/files/7004075/stroke_of_inherited_glyphs-1.26.pdf)

[component_of_recom_inherited_glyphs-1.35.pdf](https://github.com/adobe-fonts/source-han-sans/files/7004074/component_of_recom_inherited_glyphs-1.35.pdf)

**Comment by c933103** [comment]
> > > 1. [ ]  金、合、令等字中，人字頭應全用平頂如日韓版形態。
> > >    《傳承字形部件檢校表》云：「思源黑體」裏，製作者竟把「𠆢」形頂部出頭與否視作地區分別，例如金、合、令，日、韓版不出頭，但陸港臺版不但故意改成出頭，還要出得甚爲明顯。此出頭既影響字形平衡觀感，又無字理字源之據，絕不可取。
> > > 2. [ ]  [過細的字形差異，如瀀、煗、燚之中日版差異，取較（最）美觀者。](http://coder.zoomquiet.top/data/20170421215148/index.html)
> > > 3. [ ]  廢香港版、HW諸版，香港已用[昭源宋體](https://github.com/chiron-sans)代之。
> > > 4. [ ]  日韓版作捺畫的，陸臺版不作長點。
> > > 5. [ ]  [印刷體美學](https://zhuanlan.zhihu.com/p/26393056)：缶、山、表、艮、云、至、女等字或部件中竪橫、竪挑、撇橫、撇挑、撇點等折筆，一如日韓版形態。
> > > 6. [ ]  愿、感部件只用上下結構形態，如日韓版。
> > > 7. [ ]  亠、广、亡、宀、文、方、疒、立、衣等字或部件，首筆用直點（亦往字第四筆）；亥、言、旁、帝等字或部件，及立部件直接位於另一部件上方時，首筆用橫，陸版用點。
> > > 8. [ ]  雨部件居上，末四筆作四橫，否則做四點。
> > > 9. [ ]  辱部件亦只用上下結構形態。
> > > 10. [ ]  以上各條亦適用於思源宋體。
> > > 11. [ ]  按以上各條所示並結合陸臺日韓習慣寫法補全中日韓統一表意文字擴展B至F區、中日韓兼容表意文字增補區入思源黑（宋）體ExtB（Source Han Sans/Serif SC/TC/J/K-ExtB）；原有字庫移除第二輔助平面内所有字元。
> > > 12. [ ]  增設思源黑（宋）體舊字形版（Source Han Sans/Serif, Source Han Sans/Serif ExtB），不帶地方識別標識。
> > 
> > 就第3項，這牽涉到思源字體目的問題。按個人理解，思源字體的目的是為了創造適合不同地區使用並風格相同的字體，從而方便互相組合使用。非官方支持，並在其他名義下分發的字體，並不能取代這角色。
> > 
> > 就第12項，我認為要達到這目的，首要是讓電腦系統能區別並調用舊字形，Adobe和Google及其他造字廠商才會有動力去支持。為了讓電腦系統區別和調用舊字形，個人認為其中一個可行方案，是在ISO 15924 文字系統代號國際標準中，像繁體中文=Hant、簡體中文=Hans一般，加入代表舊字形文字系統的代號。但個人在漢字方面並非專家，無力代表全球漢字使用者向[有關當局](https://unicode.org/iso15924/)提供相關資料以申請相關代號。如果這裡有更適任者的話，希望能代為提出相關申請。
> 
> 舊字形文字系統屬於漢字（Hani）、繁體中文（Hant），參考《傳承字形部件檢校表》《傳承字形筆畫表》《傳承字型推薦形體表》。
> [table_of_recom_inherited_glyphs-1.03.pdf](https://github.com/adobe-fonts/source-han-sans/files/7004077/table_of_recom_inherited_glyphs-1.03.pdf)
> 
> [stroke_of_inherited_glyphs-1.26.pdf](https://github.com/adobe-fonts/source-han-sans/files/7004075/stroke_of_inherited_glyphs-1.26.pdf)
> 
> [component_of_recom_inherited_glyphs-1.35.pdf](https://github.com/adobe-fonts/source-han-sans/files/7004074/component_of_recom_inherited_glyphs-1.35.pdf)
> 

就像Hant屬於Hani但依然有自己的代碼一樣，為方便使用舊字型而申請新代碼使用應該沒問題？

**Comment by hfhchan** [comment]
If you add a new script code, then you also need to define a way to activate it through OpenType.  OpenType currently uses hani with ZHH, ZHT and ZHTM, hant and hans are not used.

**Comment by c933103** [comment]
In other words, it is also necessary to apply for a "Language system tags"
in OpenType Layout Tag Registry to Microsoft
https://docs.microsoft.com/en-us/typography/opentype/spec/languagetags

But how to file such application?

在 2021年8月18日週三 17:22，Henry Chan ***@***.***> 寫道：

**Comment by Marcus98T** [comment]
I see most of these posts are a call to return to traditional orthographic forms of JP and KR for TC, but [they already discussed this before](https://github.com/adobe-fonts/source-han-sans/issues/6), and as much as I don't like 楷化 too, Adobe's project scope is to comply with national government standards and they already said it's way beyond this. I recommend this issue be closed.

Unless there's something else I missed, but isn't Source Han Sans also supporting OpenType locale already?

**Comment by Guest-615695028** [comment]
OK. See [Adobe Ming](https://fonts.adobe.com/fonts/adobe-ming) and [Adobe Fan Heiti](https://fonts.adobe.com/fonts/adobe-fan-heiti) which helps.
