### ISSUE TITLE
The character bounding box is too large

### ISSUE THREAD

**Issue by LeoWang2007** [adobe-fonts/source-han-sans#323]
### Prerequisites

* [x] Did you thoroughly search the [open](https://github.com/adobe-fonts/source-han-sans/issues) and [closed](https://github.com/adobe-fonts/source-han-sans/issues?q=is%3Aissue+is%3Aclosed) issues to avoid reporting a duplicate issue?
* [x] If you are reporting an issue that affects glyphs for characters for a particular region or regions, did you verify that the characters are within the supported scope of the region or regions? This generally means GB 18030 or Tōngyòng Guīfàn Hànzìbiǎo (通用规范汉字表) for China, Big Five or CNS 11643 Planes 1 & 2 for Taiwan, HKSCS-2016 for Hong Kong, JIS X 0208, JIS X 0212, and JIS X 0213 for Japan, and KS X 1001 and KS X 1002 for Korea.
* [x] Did you go through the [official font readme file](https://github.com/adobe-fonts/source-han-sans/raw/release/SourceHanSansReadMe.pdf) to better understand the scope of the project, to include the *Known Issues* section at the very end?

### Description
>I've read https://github.com/adobe-fonts/source-han-sans/issues/186
>It's three years ago, but **Illustrator still not slove this problem** can you **give me some Useful method** to slove this problem. 
>This question is really annoying. 
>Thank you. 

The character bounding box is too large
like this: 
![image](https://user-images.githubusercontent.com/79351490/150472334-b27d9205-bf50-4e9f-8cf6-b20d8e9a514d.png)

**Comment by punchcutter** [comment]
There's nothing to solve here and it's explained in https://github.com/adobe-fonts/source-han-sans/issues/186
