### ISSUE TITLE
Unable to embed Source Han Sans VF correctly in TextEdit (Apple)

### ISSUE THREAD

**Issue by akihironagai** [adobe-fonts/source-han-sans#330]
### Prerequisites

* [X] If you are reporting an issue that affects glyphs for characters for a particular region or regions, did you verify that the characters are within the supported scope of the region or regions? This generally means GB 18030 or Tōngyòng Guīfàn Hànzìbiǎo (通用规范汉字表) for China, Big Five or CNS 11643 Planes 1 & 2 for Taiwan, HKSCS-2016 for Hong Kong, JIS X 0208, JIS X 0212, and JIS X 0213 for Japan, and KS X 1001 and KS X 1002 for Korea.
* [X] Did you thoroughly search the [open](https://github.com/adobe-fonts/source-han-sans/issues) and [closed](https://github.com/adobe-fonts/source-han-sans/issues?q=is%3Aissue+is%3Aclosed) issues to avoid reporting a duplicate issue?
* [X] Did you go through the [official font readme file](https://github.com/adobe-fonts/source-han-sans/raw/release/SourceHanSansReadMe.pdf) to better understand the scope of the project, to include the *Known Issues* section at the very end?

### Description

When embedding Source Han Sans VF in TextEdit (Apple) and opening it in another application, characters are invisible or some characters (like 自, 由, 尊, 理, 神 in Japanese and A) are damaged.

Examples follow (
1st line is Source Han Sans VF Normal
2nd line is Source Han Sans Normal
3rd line is Source Han Sans VF Bold
4th line is Source Han Sans Bold
Sample PDF is [here](https://github.com/adobe-fonts/source-han-sans/files/8145900/TextEdit.Source.Han.Sans.VF.Bug.pdf)):

In Apple Files App in iOS 15, characters are shown correctly.
![Apple Files App in iOS 15](https://user-images.githubusercontent.com/77012577/155829003-1d4c8776-1ec3-4eb5-a1b7-ac60e76e7f38.png)

In Adobe Acrobat DC, characters are not shown (missing fonts).
The message is "Cannot extract the embedded font 'AAAAAC+SouceHanSansVF-Normal'. Some characters may not display or print correctly."
![Adobe Acrobat DC](https://user-images.githubusercontent.com/77012577/155829078-6dd54431-8343-4dc6-8538-fa2a6b25d85e.png)

In Firefox for Windows, characters are shown, but characters are damaged.
![Firefox](https://user-images.githubusercontent.com/77012577/155829137-2ad1ffe2-6ac4-4ccb-b6fa-3774af195233.png)

**Comment by punchcutter** [comment]
This isn't a font issue. It's a problem with how the apps are handling variable fonts. The "damaged" text you see is a problem in how the app displays the glyphs. There's nothing to be done in the fonts and there are already some open issues about variable font handling in apps. 

By "unable to embed" do you only mean making a PDF from TextEdit?

**Comment by punchcutter** [comment]
Which VF fonts are you using? TTF or OTF?

**Comment by akihironagai** [comment]
> This isn't a font issue. It's a problem with how the apps are handling variable fonts. The "damaged" text you see is a problem in how the app displays the glyphs. There's nothing to be done in the fonts and there are already some open issues about variable font handling in apps.

I understood.

> Which VF fonts are you using? TTF or OTF?

I am using OTF fonts.

> By "unable to embed" do you only mean making a PDF from TextEdit?

Apple Pages and Apple Keynote have the same issue.

These apps use Quartz PDFContext. Therefore, this may be a origin of the issue.
