### ISSUE TITLE
double quotes (U+201C and U+201D) are too widely spaced in Microsoft Word

### ISSUE THREAD

**Issue by ZhuangQu** [adobe-fonts/source-han-sans#337]
In Microsoft Word 365, the double quotes (U+201C and U+201D) are spaced too far apart horizontally and look like
![2022-05-20-03-11-25](https://user-images.githubusercontent.com/89310792/169384208-8299104d-2082-425c-b61a-7833ead08fc2.png)
The correct situation should be
![2022-05-20-03-13-15](https://user-images.githubusercontent.com/89310792/169384553-6108bcaa-12ec-4480-b70c-c9c69f53c9cb.png)
This problem does not occur in PPT or Excel.

**Comment by frankrolf** [comment]
These screenshots look like they do come from different fonts. Are you sure you’re reporting on Source Han Sans?

**Comment by ZhuangQu** [comment]
> These screenshots look like they do come from different fonts. Are you sure you’re reporting on Source Han Sans?

The first image is `Source Han Sans`, and the second image is the system's built-in `黑体`, as a comparison.

**Comment by punchcutter** [comment]
Related issues: 
https://github.com/adobe-fonts/source-han-sans/issues/28 
https://github.com/adobe-fonts/source-han-sans/issues/71
https://github.com/googlefonts/noto-cjk/issues/118
https://github.com/googlefonts/noto-cjk/issues/5

@ZhuangQu to be totally clear please also provide more information. Windows or Mac? Which version of Word 365? The installed version or run in a browser? If browser then which one? Which Source Han Sans font? Source Han Sans SC? Source Han Sans CN? The related issues are mostly about the Chinese specific font, but you don't write which one you are using.

**Comment by ZhuangQu** [comment]
> Related issues: #28 #71 [googlefonts/noto-cjk#118](https://github.com/googlefonts/noto-cjk/issues/118) [googlefonts/noto-cjk#5](https://github.com/googlefonts/noto-cjk/issues/5)
> 
> @ZhuangQu to be totally clear please also provide more information. Windows or Mac? Which version of Word 365? The installed version or run in a browser? If browser then which one? Which Source Han Sans font? Source Han Sans SC? Source Han Sans CN? The related issues are mostly about the Chinese specific font, but you don't write which one you are using.

Thank you for your reply! My platform is Windows 11 and Word 365 version is `2204 build 16.0.15128.20210 64 bit` installed on PC. The font I downloaded is `Region Specific Subset OTFs Simplified Chinese (简体中文)` in your release. It is `Source Han Sans CN`. For your reproduction, here is [demo.docx](https://github.com/adobe-fonts/source-han-sans/files/8738474/demo.docx). The relevant issue is subtly different from my issue.

**Comment by ZhuangQu** [comment]
I now think this is a bug in Microsoft Word, not in font, so I closed this issue and will take it up with Microsoft.
