### ISSUE TITLE
Old hangul and vertical writing mode on MS Word 2007 on Windows 7

### ISSUE THREAD

**Issue by acuteaccent** [adobe-fonts/source-han-sans#34]
Old hangul is not composed at all in the vertical writing mode of Microsoft Word 2007 on Windows 7.
Also, the default line spacing is too wide (see the size of the cursor).

Font: Source Han Sans Regular
Text size: 12 pt
Line spacing: 1.0, pressed "Remove Space After Paragraph" once
![msword2007oldhangul](https://cloud.githubusercontent.com/assets/8185770/3638781/ad147cb6-1060-11e4-92bb-a7a2aab11968.png)

Text used in image:
사ᄅᆞᆷ마다ᄒᆡᅇᅧ수ᄫᅵ니겨날로ᄡᅮ메
便뼌安ᅙᅡᆫ킈ᄒᆞ고져ᄒᆞᇙᄯᆞᄅᆞ미니라

There is no problem in the horizontal writing mode.
![msword2007oldhangulhorizontal](https://cloud.githubusercontent.com/assets/8185770/3638785/fbbd1404-1060-11e4-85f7-5f2af37fbe5b.png)

**Comment by acuteaccent** [comment]
Would it be better to close this? As no one knows how to fix this, I don't see a point in leaving this open.

**Comment by kenlunde** [comment]
I prefer to keep this Issue open.

**Comment by kenlunde** [comment]
On second thought, let's close this issue for now, given that it is unclear what needs to be done, and given that Malgun Gothic doesn't appear to be doing anything special. The issue may be related to the format, specifically that OpenType/CFF fonts are being treated differently. If we determine the exact cause of this behavior at a later date, we can re-open the issue.

**Comment by KrasnayaPloshchad** [comment]
Is it possible to reopen this issue? I found some of Hangul Jamos seems still misbehaviored on Firefox on Windows 10 just now.

**Comment by kenlunde** [comment]
If you are able to pinpoint the exact cause of this issue in Source Han Sans, I am okay with re-opening this issue. Based on everything that has been discussed, and unless anyone can provide evidence to the contrary, the issue appears to be related to format (OpenType/CFF versus TrueType).

**Comment by jungshik** [comment]
Virtually all the remaining issue here was fixed in googlei18n/noto-cjk#79. A font with Ken's fix is available there. The only remaining issue is handling of HCF(U+115F) and HJF(U+1160). I'll follow up on them there.

**Comment by kenlunde** [comment]
As @jungshik stated, we are close to having a solution for the issue of combining jamo in vertical writing. I feel really dumb for not noticing @dohyunkim's reference to a 'vert' GPOS feature, which is implemented in the HCR Batang LVT font. I recently came to the same conclusion.

My own testing suggests that the YPlacement and YAdvance values can also be set in the 'vert' GPOS feature, in lieu of specifying override values in the 'vmtx' table, which has the advantage of putting all of the metrics settings in one place: XPlacement (460), YPlacement (1000), and YAdvance (-1000).

Two test fonts, based on Noto San CJK, are available in [Noto CJK Issue 79](https://github.com/googlei18n/noto-cjk/issues/79#issuecomment-279702701).

My personal opinion on this matter is that HarfBuzz should be the implementation of choice, when it comes to figuring out the best solution for combining jamo in vertical writing. Other implementations can then follow the same behavior.

Anyway, I am re-opening this issue.

**Comment by acuteaccent** [comment]
![hunmin-word2016](https://cloud.githubusercontent.com/assets/8185770/24976360/fec598f4-1f7d-11e7-9efd-56148c90f419.png)
This problem is gone in MS Word 2016. As the support for MS Word 2007 will end in about six months (October 10, 2017), I think this issue is not that important now.
