### ISSUE TITLE
My doubts about copyright

### ISSUE THREAD

**Issue by Simonblessings** [adobe-fonts/source-han-sans#344]
### Description

Hello, I want to know if [思源黑体TW-Light], English Name: source Han sans TW light, is it free for commercial use? I want to use it as a part-time PPT, so I would like to ask about its copyright. Then, I would like to ask, when is the deadline for free commercial use?Thank you for your reply, thank you.

###postscript
 I have some doubts about this online community for the first time, so I ask questions here and hope to get an answer. Thanks again!

**Comment by NightFurySL2001** [comment]
This font is licensed under [SIL Open Font License, Version 1.1](https://github.com/adobe-fonts/source-han-sans/blob/master/LICENSE.txt), which is an open source font and does not have a deadline per se.

**Comment by punchcutter** [comment]
The LICENSE file should be pretty clear about that. If there's still something unclear please ask.
