### ISSUE TITLE
Source Han Sans J is why is not?

### ISSUE THREAD

**Issue by kmsu3541** [adobe-fonts/source-han-sans#346]
Why is it Japanese font only for names with nothing after Source Han Sans?
Noto CJK font also has the name 'JP' and Source San Han is Add 'J' in Japanese font just like 'K' in Korean font.
Also, I think there can be confusion because nothing is marked.

Source Han Sans -> Source Han Sans J
Source Han Sans HW -> Source Han Sans HW J
Source Han Serif -> Source Han Serif J

**Comment by tamcy** [comment]
I think your question was answered [here](https://github.com/adobe-fonts/source-han-serif/issues/50#issuecomment-297604455).

**Comment by punchcutter** [comment]
Thanks @tamcy. That explains the situation and why it's not changing for Source Han.
