### ISSUE TITLE
Some korean characters are issue.

### ISSUE THREAD

**Issue by kmsu3541** [adobe-fonts/source-han-sans#353]
I didn't check the whole thing, but there is an issue.
* (糸)：䋽　纀　綼　紴‥
![image](https://user-images.githubusercontent.com/109888392/213637456-eefadd71-1e3f-4c97-9f18-241464cb25be.png) ![image](https://user-images.githubusercontent.com/109888392/213637599-f75a38d0-23e3-4a2e-a485-356fb9e1134b.png)
![image](https://user-images.githubusercontent.com/109888392/213637713-c5d146c9-3a82-4d2b-8c30-ce4881f51648.png) ![image](https://user-images.githubusercontent.com/109888392/213637749-370bf150-7d6c-4aae-abe9-c8f1744132f3.png)

* (平)：䍬　㛁　匉‥
![image](https://user-images.githubusercontent.com/109888392/213637482-5584a23b-0eb8-45de-a87e-09cddbc5d42c.png) ![image](https://user-images.githubusercontent.com/109888392/213638053-114c21ac-9aa1-4b99-898b-f87a30bf14f4.png) ![image](https://user-images.githubusercontent.com/109888392/213638096-7a375e81-f59b-4cfb-bc22-dc195632611f.png)

* (勺)：勺　趵..
![image](https://user-images.githubusercontent.com/109888392/213639316-01a1f584-b351-474b-9825-bcf9f39245d6.png) ![image](https://user-images.githubusercontent.com/109888392/213639482-3e23c566-b5dd-4486-93a0-e4194fb24af2.png)

* (言)：諀‥ ![image](https://user-images.githubusercontent.com/109888392/213639697-f924416d-4772-496c-ad80-4e3efa1fbda7.png)

* (辵)：䢌‥ 
![image](https://user-images.githubusercontent.com/109888392/213639750-f5853541-b9f3-4b74-9582-6e6abda7d7ee.png)

**Comment by tamcy** [comment]
I may not understand what you actually mean ("issue" is too ambigious), but since you are reporting glyph issues against the Korean version of the font, you'd probably first need to make sure the codepoints are within the supported scope of this variant, i.e. KS X 1001 and KS X 1002 as stated in this issue and the README file.

**Comment by kmsu3541** [comment]
Even if it is outside the Unicode area, 漢字 is treated as 漢字 in each country, so I would appreciate it if you could allocate it.
But apparently, they don't handle "Simplified" Chinese characters. This is also true in the country.
