### ISSUE TITLE
How can we build the TTF version instead of OTF

### ISSUE THREAD

**Issue by richso** [adobe-fonts/source-han-sans#365]
### Prerequisites
Some of the provided download package only include the OTF files but no TTF version

### Description
On converting some of these OTF files to TTF (e.g. SourceHanSansHC-Normal.otf from "Language Specific - OTFs"), we got "WARNING: Dropping glyph names, they do not fit in 'post' table." via otf2ttf utility of AFDKO; we do not know whether because of this, the text using such font face cannot be displayed (becomes blanks) in the resulting PDF which we generated using a report generator program (Jasperreport which use iText2 or iText7). Note that, the same problem do not happen for SourceHanSansHK-Regular.otf (contains less Chinese words) from "Region-specific Subset OTFs" (no warning on conversion, text can be displayed normally in the resulting PDF)

So we are seeking to directly generate the relevant fonts to TTF files and see whether it helps

**Comment by richso** [comment]
Finally, I find the way to directly build the TTF version with reference to the COMMANDS.txt:

`
makeotf -f cidfont.ps.OTC.HC -omitMacNames -ff features.OTC.HC -fi cidfontinfo.OTC.HC -mf ../../FontMenuNameDB -r -nS -cs 2 -ch ../../UniSourceHanSansHK-UTF32-H -ci ../../SourceHanSans_HK_sequences.txt -o SourceHanSans-HK.ttf
`

**Comment by punchcutter** [comment]
That doesn't actually make a TTF. That will only make an OTF with the `.ttf` extension. If it fixes your issue then that's great, but this is not an actual TTF.

**Comment by richso** [comment]
@punchcutter oh! really. I've checked the description of "makeotf" from the page http://adobe-type-tools.github.io/afdko/AFDKO-Overview.html, and it says the utility can create TTF, but no more instruction can be found anywhere. Despite I've solved my problem with the "fake" TTF, can I know (I really want to know) how to make a real TTF directly?

**Comment by punchcutter** [comment]
Yes, `makeotf` can produce a new TTF with updated features such as names or OS/2, etc from an existing TTF, but it can't create a new TTF from source files. The current Source Han build process is really only set up for OTF and the only TTFs are variable font TTFs which is a newer addition. There are some unofficial static TTFs around, but we don't plan to produce TTFs as part of the official releases except for the variable fonts. 

You can use the released variable TTFs to create static instances, though. For example

`fonttools varLib.instancer --remove-overlaps --update-name-table -o SourceHanSansHC-Regular.ttf SourceHanSansHC-VF.ttf wght=400`

That fails for me right now so I opened an issue https://github.com/fonttools/fonttools/issues/2905. Without `--remove-overlaps` it will make a static TTF, but you might see issues in rendering so I would wait for fontTools to get `--remove-overlaps` working first.
