### ISSUE TITLE
Recovery of subfamily deleted 1.004 in 2.004R

### ISSUE THREAD

**Issue by sommio** [adobe-fonts/source-han-sans#394]
Why remove the subfamily "Source Han Sans CN Bold", which causes backward compatibility issues, as some applications use `(Source Han Sans CN Bold, 400)` and `(Source Han Sans CN Bold, 700)` instead of `(Source Han Sans CN, 700)`

SourceHanSansCN-Bold_2.004R.otf: Source Han Sans CN:style=Bold
SourceHanSansCN-Bold_1.004.otf:   Source Han Sans CN,Source Han Sans CN Bold:style=Bold,Regular

You can't ask for font handling library compositing as this will cause openjdk errors

**Comment by punchcutter** [comment]
1.004 didn't have style linking. Style linking between Regular and Bold was added in 2.000 in 2018 and is explained in the release notes. There's nothing to be done on the font side.

**Comment by sommio** [comment]
> 1.004 didn't have style linking. Style linking between Regular and Bold was added in 2.000 in 2018 and is explained in the release notes. There's nothing to be done on the font side.

Is my v1.004 wrong? It no doubt exists style link
[SourceHanSansCN-Bold.otf.zip](https://github.com/adobe-fonts/source-han-sans/files/10937931/SourceHanSansCN-Bold.otf.zip)

**Comment by punchcutter** [comment]
Nothing was abandoned or removed. Style linking was added. If the apps you are using have a problem then it's an app problem not a font problem.

**Comment by sommio** [comment]
> Nothing was abandoned or removed. Style linking was added. If the apps you are using have a problem then it's an app problem not a font problem.

Do you have to remove the subfamily to add the style link?
If you think this is an app issue, then let's end the discussion there

![截图 2023-03-10 10-59-32](https://user-images.githubusercontent.com/64189793/224212267-681ab047-5b63-4775-82b7-042c48001d45.png)

**Comment by punchcutter** [comment]
That's how style linking works and that's not going to change in any future version.

**Comment by sommio** [comment]
> That's how style linking works and that's not going to change in any future version.

I think what you mean is that the font can be called via the style link, so there is no need to use subfamily.

But I hope you at least add subfamily for the CN and SC, because the major Chinese font makers FounderType and Hanyi have not used sytle link for a long time, so the Chinese are not in the habit of using sytle link.

eg.
方正兰亭黑-DB-GBK.otf: FZLanTingHei-DB-GBK:style=Regular
方正兰亭黑-M-GBK.otf: FZLanTingHei-M-GBK:style=Regular
方正兰亭黑-L-GBK.otf: FZLanTingHei-L-GBK:style=Regular
方正兰亭黑-R-GBK.otf: FZLanTingHei-R-GBK:style=Regular
方正兰亭中粗黑-DB1-GBK.otf: FZLanTingHeiS-DB1-GBK:style=Regular
方正兰亭黑-EL-GBK.otf: FZLanTingHei-EL-GBK:style=Regular
方正兰亭黑-B-GBK.otf: FZLanTingHei-B-GBK:style=Regular
方正兰亭黑-UL-GBK.otf: FZLanTingHei-UL-GBK:style=Regular
方正兰亭黑-H-GBK.otf: FZLanTingHei-H-GBK:style=Regular
方正兰亭黑-EB-GBK.otf: FZLanTingHei-EB-GBK:style=Regular

**Comment by punchcutter** [comment]
There already is a subfamily name. The style linking was an improvement in 2.000 and the names won't be changing now.
