### ISSUE TITLE
How to create a CMap file from a map file

### ISSUE THREAD

**Issue by jaynfs** [adobe-fonts/source-han-sans#40]
For example, how to create UniSourceHanSansCN-UTF32-H from utf32-cn.map?

**Comment by ShikiSuen** [comment]
@kenlunde There are no files on SHS source-forge site. Could you please update this link?:
![image](https://cloud.githubusercontent.com/assets/3164826/8124945/23408072-109e-11e5-9cfa-0b6c0ea32da6.png)
Thanks.

**Comment by miguelsousa** [comment]
@ShikiSuen this is the new location https://github.com/adobe-type-tools/perl-scripts/

**Comment by ShikiSuen** [comment]
@miguelsousa Copy that, thanks for assistance.

**Comment by kenlunde** [comment]
@miguelsousa: The 'cmap-resources' project is for our public CMap resources, such as for Adobe-Japan1-6. The UTF-32 CMap resources for SHS are in its master branch.

**Comment by kenlunde** [comment]
I further edited my initial response to point to our [perl-scripts](https://github.com/adobe-type-tools/perl-scripts/) project as the location of the particular Perl script.

**Comment by ShikiSuen** [comment]
@kenlunde Copy that, thank you.

**Comment by miguelsousa** [comment]
@kenlunde I see. I'll remove the link to the general CMaps then, to avoid confusion.

**Comment by ShikiSuen** [comment]
What I have to say is that I couldn't find cmap initial files like utf32-kr.map among every commit of SHS source files at this moment.

**Comment by ShikiSuen** [comment]
Successfully found them at the release **branch**.
