### ISSUE TITLE
The Simplified Chinese character shown in OS X Yosemite iMessage App

### ISSUE THREAD

**Issue by jian880821** [adobe-fonts/source-han-sans#41]
As shown in the picture, the characters aren't aligned on the same baseline in the input box. Furthermore, the sent message is not displayed properly as the bottom is erased.

![2014-07-25 4 57 11](https://cloud.githubusercontent.com/assets/8265811/3699910/cdedaeea-13d9-11e4-93ee-4d78028fac18.png)

**Comment by ShikiSuen** [comment]
@jian880821 Issue solved by Adobe Official SHS 1.002:
![image](https://cloud.githubusercontent.com/assets/3164826/7237056/0ab3f83e-e756-11e4-8897-2e2709a22c6d.png)
