### ISSUE TITLE
Request to support some Greek characters for WEB

### ISSUE THREAD

**Issue by YusukeShirakihara** [adobe-fonts/source-han-sans#461]
Hello. Thank you for providing us with great fonts.
I’d like to report a request to update Source Han Sans for **WEB**.

It applies to Version 2.004R (OTF, OTC, Super OTC, Subset OTF, Variable OTF/TTF):
https://github.com/adobe-fonts/source-han-sans/releases/tag/2.004R

Sample
ΆΈΉΊΌΎΏΐΪΫάέήίΰςϊϋόύώ
U+0386, 0388, 0389, 038A, 038C, 038E, 038F, 0390, 03AA, 03AB, 03AC, 03AD, 03AE, 03AF, 03B0, 03C2, 03CA, 03CB, 03CC, 03CD, 03CE

SourceHanSans-Regular.otf
hb-view (harfbuzz 2.7.4, Ubuntu 22.04.3 LTS)
![image](https://github.com/adobe-fonts/source-han-sans/assets/122098208/95e936bc-7170-4214-a38d-9a6d42290cea)

These strings can be correctly displayed in Source Sans version 3.052.
https://github.com/adobe-fonts/source-sans/releases/tag/3.052R
SourceSans3-Regular.ttf
hb-view (harfbuzz 2.7.4, Ubuntu 22.04.3 LTS)
![image](https://github.com/adobe-fonts/source-han-sans/assets/122098208/9a512a92-1749-4d7c-98e4-ef1e917c0e45)

I checked SourceHanSansReadMe.pdf and it seems not clear which Greek characters are supported in Source Han Sans.
When a web page with CJK contains some Greek words, it is desirable that the Greek characters be displayed correctly in Source Han Sans, rather than switching to Source Sans for only some of the characters.
Thank you for taking this request into consideration.

**Comment by tamcy** [comment]
Not a project maintainer per se, but your concern might have already been answered in #278 and #273. 

> When a web page with CJK contains some Greek words, it is desirable that the Greek characters be displayed correctly in Source Han Sans, rather than switching to Source Sans for only some of the characters.

In this case, in my experience, Source Han Sans/Serif is no different from other CJK fonts where a complete coverage of LGC characters are not their main objective. The problem is even much more easier to solve on the web - just use a LGC font as the primary font with CJK a font as the fallback.

**Comment by YusukeShirakihara** [comment]
I see.
Thank you for your good infomation.
I close this post.
