### ISSUE TITLE
The weight "Regular" has one more space.

### ISSUE THREAD

**Issue by Frank3382** [adobe-fonts/source-han-sans#469]
The weight "Regular" has one more space.
![](https://github.com/adobe-fonts/source-han-sans/assets/142497414/689e43d3-918d-407a-be47-ed7120e973c8)

**Comment by Frank3382** [comment]
I found this problem in different region specific subset. But I didn't find it in Noto Sans CJK.

**Comment by punchcutter** [comment]
The font does not have an extra space. InDesign incorrectly shows an extra space for some reason.
