### ISSUE TITLE
Variable fonts have duplicate style names

### ISSUE THREAD

**Issue by yisibl** [adobe-fonts/source-han-sans#471]
- SourceHanSansCN-VF, `Version 2.004;hotconv 1.0.118;makeotfexe 2.5.65603`

There are two `ExtraLight` in the font list.

![image](https://github.com/adobe-fonts/source-han-sans/assets/2784308/a2266ced-c5ef-4172-bfb8-06bea958a5e4)

![image](https://github.com/adobe-fonts/source-han-sans/assets/2784308/80b67e22-9705-4adc-98bd-abcd6e6977ad)

**Comment by punchcutter** [comment]
There are no duplicate styles in the font. This must be a bug in the app display, not the font.
