### ISSUE TITLE
Please adapt the letters:

### ISSUE THREAD

**Issue by xivi1839** [adobe-fonts/source-han-sans#479]
Please adapt Turkish letters:
Ğ ğ、Ş ş、I ı、İ i、

**Comment by Marcus98T** [comment]
I don't think that will be the scope of Source Han Sans as it's mostly focused on CJK languages (because of the sheer amount of ideographs and the 65K glyph limit). You can do with [Source Sans](https://github.com/adobe-fonts/source-sans) instead, which supports Turkish in full.

Sorry about that.
