### ISSUE TITLE
Error in mapping for U+3D1D 㴝 and U+2A3ED 𪏭 in HK

### ISSUE THREAD

**Issue by S-Asakoto** [adobe-fonts/source-han-sans#488]
It seems that the glyphs for U+3D1D 㴝 and U+2A3ED 𪏭 are kind of mixed up in HK locale, while in other locales the mapping is correct.
![image](https://github.com/adobe-fonts/source-han-sans/assets/53332894/715f61c1-c2df-407d-adb0-882ecfdba1e8)

And for some reason when displaying in Chrome the mappings change again, having correct mapping for U+2A3ED but identical shape for U+3D1D
![image](https://github.com/adobe-fonts/source-han-sans/assets/53332894/f973f6a8-1c07-4f2f-8304-0a9109590d42)

**Comment by tamcy** [comment]
First, the font's cmap of v2.004 shows that both U+3D1D 㴝 and U+2A3ED 𪏭 are mapped to u2A3ED-HK for HK for v2.004. 

![image](https://github.com/adobe-fonts/source-han-sans/assets/959433/e043d27c-0695-43f3-96ea-e05d67fcb9b0)

In my testing, the two codepoints appear as ⿱利𱥯 in both the CJK and subset configurations for HK. This aligns with the cmap, and no swapping has occurred. I suggest you to supply your version and configuration for a better investigation after confirming the HK glyph in your report is really a U+2A3ED.

Second, the background of U+3D1D and U+2A3ED in HKSCS is best explained in [this document](http://std.dkuug.dk/JTC1/SC2/WG2/docs/N4621.pdf):

---
![image](https://github.com/adobe-fonts/source-han-sans/assets/959433/9c2c8798-3698-4fb0-9946-71b6db1fce71)
---

So it is very possible that both Source Han Sans and Serif decided to keep the original HK form of ⿱利𱥯 in U+3D1D in the HK version for backward compatibility.

**Comment by S-Asakoto** [comment]
Thanks for the info, will close the issue.
