### ISSUE TITLE
the dot in Turkish dotted I U+0130 `İ` shifted towards right side

### ISSUE THREAD

**Issue by n0099** [adobe-fonts/source-han-sans#489]
### Prerequisites

* [x] If you are reporting an issue that affects glyphs for characters for a particular region or regions, did you verify that the characters are within the supported scope of the region or regions? This generally means GB 18030 or Tōngyòng Guīfàn Hànzìbiǎo (通用规范汉字表) for China, Big Five or CNS 11643 Planes 1 & 2 for Taiwan, HKSCS-2016 for Hong Kong, JIS X 0208, JIS X 0212, and JIS X 0213 for Japan, and KS X 1001 and KS X 1002 for Korea.
* [x] Did you thoroughly search the [open](https://github.com/adobe-fonts/source-han-sans/issues) and [closed](https://github.com/adobe-fonts/source-han-sans/issues?q=is%3Aissue+is%3Aclosed) issues to avoid reporting a duplicate issue?
* [x] Did you go through the [official font readme file](https://github.com/adobe-fonts/source-han-sans/raw/release/SourceHanSansReadMe.pdf) to better understand the scope of the project, to include the *Known Issues* section at the very end?

### Description

https://en.wikipedia.org/wiki/İ
https://www.compart.com/en/unicode/U+0130
![image](https://github.com/adobe-fonts/source-han-sans/assets/13030387/0f2948dd-cad0-4062-8c53-1ccea00fd38e)
![image](https://github.com/adobe-fonts/source-han-sans/assets/13030387/7d8feb5d-b2bc-4b36-b5b5-6dfe59776e3d)

**Comment by NightFurySL2001** [comment]
This font does not support the Turkish dotted I as this is a CJK font.

**Comment by n0099** [comment]
Then just remove this character from the font so it will fallback to other fonts which may render it normally.

**Comment by NightFurySL2001** [comment]
This font doesn't have this character (full list of glyphs by Unicode at https://raw.githubusercontent.com/adobe-fonts/source-han-sans/release/Resources/AI0-SourceHanSans if you are lazy enough to not open the font file to check). 

It seems that Chrome automatically decompose it to `I` + combining dot above (U+0309). Below is U+0130 and U+0049, U+0307 in Microsoft Word 2021. Notice that U+0130 had successfully fallback to Calibri, but the combining version shows the same problem as in Chrome. This seems to be an unintended consequence from Chrome as U+0307 is included in Adobe-Japan1.

Text: `İİ`
![image](https://github.com/adobe-fonts/source-han-sans/assets/33471049/a1717129-7e0c-4b69-b41b-ac9143fcd557)

**Comment by n0099** [comment]
https://glyphwiki.org/wiki/aj1-20338

**Comment by n0099** [comment]
```html
<h1 style="font-family: 'Noto Sans CJK SC'">İ</h1>
<h1 style="font-family: 'Source Han Sans SC'">İ</h1>
```
As of Chrome 150, it's still performing Unicode normalization (maybe NFD you mentenioned) on `U+0130`:
<img width="110" height="234" alt="Image" src="https://github.com/user-attachments/assets/6cf9282d-67b4-4754-8b80-7798b3ebae91" />
<img width="408" height="148" alt="Image" src="https://github.com/user-attachments/assets/55820a23-b407-45c6-a3a0-281a86089641" />
<img width="432" height="148" alt="Image" src="https://github.com/user-attachments/assets/d8284723-2b22-4043-a3ac-81791b73e443" />
and Firefox 153 won't do that:
<img width="154" height="277" alt="Image" src="https://github.com/user-attachments/assets/d1df443d-d7c2-435b-9e6d-c59adb7952e9" />
<img width="690" height="144" alt="Image" src="https://github.com/user-attachments/assets/ba16f6f9-2962-476b-85d3-0ba432e6da11" />
