### ISSUE TITLE
Questions about Language Specific OTFs Simplified Chinese "类" (U+7C7B/0xCOE0) words

### ISSUE THREAD

**Issue by xiaoguan-dot** [adobe-fonts/source-han-sans#494]
# Questions about Language Specific OTFs Simplified Chinese "类" (U+7C7B/0xCOE0) words

When I was editing the PPT in my "Microsoft PowerPoint", I found a typo in the word "class". I opened the character mapping table to determine that the word was indeed misspelled in the font. According to the "Universal Chinese Character Specification Table", the word "class" is written as follows:
![「类」](https://github.com/adobe-fonts/source-han-sans/assets/100571246/0a9415ba-43be-46db-b3e9-376f45da2e33)
Rather than for:
![「Wrong “类” word」](https://github.com/adobe-fonts/source-han-sans/assets/100571246/3f916d3d-64f7-4a25-9eb3-6d030feda8fc)
I am a junior high school student. If you think there is an error in the "Universal Chinese Character Standard Table", or what I said is wrong, please point it out.

zh-cn | 中文简体
# 关于语言专用OTF的问题简体中文 "类"（U+7C7B/0xCOE0）字
我在我的 “Microsoft PowerPoint” 中编辑PPT时，发现了“类”这个字的书写错误，我打开了字符映射表，以确定这个字在该字体中确实书写错误，参考《通用汉字规范表》中，“类”字的写法为：
![「类」](https://github.com/adobe-fonts/source-han-sans/assets/100571246/0a9415ba-43be-46db-b3e9-376f45da2e33)
而并非为：
![「错误的“类”字」](https://github.com/adobe-fonts/source-han-sans/assets/100571246/3f916d3d-64f7-4a25-9eb3-6d030feda8fc)
我是一名初中学生，如果认为《通用汉字规范表》中有错误，或我所说的有错误，欢迎指出

**Comment by NightFurySL2001** [comment]
Please ensure in PowerPoint you are using “思源黑体” or "Source Han Sans SC“ and not "Source Han Sans“. The English name without SC/CN is for Japanese, and this ”类“ is the traditional writing (simplified from left of 類).
请确认PowerPoint里面字体是使用 “思源黑体” 或 "Source Han Sans SC“ 而不是 "Source Han Sans“。英文名称没有 SC/CN 的 "Source Han Sans“ 是日语字体，这个 ”类“ 是传统写法（简化自 類 左）。

![image](https://github.com/adobe-fonts/source-han-sans/assets/33471049/d5fd578f-139c-4527-be07-11907a785e11)

**Comment by xiaoguan-dot** [comment]
@NightFurySL2001 好的，我知道了，感谢 | Ok, I see, thanks.
