### ISSUE TITLE
Suggestions on expanding SHS Korean font's Kanji set to 65535 based on current Korean Glyph Standards.

### ISSUE THREAD

**Issue by ShikiSuen** [adobe-fonts/source-han-sans#54]
As what @syaoranhinata told me about:

"韓文寫法大體上與舊字形（旧字形，きゅうじぎょう）相同（而且依**同文書局（どうぶんしょきょく）**原版的《康熙（こうき）》，並沒有DerkZech所列那麼多差異。部分差異是因DerkZech使用王引之（おう・ひきゆき）校訂本而來的，但學界研究《康熙》寫法都以同文書局版爲準）。"（小林劍精通日文，故部分漢語詞使用日文注音）

English translation:
"Korean's Kanji Glyph standard looks generally the same as the kyuujigyou glyph styles referred from the initial version of Kouki Dictionary which was published by Toubun Shokyoku publishing house (generally accepted as a standard by academic study areas concerned about kanji), not as what @DerkZech (#48) referred from the later versions revised by Hikiyuki Ou."

And @syaoranhinata thinks that it is an acceptable solution if SHS Korean font's Kanji set expands to all 65535 kanjis based on Korean's current glyph standard after having a nice conversation with me (This idea came out of MY mind at first).

I don't have a clue whether this suggestion could be acceptable by Adobe, but I just try paste it here and wait for people's responds.

**Comment by dine2014** [comment]
The current Korean version of Source Han Sans does not distinguish 月 (moon, as in 明), ⺼ (from 肉, as in 胸), and 月 with two dots (from 舟, as in 朝), which means that part of the characteristics of Kangxi-style glyphs would be lost. But of course, Korean glyphs for Traditional Chinese is better than nothing.

(Strangely, the Japanese Wiktionary says that the 月 in 朝 is a real "moon", and it's 残月 or 潮が満ちる様with 𠦝 being sun coming out of horizon indicated by grass, while the English Wiktionary says the 月 in 朝 is a graphical corruption of 川. What gives? The Korean glyph standard seems to have avoided unclear etymologies like this by using a single glyph for 月 consistently.)

**Comment by hfhchan** [comment]
> (Strangely, the Japanese Wiktionary says that the 月 in 朝 is a real "moon", and it's 残月 or 潮が満ちる様with 𠦝 being sun coming out of horizon indicated by grass, while the English Wiktionary says the 月 in 朝 is a graphical corruption of 川. What gives? The Korean glyph standard seems to have avoided unclear etymologies like this by using a single glyph for 月 consistently.)

Both are correct, to some extent.
In Bronze script a 朝-like character with "川" is commonly found which is the prototypical form of 潮 in modern usage while in Oracle Bone 朝 with 月 (moon) is more common which is the prototypical form of 朝 meaning twilight/morning in modern usage.

As far as I am concerned, people should have transcribed the former form to something else, say ⿰𠦝川.  Anyhow, Bronze and Oracle Bone are scripts that predate the modern Han script. As far as CJK Unified Ideographs should be concerned, they are the same character.

**Comment by kenlunde** [comment]
The Korean standards are rife with inconsistencies, probably because 99.9% of modern Korean text is composed of hangul syllables, and as a result, most Koreans are not that sensitive to the shapes, nor to the etymology. In other words, depending on Korean fonts that are based on Korean standards to provide a consistent Kangxi-style glyph design can only end in disappointment.
