### ISSUE TITLE
Incorrect shapes of 又 and 叉 parts (T Chinese)

### ISSUE THREAD

**Issue by ButTaiwan** [adobe-fonts/source-han-sans#61]
http://www.edu.tw/FILES/SITE_CONTENT/M0001/BIAU/f04.htm?open

According to Taiwan Standard, 又 should be closed.
When something in 又 (aka. 叉、蚤), 又 should be opened.

Glyph '又' of Source Han Sans looks correct,
however, '設' and '沒' are not well closed. (But, '役' seems correct in light weights.)

'叉' and '蚤' are wrong.

![sroucehan-1](https://cloud.githubusercontent.com/assets/5418570/4233543/95719f06-39ac-11e4-83fa-99f2236fadda.png)

**Comment by kenlunde** [comment]
I just prepared a [file](http://blogs.adobe.com/CCJKType/files/2015/01/shs-issue-61.pdf) that I will be using to resolve this issue.

**Comment by kenlunde** [comment]
I finally had a chance to wade through this issue, and concluded that while we will eventually address this issue, it won't happen in the pending Version 1.002 update. It is likely to be addressed in the Version 2.000 update, which will make several adjustments to the glyph set.

I found that remapping existing glyphs will fix only four of the characters. To address this issue completely, some new (TW) glyphs will be needed, but I also want to explore the possibility of modifying existing CN (or JP) glyphs to address this issue. I will need to consult with our designer and SinoType's designers about that possibility.

**Comment by kenlunde** [comment]
Consolidated with Issue #99.
