### ISSUE TITLE
No way to easily download specific formats/languages

### ISSUE THREAD

**Issue by codeman38** [adobe-fonts/source-han-sans#64]
In the now-deprecated SourceForge download page for Source Han Sans, there were individual zip files for each format and, for the language-dependent formats, for each language. This does not appear to be possible with the GitHub release - the only option, other than downloading each font file individually, is to download a single monolithic 700MB file containing all of the formats for all of the languages.

**Comment by kenlunde** [comment]
I am planning to package all of the weights together—for the language-specific OTFs, OTCs, and region-specific subset OTFs—as zip files as part of the Version 1.002 update that should happen during the first half of this year. Sort of like this:

SourceHanSansSC-1.002.zip
SourceHanSansTC-1.002.zip
SourceHanSansJ-1.002.zip
SourceHanSansK-1.002.zip
SourceHanSansCN-1.002.zip
SourceHanSansTW-1.002.zip
SourceHanSansJP-1.002.zip
SourceHanSansKR-1.002.zip
SourceHanSansOTC-1.002.zip

This is how the installable font resources were packaged in the now-retired SourceForge repository.

**Comment by ShikiSuen** [comment]
Oh I received this email and misunderstood that the SHS 1.002 has already been published...

**Comment by kenlunde** [comment]
We're still at least two months from releasing Version 1.002. Apologies for the confusion.

**Comment by ShikiSuen** [comment]
@kenlunde That's fine, thanks for telling me this and I don't need to change my recent schedule on extracting my time for forking SHS UI 1.002.

**Comment by kenlunde** [comment]
For the Version 1.002 update, I am planning to *add* the following ZIP files to the "release" branch, meaning that the individual OTFs and OTCs can still be downloaded:

OTC/SourceHanSansOTC_EL-R.zip
OTC/SourceHanSansOTC_M-H.zip
OTF/SourceHanSansJ.zip
OTF/SourceHanSansK.zip
OTF/SourceHanSansSC.zip
OTF/SourceHanSansTC.zip
SubsetOTF/SourceHanSansCN.zip
SubsetOTF/SourceHanSansJP.zip
SubsetOTF/SourceHanSansKR.zip
SubsetOTF/SourceHanSansTW.zip

Note that the ZIP file for the OTCs needed to be split into two ZIP files—one for ExtraLight through Regular, and another for Medium through Heavy—because it exceeded GitHub's 100MB file limit.

Thoughts?

**Comment by ShikiSuen** [comment]
@kenlunde 
Based on your reply above, does it mean that there will be no superOTC available in 1.002?

**Comment by kenlunde** [comment]
The Super OTC is already a ZIP file. ;-)

**Comment by ShikiSuen** [comment]
@kenlunde 
Got it. Thanks.

One more question: Could you please tell me the ascender and descender (not winasc & windesc) parameters current adopted in SHS 1.002 (if different than SHS 1.001)? I need this information for reference unless SHS 1.002 has other metric changes.

**Comment by kenlunde** [comment]
Also, because the Super OTC is an all-in-one deployment format, if someone downloads it, they have no reason to download any of the othe deployment formats.

About the changes to the vertical metrics, please wait until the official Version 1.002 release, which is very close.

**Comment by ShikiSuen** [comment]
Copy that. I will decide whether I should close SHS-UI repo after official SHS 1.002 got released.

**Comment by kenlunde** [comment]
Fixed in Version 1.002.
