### ISSUE TITLE
SubsetOTF garbled in Photoshop "Windows LCD / Windows / Mac LCD / Mac" text rendering mode

### ISSUE THREAD

**Issue by LiXiangchen** [adobe-fonts/source-han-sans#67]
SubsetOTF versions will garbled in Photoshop "Windows LCD / Windows / Mac LCD / Mac" text rendering mode, but "Full-glyphs-OTF" versions has no problem.

![image](https://cloud.githubusercontent.com/assets/8857634/4355572/0e34d486-424e-11e4-93e3-c383428f8579.png)

I found that the reason is CID indexes in SubsetOTF are not continuous, this causes to glyphs mapping dislocation.

For more information about this issue could see my Chinese article: http://zhuanlan.zhihu.com/itsuka/19853974

Undoubtedly, this is a bug of Photoshop, but before their team fixed it, this can be solved by using the blank glyphs to fill all the vacant CIDs.

**Comment by kenlunde** [comment]
I am closing this issue because the next version of Photoshop is expected to address this issue.

**Comment by kenlunde** [comment]
This should now be fixed in Photoshop CC 2015.
