### ISSUE TITLE
Components of U+3B05 㬅

### ISSUE THREAD

**Issue by mandel59** [adobe-fonts/source-han-sans#68]
The components of U+3B05 in Source Han Sans are ⿳日罒万. Is it correct?
I've compared Source Han Sans and some other fonts, and found that some are consist of  ⿳日罒方 and others are of ⿳日罒万.
![2014-09-22 15 05 52](https://cloud.githubusercontent.com/assets/1079715/4358304/074c099e-4269-11e4-9049-95f6a41ffc44.png)

**Comment by kenlunde** [comment]
Fixed in Version 1.002.
