### ISSUE TITLE
Source Han Sans Simplified Chinese: The double quotation marks are strange. 

### ISSUE THREAD

**Issue by lseed** [adobe-fonts/source-han-sans#71]
Font: Source Han Sans Simplified Chinese
The double quotation marks are strange. The distance between the 2 single quotes is too large. Please shorten the distance and make the 2 single quotes more close, like they do in other fonts. Thanks.

This is the way the double quotation marks look normally:
“可以显示中文吗？”
While with the font of Source Han Sans Simplified Chinese, the double quotes look this way:
‘　‘可以显示中文吗？’　’

**Comment by be5invis** [comment]
Everything looks OK on word 2013
![image](https://cloud.githubusercontent.com/assets/240091/6484319/dcf94698-c2b5-11e4-9fc9-48ccf896bd03.png)

**Comment by kenlunde** [comment]
Given what has been discussed, this is clearly an issue with MS Word, and any fix needs to come from Microsoft. I am closing the issue, and will re-open if deemed necessary.
