### ISSUE TITLE
Polish 圖

### ISSUE THREAD

**Issue by orangeparanoid** [adobe-fonts/source-han-sans#74]
I have taken a screenshot to show different versions of 圖. I think that this character needs to be polished.

https://drive.google.com/file/d/0ByXittg7F1LbVkNiVGMxRjBkaTg/view?usp=sharing

The middle vertical "dot" or "line" should be 90 degrees. 

I am talking about TW and CN versions.

Please take a look. Thank you for improving.

**Comment by hfhchan** [comment]
Just FYI, the straight short dot ceases to exist anywhere else in Fangti or Songti standard.  According to the CNS11643 website the character is composed of a [slanted dot + horizontal stroke] component but the provided Kai script snapshot uses a short downward dot.

Strange thing though, Microsoft Jhenghei uses straight down like Fangti, while PMingLiu uses slant left stroke, like the original.

**Comment by kenlunde** [comment]
Looking at my notes for Version 1.002 changes, I noted that the glyph for uni5716-CN needs to be corrected: the stroke in question should be completely vertical. Also, the JP glyph for U+5716, uni5716-JP, will be used for the TW fonts. The glyph for uni5716-TW is likely to be removed in Version 2.000.

**Comment by kenlunde** [comment]
Fixed in Version 1.002.
