### ISSUE TITLE
Doubts about SHS's font metric settings.

### ISSUE THREAD

**Issue by ShikiSuen** [adobe-fonts/source-han-sans#76]
**Be advised that this thread is already out of its initial topic but had led to some useful conclusion.**
**That's why I changed the topic of this issue.**
It's Yosemite's bug that some UI elements omits the lineGap value while some are not, the conclusion is to make lineGap into 0 to make sure its best compatibility among all possible display occasions.

==============================
Following contents are **out of date**.

==============================
This issue is only for suggestion on SHS's descender setting. All of those contents concerned about SHS's usage, as Yosemite's GUI font, are examples.

Source Sans Pro:
![image](https://cloud.githubusercontent.com/assets/3164826/4691536/03429f34-5722-11e4-8d2e-c18a19db1eb3.png)

Source Han Sans:
![image](https://cloud.githubusercontent.com/assets/3164826/4691542/1b3ab23e-5722-11e4-8d11-67cb47754401.png)
![image](https://cloud.githubusercontent.com/assets/3164826/4691551/a0845a30-5722-11e4-8dbe-bf36b19a8c1f.png)

This is the reason why SHS could cause some Apps (like iMessage) have issue like this: #41 
Probably these apps should do some modifications to fit SHS well,

but SHS really needs to allow its underline across & avoid all descenders,
just like what Source Sans Pro does.
**It's weird that SHS and Source Code Pro don't share their descender settings with each other.**

**Comment by ShikiSuen** [comment]
to @kenlunde : 

I have to set the current LineGap from 100 to 0 and change the Ascender by adding the LineGap value up: from 880 to 980.

The reason why I migrate the LineGap value up to the Ascender is because of OS X's following defect:

> OS X Yosemite has serious problem regarding its UILabel elements: they omit the lineGap data, cause display malfunction among multi-line filenames in Finder if the display font has lineGap data.

The example of such issue is like this:
![image](https://cloud.githubusercontent.com/assets/3164826/5994200/5c93b8f4-aa27-11e4-88a9-c93ea600c826.png)

Thus, the Source Han Sans UI, formerly SHSDeskInterface, has been updated last night:
https://github.com/ShikiSuen/SourceHanSansUI

The current-modified-parameters are:<pre><code>
  Ascender 980;
  Descender -120;
  LineGap 0;</code></pre>

And now it is correctly displayed:
![image](https://cloud.githubusercontent.com/assets/3164826/5994208/aa393ed0-aa27-11e4-9dc7-7df08a230bf0.png)

//I just made sure that all glyphs could be displayed completely. The reason why I hadn't use HelveticaNeueDeskInterface's Ascender and Descender parameters is to avoid triggering iMessage line-height issue again (Hiragino Kaku Gothic ProN, the default Japanese GUI font in Yosemite, has such problem).

Hope that you Adobe could let Apple informed regarding this issue, or otherwise this issue will still exist among those apps which doesn't use HelveticaNeueDeskInterface as their default English GUI fonts.

**Comment by kenlunde** [comment]
Thank you for this continuing testing of various line-layout settings.

My current feeling is that 880, -120, and 0 might be the ideal values for table values in question. I strongly hesitate to adapt 980 as the first value on the grounds that it is for patching unintended end-user modifications. I would rather provide Apple an opportunity to fix apparent poor behavior in a future version of OS X.

**Comment by ShikiSuen** [comment]
@kenlunde 

No problem since I treat such work as my duty before Apple adapts SHS as their default GUI font.
(Their department in China had already known my concerns, but their localization team are nerds on such point... still, only time could tell.)

What I know is that [880, -120, 0] could cause SHS displays glyphs incompletely (horizontally cut-down) in OS X's Font Book app. If we are intended to keep [880, -120, 100], Apple must fix OS X's problem on omitting LineGap data while displaying fonts in some UI Elements. (Otherwise, even though we did efforts, bug could still exists on those apps which are using English fonts other than HelveticaNeueDeskInterface)

**Comment by ShikiSuen** [comment]
//This is just a courtesy notice that I edited my last reply. (This reply will be removed as soon as it has been sent to mail-subscribers)

**Comment by ShikiSuen** [comment]
@kenlunde You are absolutely right as I had just had some time to test the parameters you provided after a bunch of heavy workload from campus:
![image](https://cloud.githubusercontent.com/assets/3164826/6100966/7e1e9c1c-afd8-11e4-8db5-ae089439efa9.png)
Everything looks normal based on your parameters.

The reason I met the "incompletely glyph display" issue, as what I recalled in my last reply, is because the "Asc - (- Desc)" is less than 1000.

**Comment by ShikiSuen** [comment]
//(Inherits my last reply)
Besides, we could see on the 1st line of the attached picture that the issue "incompletely glyph display" still exists, but that's Fontbook.app's issue.

**Comment by kenlunde** [comment]
So, it seems like a good change for Version 1.002 would be to change the OS/2.sTypoLineGap (and hhea.LineGap and vhea.lineGap) setting from 500 to 0 (zero).

**Comment by ShikiSuen** [comment]
If so, 本当に感謝します。 That means the SHS-UI repo could be shut down if official SHS 1.002 adopts such modification.

**Comment by ShikiSuen** [comment]
P.S.: I hadn't change the vhea.lineGap yet because I don't think there are vertical typeset necessities among OS X's UI elements. But your choice might be better if OS X really has or will have vertical GUI text typeset.

**Comment by kenlunde** [comment]
This change would be effected by adding the following table overrides in the "features" files that are used to build the fonts:

table vhea {
  VertTypoLineGap 0;
} vhea;

table OS/2 {
  TypoLineGap 0;
} OS/2

The first override affects only the 'vhea' table. The second override affects the linegap values that is specified in the 'OS/2' and 'hhea' tables (the AFDKO *makeotf* tool keeps these two values in sync).

**Comment by ShikiSuen** [comment]
@kenlunde Could you please take a look at this? (see its comment thread):
http://github.com/ShikiSuen/SourceHanSansUI/commit/6df7ce6fe6c9346b706131fcf7405d66b230369b#commitcomment-9696669

**Comment by ShikiSuen** [comment]
Personally thinks that Ascender and Descender using [1000, -234] will be better if LineGap is Zero.
(Fully Tested; this set of number comes with Hiragino Kaku Gothic ProN's WinAsc and WinDesc.)
This will display correct in Safari but incorrect at YouTube in recent builds of Google Chrome.
(I, at this moment ,assumed that it's the issue of Google Chrome itself with Youtube)

**Comment by ShikiSuen** [comment]
P.S.: Looks like Google Chrome with Youtube always have this issue if LineGap of SHS is Zero, whatever Ascender and Descender is between [880, -120] or [1000, -234]
![image](https://cloud.githubusercontent.com/assets/3164826/6254718/057af638-b768-11e4-841b-cae889ec5179.png)

**Comment by ShikiSuen** [comment]
I will update my font installation script which will install both Current SHS Official Build and SHS-UI, and the new script will specify current Adobe Official Build as webpage default font.

**Comment by kenlunde** [comment]
Once I have the Version 1.002 fonts built, but before they are released, we'll be performing our own testing, with a strong focus on these line-spacing issues.

**Comment by ShikiSuen** [comment]
Copy that. ご苦労様です。

One more thing to suggest:
We could always find less trouble if we do font testing on a completely reinstalled system with new local account created (no system migration from backups and old computers). I had just tested on a newly installed system on a formatted partition, and the issue I mentioned today does not exist on such configuration.

**Comment by kenlunde** [comment]
We're fully aware of the need to nuke font caches and the like when testing fonts with tweaked values, but what you wrote is a prudent reminder to yourself and others. Thank you.

**Comment by ShikiSuen** [comment]
You're welcome.

**Comment by ShikiSuen** [comment]
@kenlunde I have curiosity on your usual manner on "nuking font caches and the like".
I always run `sudo atsutil databases -remove` but it seems that it works nothing on my old laptop.

**Comment by kenlunde** [comment]
That is the command line that I use. You need to be sure to restart the machine after executing it. For Adobe font cache files, removing the following files usually does the trick:
~~~
~/Library/Caches/Adobe*/*/AdobeFnt*.lst
~~~
Although I have no experience with it, you might also try [FontNuke](http://jamapi.com/pr/fn/) for OS X.

**Comment by kenlunde** [comment]
Fixed in Version 1.002.
