### ISSUE TITLE
Full width solidus weight

### ISSUE THREAD

**Issue by beachmat** [adobe-fonts/source-han-sans#84]
We've noticed that the full width solidus is the same weight in the different weights of the font. I don't know if there was a reason for that but a Japanese person has told me it doesn't look right.

**Comment by kenlunde** [comment]
The glyph for U+FF0F was (and while we're there, the glyphs for U+2015, U+FF3C, U+FF3F, and U+FF5C were) inherited from Kozuka Gothic. The glyphs do vary by weight, with ExtraLight being lighter than Heavy, but the affect is somewhat subtle. Looking at the glyphs for these five characters in Kozuka Mincho, only those for U+FF0F and U+FF3C vary by weight, and the effect is even more subtle than in Kozuka Gothic.

Thank you for reporting this issue. I will ask the designer whether she feels that these glyphs need to be adjusted to vary more by weight.

**Comment by beachmat** [comment]
Yes I think it's more of an issue in the bolder weights.

**Comment by kenlunde** [comment]
The typeface designer, Ryoko Nishizuka, seriously considered this issue, and consulted with several leading typographers in Japan. She concluded that the glyphs are okay as-is, and thus do not require adjustment. Typographers actually prefer lighter-weight versions of these characters when the nominal weight is heavy, and if their selected font includes heavier-weight versions, they will often seek out a different font for these particular characters.

Of course, if you prefer more weight variation for the glyphs for these characters, you are welcome to fork the project and modify the glyphs.
