### ISSUE TITLE
Strokes in 途 for TW

### ISSUE THREAD

**Issue by RyanChng** [adobe-fonts/source-han-sans#86]
I noticed that in Source Sans TW, the second stroke of 途 is a na (捺) and not a dian (点) - it should be a dian in order to comply with Taiwan MOE standard. This glyph is not shared with any of the other languages so I think it should be corrected. By the way, in the upcoming experimental HK, it should be second stroke being dian and the 5th stroke is hooked (whereas in TW the 5th stroke isn't hooked. No problems there for TW.)

**Comment by kenlunde** [comment]
Thank you for reporting this minor issue, which affects the glyph named uni9014-TW (see the screenshot taken from a poor scan from the Taiwan MOE glyph standard), and which we should be able to fix in the forthcoming Version 1.002 update.

![taiwan-moe-heiti-104151-uni9014-tw](https://cloud.githubusercontent.com/assets/3988788/6318736/03bed7e6-ba57-11e4-8e2d-d0385491da72.png)

**Comment by RyanChng** [comment]
Thank you. I have noticed a similar issue with the word 怒, same issue where the 捺 should be changed to a 点. Perhaps it's because the team is following the glyph standard scans... those aren't that helpful due to the low resolution. I recommend reading this document, which details the principles of the MOE standard (it's only in Chinese though). Especially the detailed explanation on the many forms of a simple compound like 又. Makes for interesting reading - https://www.google.com.sg/url?sa=t&source=web&rct=j&ei=HvnqVIHLJcO8uASVmoHIDg&url=http://diction.myweb.hinet.net/dict/01lunwen/10doc.pdf&ved=0CCsQFjAG&usg=AFQjCNGDJeI5EHuvrN1Q8U-Y1Ddy61SWNQ&sig2=hJQ8LPxbI9AaiIs6-tUuqw.

**Comment by kenlunde** [comment]
The issue with the glyph for uni6012-TW (怒) is best to be addressed as part of Issue #61, which I expecting to happen for the Version 2.000 update that will include adjustments to the glyph set (there will be some additional glyph sharing, mainly between JP and CN, that will allow some glyphs to be removed, which is important because addressing that Issue requires a small number of additional glyphs).

**Comment by kenlunde** [comment]
The fixed version of uni9014-TW is shown below.

![uni9014-tw-fixed](https://cloud.githubusercontent.com/assets/3988788/6392949/abe42e0a-bd7a-11e4-9164-d46d4f310ba9.jpg)

**Comment by RyanChng** [comment]
Looks good, thanks!

**Comment by kenlunde** [comment]
Fixed in Version 1.002.
