### ISSUE TITLE
About the embed things

### ISSUE THREAD

**Issue by changziguan** [adobe-fonts/source-han-sans#87]
Thanks for all of your hard work and outstanding contributions. The source han sans is a set of gorgeous fonts.

Here is my problem. When  I use the fonts in PowerPoint(Microsoft Office), the fonts can't be embedded in slides. 

![image](https://cloud.githubusercontent.com/assets/11370901/6544175/f3746cac-c57d-11e4-853f-8bd489400b19.png)

>The warning means "The source han sans fonts can't be saved with the slides.

So if I use  slides in other place, I must install the source han sans fonts on the computer which is not mine.

Is there something can't be fixed?

I am looking forward to your reply.

Thank you.

David

**Comment by miguelsousa** [comment]
Microsoft Office programs [do not support embedding `.otf` fonts in documents](http://support.microsoft.com/kb/908475).

**Comment by kenlunde** [comment]
The work-around, which I employ on a regular basis because I also use PowerPoint for making presentations, is to save the final set of slides as PDF.

**Comment by KrasnayaPloshchad** [comment]
You can try some virtual printers to avoid that, such as CutePDF, doPDF, PDFCreator.
