### ISSUE TITLE
Suggestion about adding U+20AB ₫ DONG SIGN

### ISSUE THREAD

**Issue by acuteaccent** [adobe-fonts/source-han-sans#91]
Source Han Sans is a CJKV font that covers the characters used in Simplified Chinese, Traditional Chinese, Japanese, Korean, and Vietnamese.

However, it is interesting that Source Han Sans only includes the currency symbols used in China (¥ and ￥), Taiwan ($ and ＄), Japan (¥ and ￥), and Korea (₩ and ￦) – it does not include the one for Vietnam (₫).

Thus, I suggest adding U+20AB ₫ DONG SIGN to Source Han Sans.

**Comment by kenlunde** [comment]
The glyph for U+20AB was already added for Version 1.002. &#x263A;

**Comment by kenlunde** [comment]
Fixed in Version 1.002.
