### ISSUE TITLE
Stroke of U+95F4 (间) for Source Han Sans Simplified Chinese

### ISSUE THREAD

**Issue by fatloong** [adobe-fonts/source-han-sans#93]
I noticed that the stroke"gou(钩)" of the component"门" of glyph"间(U+95F4)" seems not long enough. It looks like disappeared and not clear when fonts size is small, especially on the screen of cellphone.
However when "间" as a component of glyph"简(U+7B80)", the storke“gou(钩)” looks like to be normal. 
![p1](https://cloud.githubusercontent.com/assets/11400000/6819257/267e13d6-d2f9-11e4-992b-2662a4a4fa40.png)

My another doubt is why the component"日" looks a little different between glyph "间" and "简"and their style is not coincident although these two "间" is a same glyph.
![p2](https://cloud.githubusercontent.com/assets/11400000/6819366/fcc31a12-d2fa-11e4-8a0a-5267562356e2.png)

**Comment by kenlunde** [comment]
While it's too late to fix this minor issue in Version 1.002, because the fonts were built a week ago, and are currently undergoing testing prior to their formal release, this has been noted for the subsequent version.

**Comment by kenlunde** [comment]
Consolidated with Issue #99.

**Comment by kenlunde** [comment]
Consolidated with Issue #178.
