### ISSUE TITLE
"草" doesn't look right in bolder weights

### ISSUE THREAD

**Issue by felixonmars** [adobe-fonts/source-han-sans#94]
I am marking the wrong ones red in the following screenshot:

![2015-04-02-112558-17d4ad](https://cloud.githubusercontent.com/assets/1006477/6957160/105d6d58-d92b-11e4-94da-5861a8bf7890.png)

Sorry I don't know how to describe, but I still hope this is helpful :)

**Comment by kenlunde** [comment]
It'd be useful to know the environment (OS, application, and so on) that is producing these results. If an inferior rendering engine is being used, then it would be considered a non-issue.

**Comment by felixonmars** [comment]
It's on Arch Linux x86_64, the Application is Firefox 37. I can also reproduce it on Chromium 41, but it's a little bit different:

![2015-04-02-115205-a533c9](https://cloud.githubusercontent.com/assets/1006477/6957521/b5c1c502-d92e-11e4-8e40-8dbe97138ef2.png)

I have just tried it on Windows 10, and didn't get the problem across the browsers I have tested (Chrome, Firefox, Opera, IE11, Project Spartan).

**Comment by felixonmars** [comment]
Here is the test page: http://pkgbuild.com/~fyan/test/fonttest.html

**Comment by kenlunde** [comment]
I changed "CN" to "SC" in your test page (because I am using the Super OTC with all 28 65,535-glyph font instances), and tried it on all three browsers (Chrome v41, Safari v8, and Firefox v36) on my system (I use OS X). The results look the same, and don't exhibit the distortion of Radical 140.

![osx-result](https://cloud.githubusercontent.com/assets/3988788/6963911/1043c966-d8f9-11e4-92ff-bb8038698fd9.png)

I suggest that you find out what version of FreeType that your OS is using. It may be less than v2.5.0.1, in which case it would have substandard rendering of CFF outlines.

**Comment by felixonmars** [comment]
The OS is using freetype v2.5.5 (latest), and looks like your DPI is much higher than mine, not sure if that matters though.

**Comment by kenlunde** [comment]
DPI matters, but other artifacts in your rendering example suggest that FreeType may not be configured correctly. (For anyone else who is reading this, the character in question is U+8349 (草), and its glyph is CID+34378.)

I made another example, adding a range for 7 through 13px.

![osx-result-7px](https://cloud.githubusercontent.com/assets/3988788/6964261/49462b66-d8fc-11e4-808d-0d197bfdd0c7.png)

**Comment by felixonmars** [comment]
I see, thanks a lot!

I have just tried to set hintstyle to `hintnone` and the problem goes away immediately. Setting the key to `hintslight` or `hintfull` makes it appear again.

If I understand it correctly, the Adobe native CFF hinter will be enabled by default since v2.5 of freetype, and `hintfull` should be recommended for CFF fonts since then.

Any hints?

**Comment by felixonmars** [comment]
I think I found it. Disabling `autohint` fixes this, and now I can use `hintfull`. Here is how it looks like now:
![2015-04-02-212617-e0763e](https://cloud.githubusercontent.com/assets/1006477/6964773/f46a8b0e-d97e-11e4-93a3-74543b38ea72.png)

Really sorry for the noise!

**Comment by kenlunde** [comment]
Yes, I believe that autohint ignores the hints in the fonts and attempts to hint them. The Source Han Sans fonts are fully-hinted, so I suspect that disabling autohint is the right thing to do.

No worries about the noise. When in doubt, it is always best to ask.

Enjoy the fonts!

**Comment by davearnold** [comment]
You are correct. The original rendering was using autohint.

In the Bold font, gid 34378, the top hstem runs from 685 to 790, and there is an hstem hint for this. The two short vertical strokes extend up to 846, but their tops are unhinted. The FreeType autohinter applies hints to both the hstem and the tops of the vstems, and at some sizes these two edges (790 and 846) are aligned to the same pixel. When this happens, the short stubs disappear. If the native font hints are used, the stubs will always extend above the top edge of the hstem.
