### ISSUE TITLE
Missing U+332C

### ISSUE THREAD

**Issue by LiXiangchen** [adobe-fonts/source-han-sans#95]
I found that all chars of Unicode block U+3300-33FF were in font without U+332C, why?

**Comment by kenlunde** [comment]
See Issue #78.

**Comment by LiXiangchen** [comment]
Thank you, Ken. BTW, may I know when the next version released?

**Comment by kenlunde** [comment]
The Version 1.002 fonts were built late last month, and are currently being tested (by Adobe and Google). The current plan is to make the release sometime this month.

**Comment by LiXiangchen** [comment]
Looking forward to release.
