### ISSUE TITLE
U660E (明) - Different glyph for TC&SC, is this necessary?

### ISSUE THREAD

**Issue by tamcy** [adobe-fonts/source-han-sans#97]
明's radical "日" is unnecessary thin in TC & SC version, while the one KR/JP look much better. I doubt if there is really a need (e.g. due to a the standard of a region) to have two separate glyphs for this codepoint? Thanks.

![u660e](https://cloud.githubusercontent.com/assets/959433/7206062/640f7ab8-e560-11e4-8ef4-bbdd522bb338.png)

**Comment by kenlunde** [comment]
The release notes in Version 1.002 will note that the next major version will include enhancements such as this, meaning more sharing of glyphs across languages, particularly between Japanese and Simplified Chinese, which should free up enough CIDs to tackle the Hong Kong issue, which requires additional glyphs.

I may open a new Issue that will be used to track such candidates, as a way to consolidate them into a single Issue.

**Comment by kenlunde** [comment]
Consolidated with Issue #98.
